### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Akihisa17** [Drutol/MALClient#100]
(Hello. I dont know if this is the right place to ask this. XD)
But would you mind if you can also add another feature where we can view images from Profile Comments? Example: Images hidden in Spoiler button.  Would love to see that~

**Comment by Drutol** [comment]
Hello, yeah it's the best place to ask!

Should be a matter of 1h max, you can expect it early next week on the store :)

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/22624458/0e84daa0-eb7d-11e6-8d87-164e6eb8d98b.png)

One day I'll probably want to mix text and images into one whole post, but this should suffice for now :)

**Comment by Akihisa17** [comment]
Wow. That was quick. Haha
Looks great! Thanks you so much! Yes, its more than enough for now. :) 
Will wait next week then~ Thanks again!
