### ISSUE TITLE
New suggestions ToDo

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#102]
Yo there,
* Lockscreen notifications
* cortana integration (:P) 
* better search engine (MAL default search does not work well inside app, in website it works perfect; even a partly typed name gets found; no idea why that happens)
    * It would've to be fully scrapped from html, but yes... search needs more love.
* custom anime recommendations (like the Aozora Discover app in iOS; Aozora is also a MAL client app, but it is limited to iOS. They have one of the most intelligent AI anime recommendation system.)
* anime news network feed integration (ANN news is way better than MAL news)
* cloud sync with the android app 
    * This needs server and I'm not going to buy one.

^_^ Try whatever is possible among these @Drutol

**Comment by Drutol** [comment]
Welp, I just found an endpoint for MAL search that returns JSON! Now I need to stop myself from doing android xd

**Comment by sinofanger** [comment]
And I am here checking the windows store daily to see updates for MalClient :P

**Comment by Drutol** [comment]
Well, I'm doing android now and it'll take a while to switch... + I started playing Wildstar ^^
