### ISSUE TITLE
Auto refresh on launching

### ISSUE THREAD

**Issue by Accelyte** [Drutol/MALClient#111]
I don't know whether I should label this a bug or not, but I guess that should be the intended behaviour. Just finished a series, marked it as 'completed' on MAL on my phone, but when I opened MAL on my laptop the entry was still listed as unfinished.

**Comment by Drutol** [comment]
Well, this doable but tricky without server infrastructure, you can select how often data gets synchronised in Caching settings. I may come back to this if I somehow will want to make cloud sync with Android versions though.

**Comment by Accelyte** [comment]
You probably misunderstood what I meant, I mean the client should do a refresh when it initially launches, not autorefresh every second.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/23666594/bf7e5b92-035b-11e7-821a-ecf0f6101942.png)

Not true unless something has bugged. This setting affects majority of cached data and what's checked first is whether data is present and then whether it's valid if not it's pulled again. Anime Library data is requested automatically once per app run on start-up.

**Comment by Accelyte** [comment]
Hmm...I left it as default. I've just changed it to 10 minutes, I'll see how it turns out. I was a tad concerned about my library not updating, but I'll check back.

**Comment by Drutol** [comment]
One day is probably a bit too much, I'll change the default value to something smaller.

**Comment by Accelyte** [comment]
It's working now, maybe it was the cache settings. Why not force a data pull every time the program is launched to make sure the data is up to date? I don't think many people will leave the app open for that long for the timed refresh function to take effect.

**Comment by Drutol** [comment]
Decreased default cache validity time to 2 hour i.e. all startups within 1h won't update library.
Additionally I've added syncing last anime/manga update time across all W10 devices, it's a bit random at when it actually syncs but it should trigger within 2h timespan.
