### ISSUE TITLE
Can we have this feature.

### ISSUE THREAD

**Issue by Katsuga50** [Drutol/MALClient#112]
![image](https://cloud.githubusercontent.com/assets/19756597/23833369/55eb3764-076a-11e7-8713-e25a17f93ee7.png)

When right clicking on some apps' live tiles then it shows some quick options like the ones in the pictures. Can we have it. Like search button, watch list etc

**Comment by Drutol** [comment]
Hi!

I'm not sure to be honest, brief searching didn't yield any info to my surprise. I'll try to find something though ^^

**Comment by FoxInFlame** [comment]
@Drutol I think that this is made possible using Jump Lists.
I've never developed an UWP before, but some research gave me this:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.startscreen
https://docs.microsoft.com/en-us/uwp/api/windows.ui.startscreen.jumplist

A google search for Jump List showed similar images to the one posted by Katsuga50, so I think this is it. 
Does it help?

**Comment by Drutol** [comment]
First time I'm hearing this term. Should be easy enough to do :) 
Now let's just find some time...

Big thanks!

**Comment by Katsuga50** [comment]
Yeah its Jump List. I forgot the name.

**Comment by Drutol** [comment]
If I have enough time today I'll push micro update with this today :)

**Comment by Kimod** [comment]
How about?
 * Profile
 * Manga list (and if you have start page set on manga list make it anime list instead)
 * Flyout with pinned forum posts? Or watched? I don't even know if it would be useful to have it there...
 * ... >_>

Can't really think of many other useful shortcuts :/

**Comment by Drutol** [comment]
One day... I'll want to make tiles for forum topics...

**Comment by FoxInFlame** [comment]
- Recently viewed pages in MALclient (as a list)
- Messages

**Comment by Drutol** [comment]
* Messages 
 * seem relevant enough as they are accessible by somewhat small button.
* Profile
 * Why not
* Anime/Manga list
 * This is what's launched by default...

**Comment by Kimod** [comment]
> Anime/Manga list

No you don't understand (at least I think). If you have anime list to launch by default, have manga list in the jump list. If you have manga list selected to launch by default, have anime list in the jump list.

**Comment by Drutol** [comment]
Yup I didn't understand. 
I don't know how many ppl have set manga to default page but I'm guessing that there's very little of them and I'm not sure whether it's worth adding

**Comment by Drutol** [comment]
Got it to work, but no update today... I have to adjust a few things (these icons for example)
![image](https://cloud.githubusercontent.com/assets/6102530/23913892/9d23c562-08e4-11e7-8a8a-235a2cf346c7.png)
