### ISSUE TITLE
Drag-to-update is blocked by neighbouring posters

### ISSUE THREAD

**Issue by Accelyte** [Drutol/MALClient#113]
The most commonly used feature would be the watched episode +1, so I think it would be a good idea to put a quick update button on the cover of the series poster, like so:
![applicationframehost_2017-03-15_16-57-15](https://cloud.githubusercontent.com/assets/21363469/23960816/e328836a-09a0-11e7-8428-802438c05e54.png)

**Comment by Drutol** [comment]
Try this: Drag item to right/left.

**Comment by Accelyte** [comment]
I'm not on a device with touchscreen so that's a bit hard...

**Comment by Accelyte** [comment]
It's really weird to do it with the cursor but now I see it. The dragging mechanic is a bit buggy, if my cursor moves over the next poster the sliding motion stops.
![2017-03-17_16-02-45](https://cloud.githubusercontent.com/assets/21363469/24051817/425c0cea-0b2b-11e7-8e6e-7567201e4c26.gif)

How about an option that's more favourable to mouse/cursor users?

**Comment by Kimod** [comment]
You can click on the watched episodes (the number bellow W). It will bring up menu with numbers: 
![numbers selection](https://cloud.githubusercontent.com/assets/6088494/24072338/52679f08-0be6-11e7-906e-ed98646c761f.gif)

**Comment by Accelyte** [comment]
Ooh I didn't know that, thanks :)
It's mainly because I use PocketMAL on my phone and the app made it really obvious by adding a triangle indicator.  I think a+1 button would be a nice touch and should be a default option. Noone's gonna skip from episode 1 to episode 7 all of a sudden.
![screenshot_20170318-154059](https://cloud.githubusercontent.com/assets/21363469/24073598/90e6d838-0bf1-11e7-9cbb-432f6320c80b.png)
![screenshot_20170318-154104](https://cloud.githubusercontent.com/assets/21363469/24073599/90e9b562-0bf1-11e7-8490-8fdb7e001da3.png)

**Comment by Drutol** [comment]
I'm reluctant to adding 3rd way of incrementing episodes + drag is really quick in my experience.
Especially when there are 2 different view modes which have dedicated +/- buttons :)

**Comment by Accelyte** [comment]
Can you add a quick fix for the dragging issue then? I'd like to use it as my default method to update lists as well but the issue makes it a bit hard to do so.

**Comment by Drutol** [comment]
I wish it was that easy to fix :( 
No promises

**Comment by Accelyte** [comment]
Good luck I guess? :D

**Comment by Guerra24** [comment]
One year later... This bug can happen in two cases: the cursor moves too fast and leaves the rectangle or the cursor goes into the rectangle on the right. Gonna take a look and see what can be done.

**Comment by Guerra24** [comment]
![2018-05-17_01-39-08](https://user-images.githubusercontent.com/9023392/40163371-d782c9f2-5973-11e8-814c-20bb211fb30a.gif)
