### ISSUE TITLE
Add scrollbar in "Search" view

### ISSUE THREAD

**Issue by Guerra24** [Drutol/MALClient#114]
It would be very useful.

**Comment by Drutol** [comment]
Hi, do you you mean "suggestions" view?

**Comment by Guerra24** [comment]
@Drutol [This view](https://puu.sh/uZN86/573eb794a8.png).

**Comment by Drutol** [comment]
The bar that appears when you type something, search suggestions?

Or something has gone terribly wrong and scroll doesnt work for search results?

**Comment by Guerra24** [comment]
For me doesn't work. [img](https://puu.sh/uZOpr/43364f138a.png)

**Comment by Drutol** [comment]
Roger!

**Comment by Guerra24** [comment]
Found the same issue inside the news and articles, when the content is on view.

**Comment by Drutol** [comment]
There's a setting for scrollbar visibility in articles :)

**Comment by Guerra24** [comment]
Oh, sorry! didn't know.

**Comment by Drutol** [comment]
Fixed
