### ISSUE TITLE
Broken stats bars in low horizontal size

### ISSUE THREAD

**Issue by Guerra24** [Drutol/MALClient#115]
[Video](https://puu.sh/v41Kt/41daf441af.mp4)

**Comment by Drutol** [comment]
Roger, sorry that I won't do it immediately due to Android and these issues being pretty minor.
I'll release them in batch next week probably, or if something breaks terribly. :)

**Comment by Guerra24** [comment]
@Drutol No problem, take your time :) (Also, android HYPE!).

**Comment by Drutol** [comment]
If you say so, I'm hyped a quite bit too :D

**Comment by Drutol** [comment]
Well, I'm unable to reproduce this

**Comment by Kimod** [comment]
Well, it's easy to reproduce, just don't give Profile page enough space:
![stats](https://cloud.githubusercontent.com/assets/6088494/24840560/4e94198e-1d6f-11e7-9347-290a5a125f6f.gif)

btw. what happened to @FoxInFlame ? looks like his profile vanished?..

**Comment by Kimod** [comment]
@FoxInFlame My wallpaper changes every minute, I have a folder of 500+ images of anime scenery, so it's not like I care a lot about this wallpaper or like Sao alfheim arc :^)

**Comment by Drutol** [comment]
@Kimod that's the spirit!

I've only 83 in my wallpapers folder and 153 in "nice but not wallpapers" folder :D

On the other hand I've 1,6GB worth of anime music xd (that's something... right?)

**Comment by FoxInFlame** [comment]
@Kimod @Drutol
I've always wanted to do that, but my limited desk space...
I was talking about beautiful, as in scenery. :)

**Comment by Drutol** [comment]
/r/moesacpe

**Comment by FoxInFlame** [comment]
These are all fanarts though, right?
Oh, Drutty, can't you just make a program to auto download latest posts of /r/moescape into its own folder on your harddisk?

**Comment by Drutol** [comment]
If there's no program to download images from reddit I'm going to leave IT studies and go study art...

Better than nothing:
![image](https://cloud.githubusercontent.com/assets/6102530/24877101/5e823e88-1e2e-11e7-82b6-028830c030ff.png)

**Comment by FoxInFlame** [comment]
Yeah! Did you *have* to include /r/ZettaiRyouiki?
I mean....

**Comment by Drutol** [comment]
Yeah.

They have *some* great mobile wallpapers.

.

**Comment by Drutol** [comment]
![gif](https://cloud.githubusercontent.com/assets/6102530/24878290/d1925828-1e32-11e7-9837-43685a69dc9f.gif)

**Comment by ZeroOmar** [comment]
I thing the app should change to mobile view if the width is below a certain point 
like grove music changes to full mobile mode

**Comment by Drutol** [comment]
Woho, welcome back!

Full mobile transform is impossible due to my previous faulty decisions.

**Comment by Guerra24** [comment]
It's kinda fixed so I'm closing this.
