### ISSUE TITLE
Android Colours...

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#116]
I'd like to add a few theme colours to settings... which ones look nice in your opinion?

This is the template if somebody would like to customize it :D

```
  <color name="<Colour>DarkBrushMessageBubbleMine">#7d340e</color>
  <color name="<Colour>DarkBrushMessageBubbleOther">#6a2d0d</color>

  <color name="<Colour>LightBrushMessageBubbleMine">#eab995</color>
  <color name="<Colour>LightBrushMessageBubbleOther">#e4a787</color>

  <color name="<Colour>AccentColour">#ff8c00</color>
  <color name="<Colour>AccentColourDark">#cc7000</color>
  <color name="<Colour>AccentColourLight">#ffaf4d</color>
  <color name="<Colour>OpaqueAccentColour">#7fff8c00</color>
  <color name="<Colour>AccentColourContrast">#831B2A</color> <!-- floating button colour in dark mode, accent dark in light mode -->
```

Where ```<Colour>``` is for example ```Orange``` ```Purple``` etc.

Real [example](https://github.com/Drutol/MALClient/blob/master/MALClient.Android/Resources/values/colors.xml#L65)

**Comment by FoxInFlame** [comment]
I would've loved to do this, but it's just so god damn tedious... Wouldn't it be easier to specify one colour, which can also be customisable (like a colour picker) by the user, and then darken / lighten according to different parts?

**Comment by Drutol** [comment]
Well, I have to have everything staticly defined because this is what android layout system expects, there are probably some workarounds but I don't feel like it's worth the effort :(
It took me 4 minutes fill this in using colours from Windows10, GIMP & Snipping Tool :D

**Comment by FoxInFlame** [comment]
Well, alright. I'm going to sleep now, so I can't do much, but variations of #2e51a2 would be nice. I think that's the MAL theme colour.

**Comment by Drutol** [comment]
Added blue theme

**Comment by FoxInFlame** [comment]
Screenshots?

**Comment by Drutol** [comment]
Let me describe it... it's blue? :D

![image](https://cloud.githubusercontent.com/assets/6102530/24742966/b566569c-1aac-11e7-8768-e5d830ca9cf9.png)

Not my favourite color ^^

**Comment by FoxInFlame** [comment]
The subtitle "Title", is not fitting in. But blue's my favourite colour :)

**Comment by Drutol** [comment]
Yeah, I'm aware of this but I'll tweak this later ^^
Okay, blue for you then :D

**Comment by FoxInFlame** [comment]
Is the floating button colour always orange? I don't seem to find it in the template.

**Comment by Drutol** [comment]
This is ```AccentColourContrast```, I found this button to be little invisible in dark mode so it varies in colour between light and dark theme. It should be blue here, my bad ;d

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/24744006/c6f8a4ec-1ab0-11e7-9986-a5fc906674d3.png)
 And simple picker in settings.
