### ISSUE TITLE
Android ¡Beta!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#118]
# MALClient Android Beta

## App has been published to google play as closed beta!

Welcome to closed beta of MALClient! *...Okay, semi-closed*
> If you want to join just send me your google play mail here: ```malclient[at]poczta.fm```
> Once you've been added follow this link in order to enroll for beta: https://play.google.com/apps/testing/com.drutol.malclient

## Open beta on the horizon!

As bugs are slowly melting we are approaching open beta! I'd like version v0.0.15.0 to be the one but we'll see how it goes. Feature-wise I think I'll be done in v0.0.13.0 (excluding stuff like anime cover saving, forum post starring and such).

Shortly after open beta release, I'll upload UWP build with #64 well-aged bugs resolved and notice about Android version as I guess most people don't have W10M... in order to gain some testers and gather more crashes. Actual "advertisement" on MAL forums and whatnot will be up after actual release.

### How to yell at me? (aka. release your inner tsundere)

The best approach is to create separate issues with list in @Kimod's style. (see #64)

**Comment by FoxInFlame** [comment]
Sent my mail 😄 

_I'm looking forward to this!_

¿Wasn't there a beta test feature on Google Play? I'm not sure because I've never used it, but I think I saw  a few apps in "beta" state.

**Comment by Drutol** [comment]
Yeah, there is and that's why I need your mails. Further down the line we will transition to open beta and full release.

I expect 2 more months at least.

**Comment by Drutol** [comment]
Expect apk tomorrow I did not manage to prepare everything today :(

**Comment by Drutol** [comment]
I'm preparing for release now :)

**Comment by Drutol** [comment]
Wohoho, Google is **much** stricter with certification then Microsoft, damn it...
I've added link to apk for now.

**Comment by Drutol** [comment]
We are live on google play!

**Comment by FoxInFlame** [comment]
Got it! I like the "New Update" dialog. Ahoy it is.


The icon is fixed! Great!


15 mb was quite a size...
![Image](http://i.imgur.com/6Ra8P2x.png)

**Comment by Drutol** [comment]
Is it? I mean it's 15 mb...

Btw it's bound to be heavier due to Mono runtime which is not bundled with android devices :(

**Comment by FoxInFlame** [comment]
I did not understand a single thing in that sentence, but if it's supposed to be this heavy, then it's fine. 😄

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/24839381/87ce63be-1d59-11e7-9c78-616c5c7248cb.png)
(https://developer.xamarin.com/guides/android/advanced_topics/application_package_sizes/)

Android doesn't have .NET stuff in it, because they use Java so app has to bundle missing things and as there are tons of libraries used weight increases.

**Comment by Drutol** [comment]
And so it begins... see #64 "A few bugs"  :D

How app is shaping up in your opinion?

**Comment by Drutol** [comment]
I'll try to release updates weekly. Or sooner depending on amount of time I have on my hands.

**Comment by Drutol** [comment]
#In next update
I've changed the mechanism for loading anime cover images, if image was previously loaded it will show up instantly without place-holders and fade-in. Let me know how it behaves performance-wise. :)

**Comment by FoxInFlame** [comment]
And..... when's the next update coming?

**Comment by Drutol** [comment]
Saturday/Sunday as I said one post higher I'll upload weekly updates.

**Comment by Drutol** [comment]
# New update! (0.0.6.0)

New update should be up on the store shortly!

Changelog:
```
            "Fixes from @Kimod's issue (#64)",
            "Fixes from @FoxInFlame's issue (#121)",
            "Image loading re-invented, not everywhere yet.",
            "Anime/Manga recommendations rework.",
            "Added NotificationsHub page.",
            "Tons of little fixes and such."
```

**Comment by Drutol** [comment]
# In next update (0.0.7.0)

Next update will be focused on forums, it may come earlier than next weekend.

**Comment by Drutol** [comment]
Is app really crashing that badly or crash reporting library has gone nuts?
![image](https://cloud.githubusercontent.com/assets/6102530/25117090/af9f45a8-2410-11e7-8f65-10e877067b30.png)

**Comment by Kimod** [comment]
Yeah, it crashes 24/7, there aren't specific conditions, it just crashes when the app feels like crashing... We are in beta, I thought it was normal ^^

**Comment by Drutol** [comment]
Ugh, it doesn't crash on me and if it crashes it has a reason to do so.

Is your internet connection stable? Any difference on cellular/wifi?

**Comment by Kimod** [comment]
Yup, that is my device and no, I don't think there is any difference between WiFi or cellular

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/25118823/207c751e-2418-11e7-9b15-6a29d710f3e7.png)

Ugh, I'll research on the matter.

**Comment by Drutol** [comment]
@FoxInFlame do you experience excessive amount of crashes too?

**Comment by FoxInFlame** [comment]
I did, last time I checked. Everytime the app was closed, the reason was a crash. 

For the last few days though, I haven't checked, because of the MAL easter egg hunt and all that :)

**Comment by Drutol** [comment]
I got a few hundred reports from @Kimod's phone and there's one more "MOTOROLA MOTO G (4)" with like 4 crashes.

I do have a few ideas so we will so how that turns out...

**Comment by FoxInFlame** [comment]
That.... would be my phone.

**Comment by FoxInFlame** [comment]
How do you manage your crash reports? Are they in a database? Sent by mail? I don't have a crash report system on any of my projects and I would love to try that.

**Comment by Drutol** [comment]
There's service called HockeyApp which handles everything for me, you just throw a key in it and you are done. It's free too :)

**Comment by Drutol** [comment]
I may pump out some update today in order to check how things work because I'm a bit annoyed with these crashes.

**Comment by FoxInFlame** [comment]
Aww, HockeyApp doesn't support Chrome apps... I guess I'll have to make a page on the server to accept reports... :(

I'll be looking forward to your update!

**Comment by Drutol** [comment]
Well, it's primarily for mobile apps and not html/js apps. I don't believe that there's no such tool in *javascript*.

**Comment by Drutol** [comment]
# New update! (0.0.7.0)

New update should be up on the store shortly!

Well, I'm releasing this now because I hope that I fixed some issues with random crashes, forums are working quite a bit more but still WIP :)

Changelog:
```
            "Little improvements on anime details page.",
            "Added \"Go to\" button in profile page",
            "Hopefully reduced amount of various crashes.",
            "Great cleanup in Forums... still work in progres though!"
```

**Comment by Drutol** [comment]
Fingers crossed ;d

![image](https://cloud.githubusercontent.com/assets/6102530/25145785/34776b78-2472-11e7-9199-6ee68da171bd.png)

**Comment by Drutol** [comment]
Aaand... Is it any better?

**Comment by Kimod** [comment]
I guess it is fixed and if not, it's at least much better

**Comment by Drutol** [comment]
Yay!

**Comment by Drutol** [comment]
# New update! (0.0.8.0)

Small update with mostly fixes from #64 as I caught a cold :(

**Comment by Drutol** [comment]
# New update! (0.0.9.0)

This is big one, and will go live later today!

In terms of functionality we are missing very little now, with the biggest thing being creating new forum topic, and little fries like setting rewatching count, selecting random anime, missing settings pages, review pop-ups, voluntary ads... nevermind...

```
            "Fixes from @FoxInFlame's & @Kimod's issues.",
            "Added stats page.",
            "Added wallpapers page",
            "Profile page little reorganisation.",
            "More dialogs and clickable stuff in forums",
            "Scrolling on forums should be more fluid, not perfect though.",
            "Pinned topics are now working",
            "WebViews in Forums&Articles/News will now redirect into app if possible.",
            "Notification hub fixes",
            "App should now launch on Android 5.0",
            "Ascending/Descending sorting",
            "Rewathing support, partial because I don't know where can I squeeze more controls...",
```

**Comment by Drutol** [comment]
# New update! (0.0.10.0)

Hmm, this update theme is... open beta. I'm adding miscellaneous stuff like about page, ads, donations etc.  I'd want to launch open beta in a 1 month's time.

```
            "Added ads... yay...",
            "Added dontations... yay...",
            "Added about page...",
            "Redesigned login page.",
            "Added popup which encourages to review app on the store.",
            "Tweaked hamburger a bit.",
            "Wallpapers page items are now a bit smarter about their sizing.",
            "Tweaked settings pages.",
```

**Comment by ZeroOmar** [comment]
man I wish I had an Android phone 😢  
I'm still using my poor Lumia 630

**Comment by Drutol** [comment]
It's stuck on 8.1, right?

**Comment by ZeroOmar** [comment]
sadly 😭 
I was on the inside preview back when I was using your app on my phone but I rolled back due to performance issues with the 512 mb ram and the phone was removed from the inside program so I can update it to 10 again.
at least I still use the UWP version on my PC 😄

**Comment by Drutol** [comment]
# New update! (0.0.11.0)           

An update . 

```
            "Fixes from @Kimod's #64 issue, it's neverending story....",
            "New message icons.",
            "Calendar works better.",
            "Hopefully got rid off crashes on app restore.",
```

**Comment by Drutol** [comment]
# New update! (0.0.12.0)           

Bugfix update more or less, pretty beefy bugfix-wise.

```
            "Fixes from #64 #121 and #123 issues.",
            "Added calendar countdown.",
            "Hamburger footer tweaks.",
            "More keyboard fixes.",
            "Login issues fixes.",
```

**Comment by Drutol** [comment]
# New update! (0.0.13.0)           

Bugfixes bugfixes bugfixes, final bigger page missing added. Are we feature complete now? Little stuff aside I think we are done.

```
"Fixes from #64. Yup again... Just go and see the amount of bugs contained there...",
"Added new topic page.",
"Added message/see other posts buttons in topic itmes.",
"Added option to hide manga section in hamburger.",
"Fixed characters data scrapping.",
"Other big change is that Xamarin Android 7.3 is bringing new Garbage Collector, which is currently marked as 'Experimental' and I've enabled it in this build in order to well... experiment? Let me know whether you feel any difference, in theory it should work faster."
```

**Comment by FoxInFlame** [comment]
I'm sorry for the lack of feedback I'm giving the past few days.

I usually tend to not concentrate on things long, so I switch focus from programming/computers to anime/youtube/procrastination every month or so. It's an automatic process, I can't stop it.

Right now, I'm just watching a lot of anime that I can find. I'll come by in a few weeks :l

**Comment by Drutol** [comment]
Sure that's fine, I'm too thinking about taking a short break after Android release. Gotta play some Nier somewhen :D

**Comment by ZeroOmar** [comment]
I just downloaded Nier too 😄

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/26036351/4b3e9e16-38dc-11e7-8956-dd60d083f38e.png)

Hmm, gotta put there something but I'm still without an idea... Ideas? ( #119 xd )

Else I'll put there dimmed/blurred screenshot of app

**Comment by ZeroOmar** [comment]
maybe an anime character. your waifu for example 😄😄

**Comment by Drutol** [comment]
This is a thing btw:
![image](https://cloud.githubusercontent.com/assets/6102530/26036525/7f3f2d04-38df-11e7-83d1-38b0505fba25.png)
Catchy ain't it?

**Comment by ZeroOmar** [comment]
![image](https://cloud.githubusercontent.com/assets/18592104/26036542/d993ee70-38df-11e7-9883-f8f77c6d4e23.png)

**Comment by Drutol** [comment]
Soo umm weel... how do you feel about this app? Is it ready for open beta (after a few more #64 fixes)? Does it compete well with existing apps? I feel like it's usable and works good enough ^^

**Comment by Drutol** [comment]
I'm aiming for open beta either tomorrow or on Sunday depending on how things go. This is the best time to play your trump card bugs ^^

I'll release "openbeta build" in closed ring before going to open one.

**Comment by Drutol** [comment]
# New update! (0.0.14.0)           

That's hopefully the last one, store listing has been updated with screenshots.

```
 "A few bugfixes from #64",
            "Compact view usable?",
            "Added used memory watching, app should no longer close for no apparent reason if this reason is lack of memory... xd. Images will start to load to memory again from storage.",
            "I want this to be last closed beta update and release this to open beta this weekend, if there's something big that I'm not aware of this is the time to speak!"
```

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/26275298/736c2446-3d5d-11e7-8bae-0efbabc75b21.png)

Some furious testing right there xd
