### ISSUE TITLE
Houston! We have a problem...

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#119]
Google certification says that this hummingbird in logo must go... (if you don't know, hummingbird was supported when it wast still live and I just threw it in logo)... so yeah... ideas for logo?

**Comment by FoxInFlame** [comment]
Well..... Can't you just have MAL without the hummingbird?

**Comment by Drutol** [comment]
Yeah but then it's plain MAL logo then, I'll do this if there's no other idea.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/24837970/d805ecf4-1d3f-11e7-8ab3-9880aa1f0c28.png)

Anyone has fine text to put there or should I go with his one? :D

**Comment by FoxInFlame** [comment]
Well... It is catchy, but it's has like nothing to do with MALclient itself, lol.

I think the MAL text could be reduced in size a little bit on the final icon. Seems a little too big.

**Comment by Drutol** [comment]
It passed certification, they don't mind MAL logo but hummingbird seems to be a problem. w/e

We have still at least 2 months to come up with something :D
For now let's make the app work.
