### ISSUE TITLE
Window resize crash

### ISSUE THREAD

**Issue by Guerra24** [Drutol/MALClient#120]
If you maximize or unmaximize in the anime details it will crash. Only occurs in those who have never opened. There is a probability of data corruption that prevents the details to be opened in the future and looks that only happens in the "Plan to watch".
[Video](https://puu.sh/veid4/bdc42b75dc.mp4)

**Comment by Drutol** [comment]
Very strange and I'm unable to reproduce this, I've even visited your list. Hmm I can send you debug version so we can see what crashes exactly.

**Comment by Guerra24** [comment]
Yes.

**Comment by Drutol** [comment]
https://1drv.ms/u/s!Am1xQK-HVf_IlK4w6TZOUc_-n1qkAA

Try crashing on this one.

**Comment by Guerra24** [comment]
Done, the same issue.

**Comment by Drutol** [comment]
Did you start the app again after crashing?

**Comment by Guerra24** [comment]
Yes.

**Comment by Guerra24** [comment]
Resizing causes the same issue. [Vid](https://puu.sh/vgqAF/39bb1e86b8.mp4)

**Comment by Drutol** [comment]
Damn for some reason I'm not getting reports about these crashes, I'll send one more version this evening...

**Comment by Guerra24** [comment]
This issue is caused by the UI when changing from 3 columns to 2 on a big list. [Vid](https://puu.sh/vp5u5/e5f404e9f9.mp4)
