### ISSUE TITLE
Stuff I noticed (There's a lot) 🦊

### ISSUE THREAD

**Issue by FoxInFlame** [Drutol/MALClient#121]
New report will be added as a reply to this issue. Please do not close this issue.
A bug report might contain replies to previous reports.
I'm not really in the place to say all this (caus all I've done is like scrape small pages and create a tiny Chrome Extension) but I like reporting bugs. :)

Icons: 
- 🐞 Bug - It doesn't do what it's supposed to do, required to fix (feature issues, crashes)
- 🐝 Bee - I want it to look better, not required to fix (ui, animation, etc)
- 🍄 Mushroom - Feature Request/Suggestion
- 💙 Blue Heart - I like it! General Feedback

Drutol, you are free to edit to reply.

2017-04-09 ~09:00 GMT [Android]
---
_Report No. 1_
http://imgur.com/a/m3DYZ

Putting list here so you can edit&reply if you want :)

* 🐝 The vertical alignment of the 'status' text in the Recommendation page bugs me. [Image](http://i.imgur.com/w1rTmLW.png).
  * ✔️ Fixed
* 💙 'Would you like to send a report so *we* can fix it'? [Image](http://i.imgur.com/sKEk9GK.png).
  * That's just a popup from external library. There's no 'we' xd
* 🐞 Profile stats are still not loading. [Image](http://i.imgur.com/c8pFwfx.png)
  * ✔️ Added
* 🍄 Can't you morph the hamburger icon into a back arrow icon on an anime detail page? Most Android apps do that. [Image](http://i.imgur.com/C9363Eg.png).
  * 🌠  I'm afraid that this is impossible with current flow of an app and if I did transform hamburger into back arrow what's the merit of it? It'd just limit functionality and in order to navigate somewhere else user would have to tap it twice. That's not iOS :D
* 🐝 What's the point of the [login page](http://i.imgur.com/BlQK1X5.png)? Since the input boxes are empty, I might mistake it for that I'm logged out. The Logout button should also be more visible.
  * Login page was untouched too (see "Beta" issue). The point of this page is to allow for relog and logout but I probably should indicate it in some way.
* 🐝 The icon for Anime list and Manga list on the sidebar should be identical. [Image](http://i.imgur.com/JY9ZUBI.png).
  * ✔️ Fixed
* 🍄 Is there a way to search for users?
  * ✔️ Added
* 🐝 Notifications seem to be bundling into one, and you can't see everything in the bundle.
  * (Notifications) Bugged as in details page loads forever?
    * 🦊: As in, the notifications. Notifications. Like, push notifications. 
      * Ah, android 7.0 right? I remember that it worked there differently I'll investigate.
* 🐞 Tapping Friends Feed in the settings and in the hamburger menu causes a crash
  * ✔️  Fixed

**Comment by Drutol** [comment]
Added list with replies.

**Comment by FoxInFlame** [comment]
2017-04-09 19:45 GMT [Android]
---
I know this is a lot. Bear with me, one by one. :)

* Friend request notifications only have Mark as Read, and not Accept/Decline (would probably apply to all notifications that have an action attached)
* I love the quick loading after the initial launch.
* While it shows native notifications on MAL notifications, is there no way to view it as a list inside the app?
* There seems to be a lack of loaders, as shown in [this](http://i.imgur.com/2bkhmJL.gif) crappy gif. Why is there no easy way to share screens in nice resolutions?
* Your Name is showing dubbed (in Swedish) and subbed in Sweden, so ima go watch it on Thursday (when I've literally rewatched it 15 times on KissAnime). :)
* Also experienced a random crash the moment I tapped on the app icon (which I sent a feedback report on).
* I don't know why but I just experienced a blank page after backing from an anime page for a full 15 seconds. [This](http://i.imgur.com/xEPYvyE.png)
* Opening Anime Recommendations on accident and immediately tapping the hamburger menu caused a freeze for roughly 10 seconds, probably due to the insane scrapping it's doing. Methods are cached, right?
* The search in the sidebar is renamed at last! Wooo!
* You have a full list of studios in your search. Do you scrape that, or is that hard-coded in?
* I don't like how while the score and status setter popup from the bottom, the watched episode setter pops down from the top. 
* There seems to be a lot of unneccessary crashes here and there. Happened sometimes when I tapped Manga list, and when I tapped sections of the Settings page. Also happened for no reason on the anime search page.
* The signin screen I was talking about, back-buttoning out of that goes back to the Android home screen, and not the settings page. 
* You do say that it's impossible to make a back button with the current flow of the app. But, Android-wise, app pages are apparently supposed to have hierarchy, and the top left button shows the current hierarchy. [This part](https://material.io/guidelines/patterns/navigation.html#navigation-up-back-buttons) of the Material design guidelines explains the difference between an Up button and Back arrow. Well, if you really can't, and doing so might cause an overall recode, then, well, alright.
* You really need to finish the About page, man. I can't figure out the app version.
* The text in the search box on my list is black. Black on blue is a bad colour combination.
* Back-buttoning from a search result (anime page) should go back to the anime search, not the list. 
* I again, really think keeping the images on the screen would be a lot better. It makes things go smoother, and increases user-whatever. I don't know, it just feels better.
* The top message on a private message thread (looking at one between you and me) doesn't have any margin between the app bar. That's a comfortability issue that is required to be solved. I can't sleep.
* BBcodes on messages doesn't seem to be working, I can't see my underlined size=300 text.
* On the forums, there is a Search button with white text on gray background (on the light theme). Same problem applies to "New Reply" and "Toggle watching" buttons.
* Would be cool if you could somehow sync the calendar into Google Calendar as an import or something. 
* And the loader is stuck at what looks like 10%, "Building calendar, please wait...". Oh! It moved to like 15% after 30 seconds. Can't this go any faster? It'll probably take around 5 minutes to finish (and I mean this literally). No, I give up on the wait. Moving on.
* Does it have to download data every time I go to Top Anime? Back-buttoning out of an anime page into the Top Anime page also (for an instant) shows Downloading Data. 
* MALclient stopped responding as I loaded a forum topic. For some reason. Never happened again.
* The bug icon next to "Watched Topics" on the watched topics page is not vertically aligned with the text.
* Seems like you're using the same image-loading library for forums (posts disappear when they go off-screen). I dunno, as I said before, it does feel unnatural.
* Shadows on images on News pages and Forum topics are too big.
* Would be great if you could open their profile pages, from the direct message page. Like a normal chat app.

That's probably it for now. I need sleep.

**Comment by Guerra24** [comment]
## Stuff I also noticed [UWP]
- 🐞 [Typo](https://puu.sh/vgp0A/86da3e55e7.png) in "sort values".
- 🐝 [Highlight](https://puu.sh/vgqeM/7026474e01.gif) is way too transparent.

**Comment by FoxInFlame** [comment]
2017-04-11 08:58 GMT [Android]
---

The icon for notifications (the small one that appears on the status bar) still has the Hummingbird on it.

**Comment by FoxInFlame** [comment]
2017-04-11 08:58 GMT [Android]
---

- 🐞 Aren't MAL notification notifications stored? I sometimes get the same notifications that I got yesterday, just because I haven't read it. (I keep all my notifications unread). Is this an intended behaviour?

**Comment by Drutol** [comment]
I'm slowly finishing #64 once I'm done I'm coming over here!

**Comment by FoxInFlame** [comment]
2017-04-15 02:52 GMT [Android 0.0.6.0]
---

- 🐞 Tapping on device notifications should bring user to the notification hub or the related page, not just the main page of the app.
- 🐞 Accepting and Denying friend requests, still
- 🐞 Tapping on notifications in the hub should bring user to the related page.
- 🐝 The mark as read button is not horizontally aligned together (maybe affected by content)?
- 💙 Love the shadow/roundness of the previously mentioned "mark as read" button
- 💙 I just wasted 6 hours figuring out the MAL Easter egg hunt with a couple of people on Discord. The satisfaction I feel right now was worth it, but don't try alone, you need about 3 more people to efficiently solve it.

**Comment by FoxInFlame** [comment]
2017-04-19 05:45 GMT [Android 0.0.7.0]
---

- 🐞 Why did it have to ask for connectivity permissions on installation? What's it used for?

- 💙 You spelt 'progress' with one s in the changelog 

- 🐞 Your Lie in April has this weird foggy effect, only on my list page. [Picture](http://i.imgur.com/BIfmnlf.png).

- 🐝 Vertical alignment of the entry medium on the Recent Updates page. [Picture](http://i.imgur.com/fILO0x0.png).

- 🐞 Still empty stats. [Picture](http://i.imgur.com/Zg5Ggqa.png).

- 🐞 In the recommendations page, tapping one anime cover brought me to the other one, and vise versa. In this [picture](http://i.imgur.com/otvmUxn.png), tapping on Mahouka brought me to Rokudenashi.

- 🍄 More offline support. If I have no internet connection, I don't want to wait for a loader that's never going to load (e.g forums). I want to see something that tells me that I don't have an interview connection.

- 🐝 Opening messages in offline brings up the "Something went wrong" popup instead of a similar internet connection popup.

**Comment by FoxInFlame** [comment]
2017-04-20 07:40 GMT [Android 0.0.7.0]
---

- 🐞 The height for the blue line next to the anime on the search page is different.
[Picture](http://i.imgur.com/KO0Q7lG.png)

- 🐞 Still has weird image loading in the character and recommendation pages. [Picture 1](http://i.imgur.com/UBV5VD4.png), [Picture 2](http://i.imgur.com/UWripQP.png), [Picture 3](http://i.imgur.com/A9pZQei.png).

- 🐝 Vertical alignment of the entry medium on the Recent Updates page. [Picture](http://i.imgur.com/fILO0x0.png).

- 🐞 Still empty stats. [Picture](http://i.imgur.com/Zg5Ggqa.png).

- 🐞 In the recommendations page, tapping one anime cover brought me to the other one, and vise versa. In this [picture](http://i.imgur.com/otvmUxn.png), tapping on Mahouka brought me to Rokudenashi.

- 🍄 More offline support. If I have no internet connection, I don't want to wait for a loader that's never going to load (e.g forums). I want to see something that tells me that I don't have an internet connection.

- 🐝 Opening private messages in offline brings up the "Something went wrong" popup instead of a similar internet connection popup.

- 🍄 Opening the app without an internet connection brings up the same "Something went wrong probably html" dialog instead of a cached version of the list.

**Comment by Drutol** [comment]
Are you sure about recommendations pictures using old loading mechanism?

**Comment by FoxInFlame** [comment]
Um, does that image in Screenshot 2 look like a cute moe girl with purple hair?

**Comment by Drutol** [comment]
Well, that's strange...  maybe one of these rare bugs ;d

**Comment by FoxInFlame** [comment]
2017-04-20 07:38 GMT [Android 0.0.7.0]
---

- 🐞 Oh no, I just put a comma in my tag by mistake! Wait, [it works](http://i.imgur.com/OaEACSg.png)!? Nice, but I want to edit my tag and capitalise that letter!

**Comment by Drutol** [comment]
Well, it works now but it'll split itself on next run probably. Should I split input with commas to different multiple tags?

**Comment by FoxInFlame** [comment]
Yeah, it split on the next run. Splitting in input would be wise.

2017-04-20 13:16 GMT [Android 0.0.7.0]
---

Forums :)
- 🐞 There are often incredibly long blank spaces after the post itself, most of the times spanning well over one screen. [Picture](http://i.imgur.com/RI5wFsy.png).
- 🐞 Some titles do not load. In the picture, the first >> should say "Little Red Riding Hood NSFW". [Picture](http://i.imgur.com/4jjWzpC.png). Don't ask me why I was reading that.
- 🐝 The length of the scrollbar changes while scrolling through a thread.
- 🐞 When there's an insanely long post (like LRRH-NSFW), scrolling back onto that post from a post beneath makes the screen jump to the top. [Video (password:malclient)](https://vimeo.com/214020293).
- 💙 Why the god damn hell are there no easy methods to share a screencast from Android? It has literally taken me an hour and 6 minutes trying to do that. I recorded it alright, I got the file. And then I had to upload the video to Google Photos, wait for it to process, download it on my computer, go to various gif sites to find out that they don't support files over 20 seconds, try to find simple video share sites (like puu.sh or imgur) with no avail, and finally had to create a Vimeo account to upload there. Are there easier solutions?

**Comment by Drutol** [comment]
The thing with forums is that posts' content is rendered in web view and web view content height has to be extracted using my sick javascript skills and finally applied to web view in native layout. This is rough on android, it's a little less rough on UWP version but there's still chance of this happening. This is pure *voodoo*.

Posts on the index page are not loading because there was change in html yesterday.

I could add an option to render it as a text without quotes and all this stuff.

**Comment by Drutol** [comment]
@FoxInFlame did you get any pop-ups asking whether app can use internal storage? Is data being cached properly (one loaded details load instantly)? I got some news that android 7.0 has some wicked policy going on.

**Comment by FoxInFlame** [comment]
It doesn't look like I did. (I know what caching is, I'm a fellow developer :])

Maybe that explains the reason my list doesn't load offline, or why images keep having flashes.

But wait, my anime list doesn't seem to have image problems, so maybe caching *is* working...

**Comment by Drutol** [comment]
By
>one loaded details load instantly
I meant that's the easiest way to check whether it works.

Do you get loaders on once visited anime details page?

**Comment by FoxInFlame** [comment]
No. So, maybe, caching is working. That means I pressed Ok on a popup that I don't remember...

**Comment by Drutol** [comment]
Could you try reinstall? I'm curious about that ^^

**Comment by FoxInFlame** [comment]
I'll do the reinstall when I get back home. Will edit later.

**Comment by FoxInFlame** [comment]
2017-04-21 08:15 GMT [Android 0.0.7.0]
---

- 🐝 Seems like the image loading library you made is still not working properly. Since the reinstallation I did yesterday, my list keeps having the wrong picture. When I scroll, I first see a loader. Then that disappears, and I'm left with a gray box for about 4 seconds. After that, a false image loads, and about 5 seconds after *that*, the real image loads. It still does cache though, so it only happens the first time an image is loaded.
- 🐝 Again, all the notifications keep coming over and over. If I swiped it away once, I don't want it to appear every hour or so. I have a 16 unread notifications and 2 unread messages and they both have already been read through my email. I want to see how far this can go.
- 🐞 Also, empty friend requests seem to be present in the notifications and in the Hub. They're probably the ones which are already declined/accepted.

**Comment by Drutol** [comment]
I didn't do anything with notifications yet.

**Comment by Drutol** [comment]
@FoxInFlame how are notifications looking in v0.0.8.0?

**Comment by FoxInFlame** [comment]
2017-04-25 21:22 UTC [Android 0.0.8.0]
---

- 🐝 Seems like the place where "read more" is cuts the reviews into separate paragraphs.... [Image](http://i.imgur.com/U9UNAm4.png).
- 🐞 YouTube videos are not working! Probably because JS is not present, and you only have the scrapped HTML. Is there no way to embed JS into WebView? [Image](http://i.imgur.com/t2z9orr.png).
- 🍄 Opening MAL links with MALClient should be a thing. I was browsing a news article, tapped on an anime title, and it opened in the browser instead of the app. I mean, a lot of apps do this, and they're probably not official. I don't think you need to put anything on the host site for it to open in an external app. [Image of a link to an anime title](http://i.imgur.com/XXZXPMz.png).
- 🐝 After sending a new message (like, a completely new message), the text stays. [Image](http://i.imgur.com/3BzaOlL.png).
- 🐞 Going back from ↑ makes the messages unopenable. Opening the "Sent Messages" screen also does this. [Image](http://i.imgur.com/27blTul.png).
- 🐝 Going to Sent Messages, then creating a new message, then back button makes the title "Messages" instead of "Sent Messages".
- 🐝 Input text still stays on different messages. Maybe, if possible, remember for each person? [Image](http://i.imgur.com/A72gnh1.png).
- 🐝 Notifications are still bugging me. They keep flowing in all at one go. What did you change, exactly? [Image](http://i.imgur.com/GjxYOQn.png).

**Comment by Drutol** [comment]
Notifications shouldn't duplicate, that's what I've been trying to address.

**Comment by FoxInFlame** [comment]
Ah. That should be fine. Fixed. :)

**Comment by FoxInFlame** [comment]
By the way, did you fix [this](http://i.imgur.com/qxLbkyH.png)? There's a text that says 'edit', probably an scrapping error.

**Comment by Drutol** [comment]
Wow, how did I missed it? 
By the way I've fixed auto sorting order chooser because it wasn't working on android too ^^

**Comment by FoxInFlame** [comment]
2017-04-29 16:50 UTC [Android 0.0.8.0]
---

- 🐞 I just ran across an issue where voice actors were "Unknown". My WiFi was a little unstable, so that could be the cause. [Image](http://i.imgur.com/qtuxruk.png).
- 🐝 I don't think "Accept" is the right term here in the dialogue. [Image](http://i.imgur.com/0ONChMV.png).
- 🐝 Keyboard persists even after closing the dialogue by tapping outside of it. [Image](http://i.imgur.com/drDSjRM.png).

**Comment by FoxInFlame** [comment]
2017-04-30 14:14 UTC [Android 0.0.9.0]
---
_Report No. 13_
- Sometimes the anime doesn't add to the list, no matter how many times I tap on it. 
- Also, the sorting is reverted to the default everytime the page is loaded.

Both are shown in the [video](https://goo.gl/photos/jBQQXuumXxA6hSEu7). By the way, this album will mst likely contain videos for this issue later on.

**Comment by Drutol** [comment]
I'm unable to reproduce this issue with adding anime to list. The only possible scenario is that this movie was already added to your list and local one got desynchronized somehow.

As for reverting to default sorting, this is intended behaviour navigating back keeps order as it was but every navigation to "fresh" list page results in it setting sorting as per settings.

**Comment by FoxInFlame** [comment]
God, I just viewed my profile About Me on the UWP version, and it looked horrible ;)
All the whitespace, black text on gray background, block images instead of inline, ugh.

2017-05-01 23:19 UTC [UWP 5.3.14.0]
---

- 🐝 The same issue as Android, where if you go into the Account setting, you can't go back to the main setting menu without moving the cursor all the way to the left to click on Settings again. Back button should be visible at the top left corner of the panel.

**Comment by Drutol** [comment]
Reviews are fixed, since android 0.0.9.0, it's in shared logic. I just need to release update somewhen.

**Comment by FoxInFlame** [comment]
Mmhmkay.

2017-05-06 07:10 UTC [Android 0.0.11.0]
---
*Report No. 15*
- 🐞 Promotional Videos don't load [Picture](http://i.imgur.com/SlxqIzW.png).
- 🐞 I like how notifications auto resizes to the content now, but the mark as read is now too small to be visible anymore! [Picture](http://i.imgur.com/PNsutWj.png).
- 🐝 "Helpful" text is included in the review and not as a button. [Picture](http://i.imgur.com/D9QG2Cg.png).
- 🐝 Favourite stars should be inverted, I think. Show the line through when not in favourite, and a filled one when it is a favourite. [Picture](http://i.imgur.com/IIr7GqG.png).
- 🐞 I thought she was the Main character in Choujigen Game? Where's the role name? [Picture](http://i.imgur.com/Z1z4iRd.png).

**Comment by FoxInFlame** [comment]
Just read this, and seemed interesting. If this gets implemented, wouldn't developing for Android from UWP be easier?

https://www.theverge.com/platform/amp/2017/5/11/15621428/microsoft-cross-device-ios-android-apps

**Comment by Drutol** [comment]
Nope, these are just new features that glue cross platform apps. There's a framework that allows you to develop UI on all 3 platforms simultaneously (Xamarin Forms) but it has long way to go.

Build17 stuff is exciting nevertheless. Especially this fluent design looks nifty.

**Comment by FoxInFlame** [comment]
2017-05-21 08:20 UTC [Android 0.0.15.0]
---
*Report No. 16*
- 🐞 Ad duration isn't saved. I want to help you get money as much as I can! [Image](http://i.imgur.com/qKoyPN2.png).
- 🐝 Scroll position isn't saved for News articles. Bugs me, a lot, especially when you tapped on an article way at the bottom. [Image](http://i.imgur.com/yysZm5z.png).
- 🐞 As mentioned before, when you add a new anime after viewing one that's in your list, the tags remain. You know how much I use my tags, it's really annoying. [Image](http://i.imgur.com/coDe9dn.png).
- 🐝 What's that line under Pinned Posts? [Image](http://i.imgur.com/RHDWiOm.png).
- 🐞 Scraping error still present? The same error was found in 0.0.13.0, and the update didn't fix it. [Image](http://i.imgur.com/yKvRTnT.png). Tapping on it brought me to [this](http://i.imgur.com/hNTOzKh.png).
- 🐝 The buttons sould be switched, "I'm sure" on the right and "Cancel" on the left. [Image](http://i.imgur.com/sB0IrsO.png9).
- 🐞 Friends Feeds show a spinner, then shows a blank page. [Image](http://i.imgur.com/K8vvl6c.png).
- 🍄 I want to delete some histories! I sometimes play around with code and find myself updating the episode count and reverting it, removing from the phone will be nice. [Image](http://i.imgur.com/4oxMTGf.png).
- 💙 I wasn't really satisfied with Koe no Katachi's ending but it was a good movie nonetheless!

**Comment by FoxInFlame** [comment]
2017-06-19 21:54 UTC [Android 1.0.1.1]
---
*Report No. 17*
- 🐞 Upon deselecting "Rewatching", the status still says Rewatching, and not Completed. [Image after unselecting Rewatching](https://i.imgur.com/Cx2FmrQ.png)
- 🍄 Would be great if it auto-changed the status to Completed upon finishing a rewatch (also remove the rewatching status).
- 🍄 Would be great if it auto-added one to the "rewatched times" upon finishing a rewatch (episode count = max && rewatching = true)
- ^ the two suggestion above can maybe be added as an optional checkbox in the General section (together with auto-updating dates)
- 🍄 The updates went from like 0.0.17.X to 1.0.0.0. What happened to 0.X.X.X? I've heard of [Semantic Versioning](http://semver.org), maybe try that?

**Comment by Drutol** [comment]
My versioning goes like this:

(hey, I've rewritten majority of an app).(oh, new big feature).(random minor things).(I've messed up and this is a crashfix)

**Comment by FoxInFlame** [comment]
2017-06-27 14:53 UTC [Android 1.0.3.1]
---
*Report No. 18*
- 🐞 Seems like filtering is not working for the images? Do I have to reload something? [Image](https://i.imgur.com/3hHc52v.png).
- 🐞 Why does "Read Volumes" counts appear only 9 at a time? I have to tap on the last one to show 9 more. [Image](https://i.imgur.com/6Z73piT.png).
- 🐝 Coming from a forum link (protocol handling), the nav bar has "Anime List" selected instead of Forums. [Image](https://i.imgur.com/2XtYbke.png). Probably applies to all other protocol handlings.
- 🐝 I have anime covers set to a smaller size. It's usually 3 columns, except here in favourites. [Image](https://i.imgur.com/EZVf5tY.png).
- 🐞 While tapping on the Topic Name in an email gives me an option to open it in MALClient, tapping on the "View in MyAnimeList" doesn't. Only browser. [Image](https://i.imgur.com/mwdk5js.png). Same applies to private message notification emails (username can be opened but "View in MAL" can't)
- 💙 Why don't you join us on the Discord chat for The nulls? There are quite a number of Android developers who you can share thoughts and get help from when needed, as well as giving out help.
