### ISSUE TITLE
My little bug list, updated to Andoid 0.0.11.0

### ISSUE THREAD

**Issue by luzankia** [Drutol/MALClient#123]
Hi,
As an old supporter of the W10 version, I will try my best to help you bring it to Android.

For now, I'm working on the login/logout part.
Bug part :
* after a failed log-in attempt with a wrong password (or without any pw), you can't login unless you stop MALclient and relaunch it, even with the right password. 
   * ✔️ Fixed
* In Settings/Account, when you log out and stay on this screen, you can sign back without password or even with a wrong password.
   * ✔️ Fixed

UI part :

* the "SIGN IN" button move to the left after a click on it, then come back at the center after a couple of seconds. It's unusual.
   * ✔️ After redesign it won't move
* After a click on the "SIGN IN" button, the password's "*" are deleted, I think they should stay visible until logged in and only sweeped on the fail.
   * 🌠 Hmm in my opinion it should disappear always, password gets consumed and it's not available later. What would you like to do with this ⭐️s?

Ho, MalClient just crashed on updating the volume count of a manga series, it did update the count before crashing. A bug report was sent.

**Comment by Drutol** [comment]
Hello!
Login experience is the same as it was in December,  I'll play with it more before open beta. ^^
Crash report received!

**Comment by luzankia** [comment]
I did read some post before but not enough...

When you click two time on the same number to set chapters/episode/volume, the app crash. https://imgur.com/a/XyDOb
