### ISSUE TITLE
This is ugly... ideas?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#124]
I don't like this and I'm out of ideas... help?

![image](https://cloud.githubusercontent.com/assets/6102530/25664361/af898ae0-301a-11e7-88cb-18600970a133.png)

**Comment by FoxInFlame** [comment]
How is it ugly? Is it not the same as UWP?

**Comment by Drutol** [comment]
Nah, it just looks sketchy to me. Maybe it's just me?

**Comment by FoxInFlame** [comment]
I feel nothing wrong with it, but maybe that's just me getting used to it.

**Comment by Drutol** [comment]
How about this?

![image](https://cloud.githubusercontent.com/assets/6102530/25770734/e93bb16c-323d-11e7-8665-707d0c353a35.png)

**Comment by FoxInFlame** [comment]
I think the shadows on the blue buttons are a little too heavy...  But moving the like button down is a good idea.

**Comment by luzankia** [comment]
I think I'm used too to the tree icons next to profil.
The new icons are great but something bug me when I see the "support heart" next to the settings.

**Comment by Drutol** [comment]
I wanted this heart to go through the border of hamburger like this:
![image](https://cloud.githubusercontent.com/assets/6102530/25772912/d20083d8-3274-11e7-9e03-13a5cf303cba.png)

 But apparently it's pretty hard to do so.

I'll push this for v0.0.12.0 and we'll see how it looks. ^^

**Comment by FoxInFlame** [comment]
Doesn't Android support any way for elements to go out of Parent bounds?

**Comment by Drutol** [comment]
It is possible but because hamburger is from external library that wraps another library such manipulations are pretty hacky and I don't feel like it's worth the time.
