### ISSUE TITLE
Too soon? New UWP Design... Somewhen?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#126]
I've been playing with new toys from MSFT and this is what I got.

![image](https://cloud.githubusercontent.com/assets/6102530/25904753/734c50a4-35a0-11e7-992c-f8cac0ed9eef.png)

Thoughts? I won't be pushing "NEON" version to the store anytime soon mainly due to amount of changes required in whole app. (+ Android) And when I'll get to it I'll want to make UI cleanup and lifting.

If you are unfamiliar with new MSFT design, this background is blurred "whatever is under the window" in case of this screenshot it was wallpaper

![image](https://cloud.githubusercontent.com/assets/6102530/25904957/07d0c1d8-35a1-11e7-88f4-85e872d9088c.png)

**Comment by ZeroOmar** [comment]
yeah the new neon stuff looks good 😉 
also the bottom bar need to go, there is plenty of space up there next to the search icon so it won't overlap with the hamburger menu and save space on low resolution displays

**Comment by Drutol** [comment]
Wohoo! がんばって！

Yeah some redesign will take place on neon, we can start gathering things now ^^

**Comment by FoxInFlame** [comment]
Seems nice.
I'm not familiar with Microsoft design guidelines, but that looks similar to the Win 10 Mail app. A bit. Maybe not. 

While wallpapers seem good, wouldn't it be weird to see other windows half-transparent? Can you screenshot a state where it's on top of other windows?

**Comment by Drutol** [comment]
Check this out:
https://www.youtube.com/watch?v=vcBGj4R7Fo0

They have just announced this.

Well it looks strange on fully white backgrounds for example but this is the matter of applying modifiers to this blurry thing.

**Comment by FoxInFlame** [comment]
Man, that is exciting. Big companies announcing their own Design guidelines for consistent design. Material Design and Fluent Design. I personally feel good following guidelines to the last character, but you might be different. Good luck nonetheless!

**Comment by Drutol** [comment]
I'll probably do design update together with **Fall** Creators Update, right now most APIs are here but using them is cumbersome and I'll wait for streamlined version. Next major windows update is going to make these things much easier.
