### ISSUE TITLE
Moved discussion from MAL comments ^^

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#127]
Continued from: https://myanimelist.net/clubs.php?cid=72829

>- News (Renamed 'Articles & News')
>- Recommendations
>- Calendar
>
> Anime Header
>- Seasonal Anime
>- Top Anime
>- Anime List
>
> Manga Header
>- Top Manga
>- Manga List
>
> Other
>- dontrememberwhatitwas

But the "Anime list" is the most important here isn't it? And if I added "Anime" header, "Calendar Recom Search" section would have to get header too for the sake of consistency. More space + header name "Others" "Even different others" xd

> By the way, I have a WP8. Any chances your WP app might support WP8?

Impossible. You can use desktop version if you have W10 though ^^

**Comment by irfan-dahir** [comment]
Fair enough. What about categorizing them by their intent?
**App Related Stuff**
//Seasonal anime, search, calendar, etc
**Anime Related Stuff**
**Manga Related Stuff**
**Community**
//forum, friends, etc
**Misc*
//pixiv stuff


> Impossible.
Aw. 😢
