### ISSUE TITLE
Android app crashes if you mash manga list and top manga options at the same time

### ISSUE THREAD

**Issue by Accelyte** [Drutol/MALClient#128]
Was switching between the two a bit too quick, and the app crashed momentarily. If you hold the manga list option and then the top manga option, then let go at the same time, the app will lag out. Restarting the app fixes it.

**Comment by Drutol** [comment]
Roger, I'll fix this over the weekend with more tricky stuff from #64.

I hope to do full release next week, but we'll see about that. Exams start again -.-

**Comment by Drutol** [comment]
Fixed, thanks for report :)
