### ISSUE TITLE
Excellent app for android, I have some suggestions

### ISSUE THREAD

**Issue by MakuSensei** [Drutol/MALClient#129]
With the time that I have been trying this app you can confirm that it is the best one I have used.
I found some bugs in the calendar that do not correctly filter the animes in the list on the corresponding days.
It would also be nice if you were in Spanish xD

If I find other problems I will report it right away in this report

**Comment by Drutol** [comment]
Hello!
I'm really glad to hear that! ^^

As for calendar, the data is scarce and if I recall correctly it's taken from "Air start day" which is hardly ideal. You can use slider in settings to set offset for these days.

I've never intended to localize this app but maybe after getting all the features in? Maybe, I don't know. Whole content is in English anyway so such mix would be confusing?
