### ISSUE TITLE
Quick Suggestion

### ISSUE THREAD

**Issue by nandito104** [Drutol/MALClient#131]
Great app. At first I doubted the interface but it quickly grew on me and it's become my favorite MAL Client. I was wondering if it could be possible to add comic book integration to both the Android and UWP app?

**Comment by Drutol** [comment]
Hi!

By "comic book" do you mean to read manga in app?

**Comment by nandito104** [comment]
@Drutol not exactly (although it would be awesome if you could add it) I mean something like keeping track of comics from as Marvel, DC, etc.

**Comment by Drutol** [comment]
Everything is tailored to pretty unique inner workings of MyAnimeList and adjusting it to something else is impossible. Moreover it'd be too much of an off-topic within an app.

As for reading/watching support...  I won't be doing this, there are copyright issues that I don't wish to deal with. 

Sorry that I cannot help much here :(
