### ISSUE TITLE
Future plans!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#132]
Now with android being released, I can finally add some more stuffs  (ekhem... bugs)  to the app!

The first thing I'm planning is to update UWP with little features that I've added in the last 2 weeks to android version (behind the scenes shared mechanisms).

Going forward I'm going to play some Nier... I'm just waiting for steam summer sale now.  :D

Once I'm done with it I'll do:
1. ~List comparisons.~
2. Clubs.
3. Full search - remade from scratch - ctrl + a & delete
3. ??? What am I missing?

Some smaller things:
1. Recent Reviews
2. Friends accept/reject and display of all friends.
3. Studios

Clubs are somewhat bigger but list comparison will require trickier UI.

In the far future (i.e. November?) together with Fall Creators Update I'm planning to apply Fluent Disgn (blurify everything that is ^^) to UWP app, and rework UI to some extent.

**Comment by Drutol** [comment]
Nier is progrsing nicely! First ending is completed and now I'm halfway through second "route". ^^

**Comment by Drutol** [comment]
Nier is finished... what a glorious game.... now back to Visual Studio :D

**Comment by noctuid** [comment]
With regards to list comparisons, would you consider adding a way to just view another person's list like you would your own? Or is that already possible?

**Comment by Drutol** [comment]
It's possible! You can do so either visting somebody's profile or on anime list page:
* Android
   * Hold action button to set "list source"
* Windows 
   * Press "..." on bottom AppBar.

**Comment by noctuid** [comment]
Ah thanks. I'm really glad to have found this app; it seems close to perfect for me. I've noticed two minor things with the android app. When I'm disconnected from the internet, shows that don't have downloaded thumbnails use the thumbnail from other shows (which is somewhat confusing; it would be nicer if they were just black or if there was a placeholder). When connected to the internet, and old/incorrect thumbnail will often flash for a second when scrolling down as well. It would also be nice if previously added tags showed up as tappable suggestions when adding tags. I can make separate issues for these if you would prefer.

**Comment by Drutol** [comment]
Separate issues won't be necessary :)

**Comment by noctuid** [comment]
Thanks a lot for adding these features so quickly! As for the flickering images, there doesn't seem to be any problems with images that already have thumbnails. However, for shows that a thumbnail hasn't previously been cached for, the image will sometimes flicker (the scrolling speed doesn't matter, only that the images haven't been previously displayed). It seems to occur less often and the correct image is displayed more quickly (there is still flickering, but the incorrect image isn't in place long enough to be visible) now after the last update.

**Comment by Drutol** [comment]
List comparisons are now semi done!
#134

**Comment by hohoaisan** [comment]
Promoted ur app :)) https://m.imgur.com/a/MVO3B

**Comment by Drutol** [comment]
Thanks!
