### ISSUE TITLE
List comparisons!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#134]
I've started working on them and I'm thinking about sorting and filtering there...

![image](https://user-images.githubusercontent.com/6102530/27763234-d963243c-5e7f-11e7-9a61-35e80bf348d6.png)

Any ideas? This is the best time to send wishes!
I'll probably know what would be useful once I get it work too.

**Comment by Drutol** [comment]
![image](https://user-images.githubusercontent.com/6102530/27764110-a764fa20-5e91-11e7-8a4d-28c3e7755160.png)

I'm thinking about such design when item is on other list but not on ours.

**Comment by Drutol** [comment]
![image](https://user-images.githubusercontent.com/6102530/27764769-ff5eef5a-5ea1-11e7-8ed4-2642d199f483.png)

Comparison mode and "other person doesn't have this" mode

**Comment by Drutol** [comment]
![image](https://user-images.githubusercontent.com/6102530/27768051-ea97c6c4-5f09-11e7-8c50-bbcf10d09ce1.png)

BLUR!

**Comment by Guerra24** [comment]
It looks damn good. It is possible to add a parallax effect (when scrolling) to the blurred images?

**Comment by Drutol** [comment]
Give me a second

**Comment by Drutol** [comment]
I tried but for items in list it won't work that easily. That being said effect was pretty cool:
![gif](https://user-images.githubusercontent.com/6102530/27768372-6444c80c-5f12-11e7-9179-43fc8220b2b8.gif)

Maybe in the future I'll play with it ^^

**Comment by Guerra24** [comment]
😮😮😮😮 It's fucking gorgeous, I need that xD

**Comment by Drutol** [comment]
The problem is that I'd have to apply offset to every itemd epending on itm's postion in grid view. This position can change.

If I don't do that:
![image](https://user-images.githubusercontent.com/6102530/27768415-6549ca44-5f13-11e7-9e26-552008b30749.png)

Because scroll is to big relatively to item's first visible position.

**Comment by Guerra24** [comment]
Is that the same parallax effect shown in the MS blog?

**Comment by Drutol** [comment]
Hmm, I'll take a look. I've used something else.

**Comment by Drutol** [comment]
I've spent far too much time on this but I'll have something working and it's gonna be glorious

**Comment by Drutol** [comment]
I did it! Mom I did it!

**Comment by Guerra24** [comment]
Where is my blur? 😞

![img](https://puu.sh/wC4eu/bedf81c0ad.png)

**Comment by Drutol** [comment]
I thought is going to be better without blur

**Comment by Guerra24** [comment]
:_( 
Add toggle pls :)

**Comment by Drutol** [comment]
Okay... I'll need to make the right part darker in some modes too

**Comment by Drutol** [comment]
@Guerra24 I wanted to push these changes 7 days ago but MSFT found some strange things about the package and as I was about to head out for my holidays I'll try to push it today.

**Comment by Drutol** [comment]
As a bonus I'll add some additional blur :D

**Comment by Guerra24** [comment]
Blur looks good, also: 

- In "Show other user's items" doesn't blur the entire image [Video](https://puu.sh/wPD0n/a4eef0785e.mp4).
- Scroll bar is behind the top "panel". 
![Image](https://puu.sh/wPDco/9838d53119.png)
- Why not use the Acrylic blur for the images and panel?
