### ISSUE TITLE
Synopsis unavailable

### ISSUE THREAD

**Issue by dinosw** [Drutol/MALClient#136]
No matter which anime I view from the MALClient for Windows, it cannot display the synopsis, the only text displayed below the header "Synopsis" is "Synopsis unavailable...".

**Comment by Drutol** [comment]
Hello, that's very strange. I cannot reproduce this bug.

Is there a chance you could use this: http://www.telerik.com/fiddler to check what gets returned from MAL?

**Comment by dinosw** [comment]
Hi
I was just about to run a debug with Fiddler, but apparently I do not have the problem anymore =)
I can see, that the app was updated 3 days ago, so the problem must have been corrected in that update.
Otherwise Fiddler must have fixed it, as I used the WinConfig in Fiddler to enable loopback for MALClient.

**Comment by Drutol** [comment]
UWP wasn't updated for a while so maybe that was it. Thanks for reaching back!
