### ISSUE TITLE
"Manga list" status filter on sidebar missing? (Android, image included)

### ISSUE THREAD

**Issue by RudeBoyEEEE** [Drutol/MALClient#140]
Where it says "Manga list", I think the "..." is missing for filtering the status of the list. Can this be fixed? Sorry if I'm using the wrong terminology.

![screenshot_2017-07-22-05-07-44](https://user-images.githubusercontent.com/24692232/28489912-018587bc-6e9c-11e7-8f11-a548b2258724.png)

**Comment by Drutol** [comment]
Hello! It seems like I've forgotten about it, this will be fixed in next update :)

Thanks for report!

**Comment by Drutol** [comment]
Added
