### ISSUE TITLE
Statistics feature 

### ISSUE THREAD

**Issue by JamessonCheron** [Drutol/MALClient#142]
Something that I've being missing is the statistics about how many Animes/Manga I have in my lists and how many times i have rewatched an anime. 

Something as the image in attach:
![screenshot_20170724-220751 1](https://user-images.githubusercontent.com/22543608/28551303-8c3b6a7a-70bd-11e7-98dc-6e30d5e6b29c.jpg)

Going a bit further i would also suggest some _Time spent statistics_. As all Anime have a duration time  It would be really nice to sum up all the time o have spent watching Animes. 

Something as the image in attach:
![screenshot_20170724-222404 1](https://user-images.githubusercontent.com/22543608/28551638-a7ebf5b2-70bf-11e7-904c-6d2bb0db5e1a.jpg)

**Comment by Drutol** [comment]
Hello, stats section in profile does exactly this :)

**Comment by JamessonCheron** [comment]
My bad then hihi! Just disregard it :D thx for the reply

**Comment by Drutol** [comment]
:)
