### ISSUE TITLE
Can't update anime (or manga) episodes (or chapters) watched (or read) while on cellular data

### ISSUE THREAD

**Issue by RudeBoyEEEE** [Drutol/MALClient#143]
Just what the title says. I am having trouble updating my episodes/chapters when I am not connected to WiFi, even if I have cellular data turned on. Any way to fix this? Thanks, love the app!

**Comment by Drutol** [comment]
Hello, hmm this is very strange... can you check whether https://myanimelist.net/api/ accepts your credentials?

**Comment by RudeBoyEEEE** [comment]
Okay, I tried that and this is the screen I got (on my Android tablet):


![Screenshot](http://i.imgur.com/MUcDRJQ.png)


_Sent from my Lge VK410 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Drutol** [comment]
Hmm, I rather had in mind trying withcellular data... ^^

**Comment by RudeBoyEEEE** [comment]
Oh, right. Sorry about that... Here it is with cellular data on my phone:
![Screenshot](http://i.imgur.com/qAcwE9u.png)


_Sent from my Lge VS987 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Drutol** [comment]
And it still refuses to work?

**Comment by RudeBoyEEEE** [comment]
Yeah, just tried it on data, no dice.

**Comment by Drutol** [comment]
Truth be told I don't have any idea... other apps like PocketMAL are working ok?
I've just got my android phone and it works as expected. :(

**Comment by RudeBoyEEEE** [comment]
The latest version, for sure. Anyway, weird thing, it's working again... I guess it was just a fluke?

**Comment by Drutol** [comment]
MAL itself is pretty unstable maybe that was it it's just one big mystery box :(
