### ISSUE TITLE
An idea for a future addition to the APP

### ISSUE THREAD

**Issue by Connity** [Drutol/MALClient#144]
So today in the patch notes in app I saw that the developer is running out of big updates to make to the app. Let me start by saying, yes, it is an extremely great MEAL client and I love it! One idea that I would love to see implemented to this already great interface is a randomizer for the plan to watch and also for just all of MAL. I don't know how possible this may be to achieve but I sure would love to have access to this in the app I already use. Keep up the great work! :)

**Comment by Drutol** [comment]
Hello, I don't know whether I misunderstood or something was lost in translation, but randomizer for PTW is already here. (ActionButton -> Shuffle).  ^^

Adding this for completely random anime shouldn't be much of a problem logic wise... where would you put a button for such feature? Search? There's so much stuff that I don't have space to place buttons :D

**Comment by Connity** [comment]
If it's possible to have it on an additional click of the anime tab in search maybe that would work. Or even just typing random into the search bar maybe? I definitely see what you mean with the lack of space though... If need be it could be in the sidebar underneath search.

I totally over looked the PTW randomizer thanks for letting me know! XD
