### ISSUE TITLE
No Ads

### ISSUE THREAD

**Issue by Japa986** [Drutol/MALClient#145]
I'm not getting any Ads in Windows app even though I set them as enabled and to show indefinitely.

**Comment by Drutol** [comment]
Heh, it's just how Microsoft ads are. They are unable to find any ^^ Thanks for supporting me but right now I can't do much about it.

**Comment by Japa986** [comment]
Oh, OK. Then if possible can you add an alternate way to donate, because the one in app is tied to Microsoft account and I don't like that. Like I choose to pay with PayPal and it still asks me for all my info and address for some reason.

**Comment by Drutol** [comment]
Well I can add paypal donate button in github repo's readme... ^^

**Comment by Drutol** [comment]
Doned

**Comment by Japa986** [comment]
Tnx, donated.
P.S. I know it's a small amount, but just wanted to show my support

**Comment by Drutol** [comment]
Thanks! It's quite something considering it's more than ads yielded since launch ^^
