### ISSUE TITLE
Procurando animes

### ISSUE THREAD

**Issue by Hamilko** [Drutol/MALClient#146]
Olá, eu sou do Brasil e começo agradecendo a equipe pelo belo trabalho que vocês tem feito. ^^
Então, a minha sugestão está relacionada à busca de animes.
O meu MAL me permite ordenar animes por gêneros e estúdio apenas. Acho que poderia ser adicionado especificações tais como notas do anime, data de lançamento, popularidade, até quem sabe numero de episódios. 
Além disso, um sistema de filtro para caso você queira estabelecer mais de uma
especificação na busca do anime. Como por exemplo: animes de nota 7.5+ e 25 eps..
Isso faria com que a área de busca fosse utilizada para quando queremos assistir alguma coisa mas não temos ideia do que.

**Comment by Drutol** [comment]
Hello, English please if possible.

>Hi, I'm from Brazil and I start by thanking the team for the beautiful work that you have done. ^^
So my suggestion is related to the search for animes.
My MAL allows me to sort animes by genres and studio only. I think it could be added specifications such as anime notes, release date, popularity, even who knows number of episodes.
In addition, a filter system in case you want to establish more than one
Specification in the anime search. Like for example: animes of note 7.5+ and 25 eps ..
That would make the search area used for when we want to watch something but we have no idea what.

**Comment by Drutol** [comment]
Hmm, MAL is planning on redoing their API pretty soon with much better search. Therefore I won't be implementing it now by scrapping web pages. I'll wait for new API as search is pretty big thing and doing it twice isn't something I want to do. You'll have to wait a bit. Good suggestions anyway :D
