### ISSUE TITLE
Please add Glossy theme & Thumbnail of related animes

### ISSUE THREAD

**Issue by sinusshahi** [Drutol/MALClient#148]
Hi, I really like your work on MAL client. This app is great. It gives me every feature of M.A.L server. I really wanna thank you a lot for your hard work. Although I don't have the ability to donate on paypal. 😥 But I can give you my Respect from the bottom of my heart. 💙 😊 I wanna request you about some other things. I hope you don't mind me. 😊 -

1. Please add a Glassy/Glossy/Transparent theme. I think it will be more great to look for everu user also.
   * Do you mean Windows or Android version? If it's windows I plan to apply a bit of "fluent design" once Fall Creators Update hits. If it's Android could you post some pictures with "glossy" theme you have in mind?
2. Please place "Related anime" tab in third place. Before "Reviews" tab.
   1. Please add thumbnails of related animes in "Related tab".
4. is there any way to make notifications system more active? (Ex: LiveChart.me). Livechart.me app updates every current airing anime time in exact time to time via notification. Is it possible to get notified currently airing anime episods releases like that fast via MAL Client?
   * It's not possible unless I host a server with push notifications which cost money, I do not intend to add server infrastructure to this project.

Please consider, if possible.  Sorry for my selfish requests & being so much noisy. 😊

**Comment by Drutol** [comment]
Edited your post with replies so it's tidy ^^ Hello!

**Comment by sinusshahi** [comment]
Thank you for your reply. ☺ I'm an android user, so I want update for android.
Here, "glossy" I wanted to mean blury transparent background. (Like ios notification tab). Or you can check this music player please. This music player has "Glossy" looking theme- 
https://play.google.com/store/apps/details?id=com.Project100Pi.themusicplayer&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dpi+music+player+glossy+theme&pcampaignid=APPU_1_5lydWYC3KczuvASwvZqADg

Thanks again. 💙☺

**Comment by sinusshahi** [comment]
Anout glossy look- I don't know how to describe it. But for better idea pleas look this App details images.

https://play.google.com/store/apps/details?id=com.sec.android.app.music&hl=en

This music player user interface I mean- ⬇⬇

https://play.google.com/store/apps/details?id=com.playermusic.musicplayerapp&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dmp3+player+app&pcampaignid=APPU_1_-V-dWd2sAoiEvQS4iarwDg

**Comment by Drutol** [comment]
Oh, this is certainly not easy task and I'd have to be designing app like so from the very beginning. I don't like Material Design too but as this is my first android app I wanted to keep close to common android conventions. Windows will look like it because native support  glows/blurs/lights and so on is on its way for

**Comment by sinusshahi** [comment]
Ok. I understand. 😥
Thanks for your time though. ☺

**Comment by sinusshahi** [comment]
Btw, I found out another issue, can't  send friend request to any user. Is it possible to add a button in users profile view so that we can send/accept  a friend request from MalClient? 😊

**Comment by Drutol** [comment]
Well, sending/accepting friends is not here yet. It'll appear in future update.

**Comment by Drutol** [comment]
Added images to related tab (v1.2.4.0+)

**Comment by sinusshahi** [comment]
![myscreen_2017-09-01-19-59-14](https://user-images.githubusercontent.com/31254830/29973196-7b82609c-8f50-11e7-9619-08ef1f063053.png)
 But I didn't  find any. 😒 I updated app to its latest version though. Found no  Thumbnails of related annimes.

**Comment by Drutol** [comment]
Well I said 1.2.4.0+ so it will appear in next update which is currently being baked ^^

**Comment by sinusshahi** [comment]
Opps! my bad! 😜 Eagerly waiting for the update. Thank you again. 💜🙌

**Comment by Drutol** [comment]
I've just pushed an update
 :)

**Comment by sinusshahi** [comment]
Hello, Mr. Drutol.  Hope you are well. 😊
Believe it or not, I'm always waiting for your next update. Today I wanna request something-

(1)  Recently I noticed that there is no option about sharing any anime with my friends via any social app (ex:massenger,whatsapp). Please add a "Share" button to every single anime page. So that when we open any specific anime details page, we can share this anime link to our friends via other social apps. I mean, Share button will trigger others installed social apps for share any anime.

(2) Please increase the thumbnail size of "Related anime" tab. Make it more bigger like "Recoms" tab. In latest version, it's kind of small to view. 

(3) Please add a option of "Grid view" in all anime list. As like as (ex: Profile>Favorite Anime) grid view.

(4) I guess there is some minor bug/lag in latest app. When I minimize & maximize app it get crushed. A pop up says 'MAL Client is not working. please wait or close'. It also happens after using app for log time. ( I'm using Android 6.0)

Thank you sir for always being so patient & considering. Thank you always for listening our selfish requests. 💜😃

**Comment by Drutol** [comment]
Hello!

1. What would be the scenarios to share? Just link to MAL?
2. I can't really agree here, It's just small picture to hint what anime/manga is it. I will increase its size a little bit but not to match the size of pictures in Recoms tab.
3. It's available since day one :) It's default option so you've probably changed the default in settings. Display modes can be changed temporarily in action button menu (long press action button).
4. Hmm on what pages does it happen? Any chance of GIFs being there? I cannot really reproduce it.

**Comment by sinusshahi** [comment]
I mean, I want to share any anime link with my friends via other social apps. So that my friend will get the link/Title+Thumbnail of MAL site of that anime. 😊

Ok atleast increase the thumbnail size of related tab a little please. 😞 Cause, for small sized handset/screen, those thumbnails r difficult to recognize sometimes. 😢

And the crush happens often. There is no particular page. Sometimes it forced MAL client to shutdown. And also like I wrote above.

Thank you Mr Drutol for your time. 😊😊

**Comment by sinusshahi** [comment]
Hello dev, its been a while since I'm messaging you. Hope your are doing well in your study. Today I wanna request something, It's about adding "Genres" menu. It'll be really helpful if you add a Genres option in side menu. So that after clicking genres button we can view all kind of anime genres listed in MAL in a list and choose our required genres anime. as an example: when we click the 'Romance' or 'Action' or others genre, Then all the anime of related genre(that I've clicked) of MAL will show serially. Just like search result. Or else, please make every genre clickable in 'Genres' area of anime details tab. So when we click any genre, It'll show us related genres animes. Hope I make you understand what I wanted! I'm sending attached image as example, an anime streaming app which has this option. Please check. 😊
![received_776119969240060](https://user-images.githubusercontent.com/31254830/31718468-e10400f0-b431-11e7-89de-1e3f0381ca0e.jpeg)
![myscreen_2017-10-18-17-50-03](https://user-images.githubusercontent.com/31254830/31718485-eece04ec-b431-11e7-8389-001387b4ab3b.png)
