### ISSUE TITLE
This File could not be found. (MALClient.XShared\Secrets.cs).

### ISSUE THREAD

**Issue by anson1124** [Drutol/MALClient#151]
Hi ,

I have got the following error when I was trying to build the application

This File could not be found. (MALClient.XShared\Secrets.cs).

**Comment by Drutol** [comment]
Hello, you will have to add this file yourself. There are just 3 strings with HockeyApp keys and android password encryption one. You can probably make them empty.

**Comment by Drutol** [comment]
Like so:
```
public static class Secrets
{
    public const string AndroidEncryptionPassphrase = "...";
    public const string UwpHockeyId = "...";
    public const string AndroidHockeyId = "...";
}
```
