### ISSUE TITLE
Feature request: "Zoom in", in the cover image

### ISSUE THREAD

**Issue by Wolfteam** [Drutol/MALClient#153]
Hi!, thank you for your app, its awesome :+1: 
 I would really like to be able to"click" in the cover image (the one that appears when you go into anime/manga details) and then "zoom in" to see it better.

**Comment by Drutol** [comment]
Hello, I'll see what can I do :)

**Comment by Drutol** [comment]
Added :)

**Comment by Wolfteam** [comment]
thank you :D
