### ISSUE TITLE
Suggestions & Bug Report

### ISSUE THREAD

**Issue by sh1nrei** [Drutol/MALClient#155]
I've a few suggestions for the app.

1. When opening the app, you could force automatic synchronization. Yes, it is not a big deal to swipe down to refresh the list but that is one of the things I would welcome.

2.I'm the type who rates anime only after he finishes it, again, yes it's not a big deal to set it beforehand but I like the feature that Pocket MAL has, it ask me if it should set it as Completed and asks me to set a score for the series.

And also a bug report.

I don't really know if this only happens to me but, when I browse images and tap the load more images button(?) I continue to swipe down and I get a "reset" and I kinda have to start scrolling from the top all over again. Also, the last image when I scroll down before hitting the button is always the same one from months ago.

Anyway the app is really cool and you did a great job, thank you ;)

**Comment by Drutol** [comment]
Hmm I didn't reply for some reason... sorry...

1. I think the list has valid cache time of 10 minutes. It slightly improves startup times.

2. I've implemented it two updates back, after reading it here ^^ Just forgot to respond.

Images page will be getting total rework soon... ^^
