### ISSUE TITLE
Widget bug?

### ISSUE THREAD

**Issue by RedWavez** [Drutol/MALClient#156]
Hello! First of all, thanks for the app, it's really useful. Sencondly I would like ti report a bug.

I am using Nova Launcher and I think the widget has some compatibility issues with the launcher. When I place the widget on my home screen it works well for that day. However, next day it doesn't show any shows "Nothing is airing today" and I am sure there is something airing.
To fix it I have to always remove and place the widget.

Android version: 6.0

Thanks :)

**Comment by Drutol** [comment]
Hi, I keep having problems with this widget (as last few changelogs would suggest ^^). I'm slowly getting there but it persistently refuses to cooperate. It's on my radar! Thanks for report!

**Comment by Drutol** [comment]
Okay I think I got it, should be better in next update. ^^

**Comment by RedWavez** [comment]
Thank you! :D
