### ISSUE TITLE
App Icon for android version

### ISSUE THREAD

**Issue by McFissh** [Drutol/MALClient#157]
Can we get a round metarial icon to match the latest android design?
P.S- There's nothing wrong with the current icon but I think a round icon would be a cool change.

**Comment by Drutol** [comment]
Hello, sorry for late reply.

I'm not sure when I'll get my hands on Android Oreo device/emulator. I'm currently rolling with Xiaomi's MIUI and I have AMD processor for which google didn't release emulators (yet). I'll look into it once I get the opportunity.
