### ISSUE TITLE
Help for translate to Japanese

### ISSUE THREAD

**Issue by Hagepaka** [Drutol/MALClient#159]
Thank you for making this app.I really like this.

Do you have a plan to support any other language like Japanese or something?
There're many hidden Japanese user in this app so If it possible please support :)
I don't have some skills of programming ,but If you need help ,when you support Japanese I'll help translate.

**Comment by Drutol** [comment]
Thanks for the offer!

Unfortunately localization has the lowest priority as it gets right now. Maybe in the distant future I'll implement it but for now it's English only.
