### ISSUE TITLE
[Suggestion] Link File to Anime

### ISSUE THREAD

**Issue by Strosk** [Drutol/MALClient#160]
It's possible to create an link for open the anime episode file from anime description page?

**Comment by Drutol** [comment]
Hello, and where could this link lead?

**Comment by Strosk** [comment]
It would work as follows: In the anime page I have an option to link a file (video/episode) to the anime page. That way I could from the page of the anime open the video of him that I have on the cell phone. Something similar to Kodi.

**Comment by Drutol** [comment]
Okay but I won't have any way of obtaining these links, you'd have to provide them manually. Even then what kind of links would that be? I didn't use Kodi

**Comment by Strosk** [comment]
I would add the links manually as a database.

It would just be links where I would click and he would ask which video player would like to open the anime episode.

**Comment by Drutol** [comment]
Hmm, I think it's an overkill for this app. I don't really want to get into playback or file/source management here.

**Comment by Strosk** [comment]
Ok Drutol, but anyway thank you for the application, it's really the best to keep track of MAL. xD
