### ISSUE TITLE
Sort by priority?

### ISSUE THREAD

**Issue by Ryrynz** [Drutol/MALClient#161]
Is it possible to sort by priority yet? I don't think the API allowed it to be done the last time I checked.

**Comment by Drutol** [comment]
Hello, what is "priority"? Something you can set on mal?

**Comment by Ryrynz** [comment]
Yes, under edit details for anime is a watch priority of Low, medium and high.

**Comment by Drutol** [comment]
I'm afraid MAL's API doesn't provide this data in its current state :(

**Comment by Ryrynz** [comment]
Yeah author of Pocket MAL said so too last time some years ago. I've made the request before to have it added to the API but no luck. Do you know anyone over there that could make it happen?

**Comment by Drutol** [comment]
They are making new API which should be available somewhen next year so maybe then.

**Comment by Ryrynz** [comment]
Hopefully then. Keep up the good work.
