### ISSUE TITLE
I can't seem to download this on Windows Store

### ISSUE THREAD

**Issue by densityx** [Drutol/MALClient#169]
Hi, it seems windows store won't allow me to download the app 😢 

I am using latest update of windows 10 (not the creator edition)

![applicationframehost_2017-10-12_21-11-51](https://user-images.githubusercontent.com/10068719/31497585-224d4f48-af92-11e7-9283-e72f649fcaa3.png)

and this is how it look like in the windows store

![applicationframehost_2017-10-12_21-12-16](https://user-images.githubusercontent.com/10068719/31497621-391b14b2-af92-11e7-895e-61212e0d67b2.png)

welp

**Comment by Drutol** [comment]
You seem to have pretty ancient version ^^

```    
<TargetPlatformVersion>10.0.15063.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.15063.0</TargetPlatformMinVersion>
```

**Comment by densityx** [comment]
xD oh myy it's the latest update / build

I might need to upgrade to Creators update soon

**Comment by densityx** [comment]
but then can you change the os requirements?

![2017-10-13_07-03-26](https://user-images.githubusercontent.com/10068719/31523194-a3f848d4-afe4-11e7-96b7-4e9ce10b2406.png)

**Comment by Drutol** [comment]
Hmm... the heck?
![image](https://user-images.githubusercontent.com/6102530/31531721-0e2c51e2-afe9-11e7-9272-1546edcf2904.png)
This is what I see on store listing. You are on your desktop device right?

**Comment by densityx** [comment]
Yes I am, but then that was before I update my Windows 10 creators update
(probably, for non windows 10 creators update users, they see that)

now it looks like they have update it
![applicationframehost_2017-10-14_07-40-08](https://user-images.githubusercontent.com/10068719/31570056-e8c8208c-b0b2-11e7-8131-67ec2babfdc7.png)
