### ISSUE TITLE
Blank after app switchings

### ISSUE THREAD

**Issue by jGRite** [Drutol/MALClient#170]
After opening the app and switching between apps a few times I'm left with this screen. Because of this happening I have to close the app clear the app from the recents and then open it again.

Pixel C Oreo.

![screenshot_20171001-013049](https://user-images.githubusercontent.com/5149994/31561092-c4e764a4-b024-11e7-8f6d-1bbc18a06b93.png)

**Comment by Drutol** [comment]
Hello, I didn't run the app on adnroid 8 yet. Current build isn't even using newest SDKs so this may be the cause. I'll look into it when I've time.
