### ISSUE TITLE
i really like your app but can you add this feature?

### ISSUE THREAD

**Issue by showstopper012** [Drutol/MALClient#172]
![2017-10-16 12 21 37](https://user-images.githubusercontent.com/32828583/31595369-d9055464-b26d-11e7-8671-8fe322486536.png)
this feature from iMal is really helpful to keep me updated when new ep is already aired or i missed something i hope that you can add this. .

**Comment by Drutol** [comment]
Hello, this info is displayed in anime details page (general, under current status) :) Also current episode is highlighted in watched episodes dialog.

**Comment by showstopper012** [comment]
i see thanks. .is there any way to put it outside?beside the TYPE. .it takes time to check it one by one. .sorry if im asking too much im just spoiled by imals feature. .i really love your app all of your features i just want it to be perfect and easy

**Comment by Drutol** [comment]
I'll try to cram it somewhere.

**Comment by showstopper012** [comment]
thanks! your app is the best hands down

**Comment by Drutol** [comment]
It took a while... but it will now be displayed in type bar like so `TV 2/12`. Also the number in ep chooser will be much bigger than previously.

**Comment by showstopper012** [comment]
thanks for the update!

**Comment by showstopper012** [comment]
<3
