### ISSUE TITLE
No Releaseday anymore

### ISSUE THREAD

**Issue by Lolliix** [Drutol/MALClient#176]
Hey!

I just wanted to ask if the little show day at the left corner of the anime cover was removed o: I searched the whole settings but didnt find an option to activate/deavtivate it. For those who dont know what i mean:
http://puu.sh/ygi1Y/656d4648fd.jpg
thanks!

**Comment by Drutol** [comment]
Hello, if you mean countdowns in top left corner they will be displayed on the same day and not on calendar page iirc as there are other countdowns already.

**Comment by XavierBlack** [comment]
I think he means the Sun, Mon, Tue, Wed, Thu, Fri, and Sat overlays that are displayed over the cover in the upper left corner are completely missing now (see his screenshot).  I'm having the same issue... in addition to that I also went to the calendar and my calendar is not completely blank after the recent update.

**Comment by Drutol** [comment]
That's strange I'll check it in the afternoon

**Comment by Drutol** [comment]
Okay got it. Apparently MSFT screwed something up. Update should be available early next week.
