### ISSUE TITLE
Bug! Episode data and Status not showing up.

### ISSUE THREAD

**Issue by nandito104** [Drutol/MALClient#180]
On the Windows 10 client of the app, the episode counter and all the buttons present on the images isn't showing up when using the light theme of the app. Below (hopefully) is a screenshot of what I mean.
![screenshot mal](https://user-images.githubusercontent.com/22856479/33633416-1b5a3d3e-d9e7-11e7-893f-15b06b503167.png)

**Comment by Drutol** [comment]
Hmm, pretty strange. Which version are you using?

**Comment by nandito104** [comment]
Version 5.3.29.0. I just opened the app to look which version I was using and they showed up correctly, which is curious.

**Comment by Drutol** [comment]
Hmm, did previous version have blur?

**Comment by nandito104** [comment]
It's enabled. The data is shown at random startups.

**Comment by Guerra24** [comment]
I see it now, sorry! I forgot to change the text color in the light theme. When transparency is disable it fallback to white and the text is white...

![image](https://user-images.githubusercontent.com/9023392/33731022-6de3444a-db47-11e7-90d8-76bdeb33595f.png)

**Comment by nandito104** [comment]
No worries, just glad to be of help.

**Comment by Guerra24** [comment]
This has been fixed a while ago.
