### ISSUE TITLE
Data consumption

### ISSUE THREAD

**Issue by tedechan** [Drutol/MALClient#181]
The app time by time downloads data in a background.
It's can download about 40Mb in half of a day.
Personally I disabled connection for app in background by "Opera Max", but when I open it, I have to manually update my list by "pull to refresh" gesture.
Is there an ability to increase an updates "interval", or to do a cache of data for offline mode to reduce an amount of the application traffic?

Hards: Meizu ME Note (L681H revision);
OS: Flyme 6.1.0.0G based on Android 5.1 (lollipop).

**Comment by Drutol** [comment]
Are you sure that's all of it is downloaded in background? I find it impossible for it to download this much data... do you have widget enabled?

**Comment by tedechan** [comment]
I hadn`t enabled widget.
I made sure that`s it background, because I don`t open MAL-app, but when I open "Opera Max", I see a lot of it`s data, as I written previously.

**Comment by Drutol** [comment]
And what's the system saying and not this `Opera Max` app?

**Comment by tedechan** [comment]
I looked for this in "Security" app, and it's says that today it's had consumpt even a little bit more than says Opera app, around 26,7 (Mbyte).

**Comment by Drutol** [comment]
On my phone it's just a few KBs, probably depends on the ROM. What's your notification pooling frequency setting?

**Comment by tedechan** [comment]
Every 15 minutes.
