### ISSUE TITLE
Bug? and Suggestions

### ISSUE THREAD

**Issue by Hagepaka** [Drutol/MALClient#185]
1.I can't find the studio named white fox at the studios search .

2. I want to search anime and maga with Japanese. The original Myanimelist website can search with Japanese so I'd like to Implement it.

**Comment by Drutol** [comment]
Hello, the website search api is much better than the one meant for 3rd party apps and it offers no such functionality.

As for White Fox... I must have missed it.

**Comment by Hagepaka** [comment]
I understand. It cannot be helped.
Any way I love your app! Thanks for the reply.

**Comment by Drutol** [comment]
Added
