### ISSUE TITLE
Anime History appears empty when user's list is private

### ISSUE THREAD

**Issue by AmineI** [Drutol/MALClient#186]
Hi !
It may be because of the lack of API to access an user's history, but I noticed that checking my (private) anime history in MALClient always shows it as "Empty…", while it appears normally on the website(if I'm logged in.).
It doesn't happen if I make my anime list public, which may be a consequence of not authenticating to the MAL website before trying to access that data ?

Do you have an idea about that issue or can't it be solved until a better MAL API is released ?

Thanks for your continued work on the app, by the way ! It's one of the best out there, and the UWP version is super handy.

**Comment by Drutol** [comment]
Hello, yeah it's because I'm getting this particular info without authenticating the request.

Sorry for lack of updates for a past few months, I'm on a little hiatus now while recovering from a burnout. I hope to make little maintenance in February, I'll look into it then :)

**Comment by Drutol** [comment]
Fixed
