### ISSUE TITLE
cant login 

### ISSUE THREAD

**Issue by FelipeAE** [Drutol/MALClient#187]
i put my username and my password correctly and i got this 
![screenshot_12](https://user-images.githubusercontent.com/32912012/35077035-f718ac34-fbd9-11e7-89c4-47ce7b751a4a.png)

**Comment by Guerra24** [comment]
The message says it, MAL banned your IP. Wait 2~ hours without using the app and then try again.

**Comment by Drutol** [comment]
Yeah, MAL even admitted they have this mechanism bugged. Nothing we can do now.

**Comment by Drutol** [comment]
We can only wait for now bug-free api. It will be resolved then.
