### ISSUE TITLE
Better landscape support on mobile please

### ISSUE THREAD

**Issue by ashergz** [Drutol/MALClient#189]
When browsing a particular staff's page, the top portion blocks half the page when scrolling through list of their works. Example: https://i.imgur.com/wKXoNoe.png

Kindly make it so the top portion gets out of the way when you scroll up. Similar to the characters page. Thank you.

**Comment by Drutol** [comment]
Hi, I agree that I have to remake some old pages that now look just bad. I had no experience with Android back then ^^.

I don't know when, but I'll do it. Right now I'm fixing some other more important things.

**Comment by ashergz** [comment]
Any update on this? This is my only issue in your otherwise perfect app, and in the three updates we've had since then, I always have my fingers crossed this has finally been resolved. Just wanted to remind you in case you've forgotten.

**Comment by Drutol** [comment]
Uh oh, not really. I'm crazy busy with Uni+Work and I don't see it changing till the end of this semester (2 more months). Be sure to poke me then... sorry :(

**Comment by ashergz** [comment]
All cool man. Will remind you then.

**Comment by ashergz** [comment]
So it's been two months. During this time I also got a new phone, one with that super tall aspect ratio and now it's literally impossible to surf staff pages: https://i.imgur.com/6az7RSl.jpg

Are you finally ready to tackle this issue?

**Comment by Drutol** [comment]
Okay I'll check it tomorrow.

**Comment by Drutol** [comment]
![](https://cdn.discordapp.com/attachments/446928415153586179/465164468788396042/Screenshot_2018-07-07-16-35-57-109_com.drutol.malclient.png)

Fixed.
