### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by IAndersonI** [Drutol/MALClient#195]
The app doesn't show any images.

**Comment by Drutol** [comment]
What do you mean by "any"? Seems to be okay for me.

**Comment by IAndersonI** [comment]
I mean there are no pictures, I just can't see them, the pictures doesn't load. :(

**Comment by Drutol** [comment]
Images where exactly?

**Comment by IAndersonI** [comment]
On the screen

**Comment by IAndersonI** [comment]
There is no pictures on the "anime boxes", my perfil pictures doesn't load, the only images that appear are those of the "other/images" tab.

**Comment by sesshoth** [comment]
I am not having the issue anymore but thanks

**Comment by Drutol** [comment]
Maybe MAL's cdn had problems.

**Comment by sesshoth** [comment]
I dunno but I am just glad that it is working again because it is easily the best client out there the only other problems I have are sometimes shows don’t show up in the client when I search, so I have to go to the website to select them first. It seems to work fine after

**Comment by Drutol** [comment]
Thanks ^^.

Yeah, search is pretty bad because MAL's old API is pretty bad. I'll be migrating to new API in July probably.

**Comment by PixelatedBulb** [comment]
Hello there. I'm having the same issue as Anderson used to have. Is this something that just happens from time to time?

**Comment by Drutol** [comment]
It all started happening very recently. Someone suggested that the phone is running out of storage for image caching... would it apply to you?

**Comment by PixelatedBulb** [comment]
I still have more than 1GB left on my phone. That should be enough, shouldn't it? BTW I'm seeing images again but I already had more than 1GB when the images disappeared.

**Comment by Drutol** [comment]
Yeah that's plenty of space left. I'll try to investigate this weekend.
