### ISSUE TITLE
AniList Sync Support

### ISSUE THREAD

**Issue by kaiserdj** [Drutol/MALClient#198]
Hi,

Would it be possible to look into supporting sync with Anilist?
Our JSON API is fully documented here and not difficult to work with. Other users have successfully managed to create syncing apps.

Any issues/questions let me know.
The developer section can be accessed at http://anilist.co/settings/developer
https://github.com/AniList/ApiV2-GraphQL-Docs

Thanks

**Comment by Drutol** [comment]
Sorry, I'm currently so short on time that I can't even watch anime. :(

This project is now in maintenance mode and I'd probably rewrite it from scratch before adding anilist.
So yeah, sorry!

**Comment by Drutol** [comment]
Depending on how MAL resolves current situation I may just migrate myself and whole app to anilist.
I have had enough of supporting them... AniClient xd?
