### ISSUE TITLE
Missing related anime?

### ISSUE THREAD

**Issue by ChainekJan** [Drutol/MALClient#204]
https://i.imgur.com/CH6QzuC.png
https://i.imgur.com/vsJiujE.png

Ran into this yesterday. The related tab only shows the first related entry for all ptw and most completed entries. Tried reinstalling, didn't help.

**Comment by Drutol** [comment]
Hello, they might have changed something in html. I'll check.

**Comment by Drutol** [comment]
Yeah, they have changed html. Fixed.

**Comment by Drutol** [comment]
Haha, yeah until I publish update to the stores it will stay that way. ^^

**Comment by ChainekJan** [comment]
Oh, ok then. Thanks
