### ISSUE TITLE
More accents?

### ISSUE THREAD

**Issue by jesus87714** [Drutol/MALClient#206]
Hello, first say that I love your application. I would like to know if you could add more colors? Type cyan, red, light blue .. Thanks and best regards!

**Comment by Drutol** [comment]
Roger! I'll try to add some together with new logo update :)

**Comment by Drutol** [comment]
![image](https://user-images.githubusercontent.com/6102530/40253400-db0c91d0-5adf-11e8-8997-c9702c62ddf6.png) ![image](https://user-images.githubusercontent.com/6102530/40253410-e3735c6e-5adf-11e8-9bec-0150424addb1.png) ![image](https://user-images.githubusercontent.com/6102530/40253417-ec5de4ca-5adf-11e8-8cdb-4a488fed022c.png)

I've added these color palettes.

**Comment by jesus87714** [comment]
Wow, thank you very much. The best MAL client without a doubt 👍



2018-05-18 21:12 GMT+02:00 Piotr Szymczak <notifications@github.com>:

**Comment by jesus87714** [comment]
Wow, thank you very much. The best MAL client without a doubt 👍
