### ISSUE TITLE
About MAL just removing whole API

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#211]
MAL has just removed/disabled whole API and MALClient won't work without it. I'm already receiving flood of emails and I'm hoping that this "post" will explain situation for some. There's no ETA. Please go complain to MAL about it.
I'm angry.

**Comment by Kaishiyoku** [comment]
Seems like it has something to do with this:

![image](https://user-images.githubusercontent.com/5131112/40487358-390ef6d2-5f64-11e8-876e-c5ba4469afc3.png)

**Comment by Drutol** [comment]
Yup, I'm talking with their "community" staff on Slack but I still don't know much.

**Comment by ZeroOmar** [comment]
RIP API

**Comment by Drutol** [comment]
I guess I'll release an update saying that app won't work. They said that there's no ETA.

**Comment by TusharGod** [comment]
Give me the discord server link please

**Comment by Guerra24** [comment]
@TusharGod https://discord.gg/5yETtFT

**Comment by LooneyN** [comment]
In case you havent seen it already, they finally gave a [small statement](https://myanimelist.net/forum/?topicid=1731860). The most important message from one of the moderators is the following 

> Rest assured, we will absolutely provide a new API everyone can use, but I can’t speak to a release time yet (though it is most definitely in a beta phase.)

**Comment by Drutol** [comment]
Thanks, believe me I know all there's to know right now though. ^^
I'm following the case pretty intensively.

**Comment by Code027** [comment]
Since MAL is pretty much a big mess right now, is there a possibility of switching the app to AniList?

**Comment by Drutol** [comment]
Yes there is, I don't have time for this right now. If situation doesn't change by the end of June I'll port it in July.

**Comment by Drutol** [comment]
I've pushed quick workaround version to Google Play store. Not everything works but should be usable. Reinstall advised.
