### ISSUE TITLE
why not add anilist?

### ISSUE THREAD

**Issue by Zocex** [Drutol/MALClient#212]
this is the best apps out there to browse an anime site. i would like to have similar app like this for anilist. do u plan to add anilist next to mal here?

**Comment by Code027** [comment]
There's a possibility of it if there's still no new API for MAL. KInda not seeing the API showing anytime soon since their devs are busy on the site maintenance.

**Comment by Drutol** [comment]
The main problem with switching to AniList is that I'd have to remove a bunch of MAL specific features like forums. You may ask why just not add list stuff... well the code in here is pretty ancient and hard to modify.

For the time being I fixed the app without having access to MAL's API. Final decisions in July.
