### ISSUE TITLE
Workaround version not working on android

### ISSUE THREAD

**Issue by LuacsDev** [Drutol/MALClient#213]
My list doesn't load and when I try to reload the app crashes

**Comment by Drutol** [comment]
Did you reinstall or sign in again with new credentials?

**Comment by LuacsDev** [comment]
Yup, I reinstalled twice, same problem

**Comment by LuacsDev** [comment]
https://i.imgur.com/hbRGNrW.jpg
It never loads so I close the app, open it again and try to refresh my watching list, that's when the app crashes

**Comment by Drutol** [comment]
Okay... I found something that may cause issues. Next version should be up within minutes on gplay.

**Comment by LuacsDev** [comment]
It's working now, thanks!
