### ISSUE TITLE
My start and end

### ISSUE THREAD

**Issue by HentaiOusams** [Drutol/MALClient#215]
### System

* MALClient Version: `1.4.1.0` 
* Platform: `Android 7.1`

### Description

After release of work around version, our my start and my end dates are not being saved on MAL servers. I go to site and my start and my end are not filled. Even after refreshing the page in app, the dates will disappear. Please fix it. 

Thanks a lot!

**Comment by Drutol** [comment]
Hello, as I have noted in change-log a few times, start and end dates are not working currently. Getting them to work requires a lot of trickery and I didn't have time to tackle them. No ETA yet, sorry!

**Comment by HentaiOusams** [comment]
Oh okay. Thanks for info. Cuz on the site we are still able to set our start and end dates and I'm the app, it fetches the dates that have already been set so i thought that part got forgotten while releasing the temporary version.
