### ISSUE TITLE
Where can find Windows Aplication?

### ISSUE THREAD

**Issue by Yari27** [Drutol/MALClient#219]
### System

* MALClient Version: `5.4.4.0`
* Platform: `UWP`

### Description
The store can not find the application and the link below is the message below:

> We are sorry, the page you requested cannot be found.
> The URL may be misspelled or the page you're looking for is no longer available.

**Comment by Drutol** [comment]
I'm currently fighting with MSFT to get it back on the store. They found some "certification issues"...

**Comment by 41x3n** [comment]
Man, I was freaking out too. I have the app installed but it's not working properly, thought of reinstalling then found out that it has been unpublished.

**Comment by Drutol** [comment]
I'm waiting 2nd day for their response now. I've been mailing with them for like 2 weeks already.
