### ISSUE TITLE
No longer support for RS1 build?

### ISSUE THREAD

**Issue by hohoaisan** [Drutol/MALClient#223]
After MAL Dev Team had a big server fixing months ago, MALClient stopped working till now and few days ago i rechecked on MS Store and you had updated the logo and the app requires 16299 as the lowest build, so if i uninstall MALClient for now i will not be able to install it again.
So please resupport for lower build.

(My English is not good, sorry for any mistakes)

**Comment by Drutol** [comment]
Sorry but because of architectural change I'm unable to go any lower :(

https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/
