### ISSUE TITLE
Search area comes up blank

### ISSUE THREAD

**Issue by DavidG72** [Drutol/MALClient#228]
### System

* MALClient Version: `M.m.r.p` 
* Platform: `Android|UWP`

### Description

When I search for a title (any) it comes up blank. I even tried one I already have completed. Can some one help?

David

**Comment by DavidG72** [comment]
No worries now. Uninstalled and then installed and it now works. Thank you anyways for this forum.
David

**Comment by Drutol** [comment]
Hello there I'm guessing it was short outage of 3rd party API providing some data. Thanks for reporting either way :)
