### ISSUE TITLE
I have a problem with adding "Masamune-kun no Revenge" in my entries.

### ISSUE THREAD

**Issue by AndrewFreak** [Drutol/MALClient#231]
### System

* MALClient Version: `M.m.r.p` 
* Platform: `Android|UWP`

### Description

	
So, I've been trying to add tha anime in my entries and the icon justo load, but doesn't do anything. Can you check that? Is (I guess) the only one that causes me that problem. Thanks anyway, the app is great!

**Comment by Drutol** [comment]
Hello, hmm... it works for me.

MAL can be doing some strange things on its part... can you try maybe signing in again/reinstalling the app?

**Comment by AndrewFreak** [comment]
Oh, re signing up work... Thanks xd

**Comment by Drutol** [comment]
Yeah, sorry. I can't guarantee any stability with MAL right now :(

We have to wait for proper API...
