### ISSUE TITLE
Bug: completed set number of chapters into number of volumes

### ISSUE THREAD

**Issue by matthieu-vergne** [Drutol/MALClient#254]
# Context

MALClient 1.4.15.0

When finishing a manga, I set its status at completed. The app then suggests to set the volumes read to the last volume.

# Problem

It actually use the number of chapters to set the number of volumes. For instance, I just finished a manga of 63 chapters & 11 volumes, and it suggested me to set it at 63 volumes read instead of 11 volumes.

**Comment by Drutol** [comment]
Thanks, fixed :)

**Comment by matthieu-vergne** [comment]
Thank you.

It seems that the releases available here do not match the Android version (still 1.1.0.0 here)
On which version will be the fix for Android?
