### ISSUE TITLE
ISwipeListener error when building for Android

### ISSUE THREAD

**Issue by gitfib** [Drutol/MALClient#257]
### System

* MALClient Commit: 7224a94d03ecddb9d75cc3602dfa5b9b8e106940
* Platform: `Android`

### Description

	
I'm trying to build this app for AndroidDebug ARM, but I'm getting these errors:

`\MALClient\MALClient.Android\AndroidBindings\Binding_SwipeLayout\Additions\SwipeLayout.cs(7,47,7,61): error CS0426: The type name 'ISwipeListener' does not exist in the type 'SwipeLayout'`

`\MALClient\MALClient.Android\AndroidBindings\Binding_SwipeLayout\Additions\SwipeLayout.cs(5,48,5,62): error CS0426: The type name 'ISwipeListener' does not exist in the type 'SwipeLayout'`

From online search I guess ISwipeListener is a Xamarin thing, but I couldn't find it in the original [AndroidSwipeLayout](https://github.com/daimajia/AndroidSwipeLayout).
I haven't installed UWP's SDK.

How can I resolve these errors?

**Comment by Drutol** [comment]
Hello, these are some peculiar binding issues.

You just have to comment this code out, build the binding, uncomment the code and build again.
`Binding_SwipeLayout/Additions/SwipeLayout.cs`
```
public partial class SwipeLayout
    {
        private Com.Daimajia.Swipe.SwipeLayout.ISwipeListener _swipeListener;

        public Com.Daimajia.Swipe.SwipeLayout.ISwipeListener SwipeListener
        {
            get { return _swipeListener; }
            set
            {
                if (_swipeListener != null)
                    RemoveSwipeListener(_swipeListener);

                _swipeListener = value;
                AddSwipeListener(_swipeListener);
            }
        }
    }
```

It's just a little addition to simplify having only one listener.
