### ISSUE TITLE
Sort By Rating

### ISSUE THREAD

**Issue by 123tris** [Drutol/MALClient#258]
One thing which bothered me on the actual website of MAL was that you can't sort your "plan to watch" list by score (the average score from user votes, aka rating). I noticed that MALClient doesn't have this functionality either. So it would be nice if a "rating" sort would be added. I don't mind programming that myself and sending a pull request, I just want to know if it would be allowed or not before I do anything.

**Comment by Drutol** [comment]
The problem is that MAL does not return global score for anime on your list. So It's not really possible to do in a feasible way.

**Comment by 123tris** [comment]
I'm aware, I once programmed a small console printing the list out for myself and I ended up having to query the individual anime's from the user's list and then grab the score from there. Even when doing asynchronously it ended up taking pretty long.

So yea it is a hassle. Unfortunately, I can't find my test code but I might make a test using HTTP requests since I believe the API does contain the anime ID which you can then use to get the HTML data which might be faster than querying it through the API.
