### ISSUE TITLE
Wrong value of chapters when changing Manga to "completed". 

### ISSUE THREAD

**Issue by AndrzejBaran** [Drutol/MALClient#263]
### System

* MALClient Version: `1.5.1.3`
* Platform: `Android`

### Description

When I'm changing state of Manga from "reading" to "completed" I'm getting a question if I want to change the number of read chapters to number of all the volumes, not chapters. Example: manga has 120 chapters, and 9 volumes. When changed to "completed" it asks if I want to change "read chapters" to 9 instead of 120. 

### Screenshots

![Screenshot_20190628-113358](https://user-images.githubusercontent.com/29891264/60333603-c07d6480-9999-11e9-89bd-a88776c6103a.jpg)
![Screenshot_20190628-112825](https://user-images.githubusercontent.com/29891264/60333619-cd9a5380-9999-11e9-97d5-d1a59ac149fd.jpg)

### Steps to reproduce

1. Set any manga, with known number of chapters and volumes, to "reading" 
2. Change state of that manga to "completed"
3. The pop-up asks to change number of "read chapters" to number of all volumes.

**Comment by Drutol** [comment]
Thanks! Fixed :)
