### ISSUE TITLE
Feature : Share manga progress by volume instead of chapters

### ISSUE THREAD

**Issue by Gyoo** [Drutol/MALClient#266]
Android app : When I update a manga by adding a new read volume, the Share button shows up.
If I click on it and want to share on Twitter for instance, the pre-generated message is always "I just read the Xth **chapter** of XXX"

Would it be possible to add a setting to share the volume progression instead of the chapter progression ?

**Comment by Drutol** [comment]
Yeah, should be possible I'll look into it.

**Comment by Drutol** [comment]
Should be changed in 6cd88fc. I'll be posting beta on discord the week probably ^^
Release this weekend or next week depends on how it goes.
