### ISSUE TITLE
I am having problems searching for content

### ISSUE THREAD

**Issue by sesshoth** [Drutol/MALClient#273]
Reporting a bug?
----------------
### System

* MALClient Version: `5.5.9.0`
* Platform: `UWP`
-->

### Description

 So ever since several days ago, I have been having an issue with any searches that I try to make. I type everything from the full name of a show in english or japanese to just letters, and all that it is saying now is: No data from MAL try searching for something more specific :)
So I don't know if it was from an update or just some issue with recieving information from the server. I also don't know if this is an issue only I am having or if others are having it too. I have tried uninstalling the program and reinstalling it but nothing had changed.

**Comment by Drutol** [comment]
Hmm, it's been a while since last UWP mainteance... I'll check up on it

**Comment by sesshoth** [comment]
Thanks

**Comment by bashenk** [comment]
Same issue for me as well.
![image](https://user-images.githubusercontent.com/40068887/63899986-fc9a6900-c9cc-11e9-9a8f-b3b37b8013a4.png)
That is what I get when making a general search. 

Also, and likely relatedly, the details pane has been quirky. That is, some of the components will load while others will remain what they were from the previous item, but in many ways feels like it's caught waiting on something. For example:
![image](https://user-images.githubusercontent.com/40068887/63900141-98c47000-c9cd-11e9-9a5e-39ebc56dfeec.png)

**Comment by bashenk** [comment]
So far so good for me on 5.5.10.0

**Comment by getBoolean** [comment]
Thanks, it is working again.

version: 5.5.10.0

**Comment by Drutol** [comment]
:)
