### ISSUE TITLE
Issue with MALClient - Broken search function

### ISSUE THREAD

**Issue by KCV316** [Drutol/MALClient#274]
* MALClient Version: 5.5.9.0
* Platform: Windows 10

Hi.

Recently, the app refused to find any results when i searched for various anime. simply got the message "No data received from MAL, try searching for something more specific". I've tried many obvious titles, but nothing shows up. the anime list shows all that i've already added, and the seasonal anime list loads fine, but the searching function is completely broken. Also, every time i click on an anime to either update episodes watched or whatever, it never loads properly, instead it's all just question marks. So, is there an update to fix this or do i maybe have to reinstall?

**Comment by Drutol** [comment]
Hmm, that's pretty weird. `5.5.9.0` should fix just that. 
Could you please try running Fiddler https://www.telerik.com/fiddler and send a screenshot of internet traffic going on?

**Comment by getBoolean** [comment]
MALClient Version: 5.5.10.0
Platform: Windows 10

Hi, my search is working fine with the recent update `5.5.10.0`, try checking the Microsoft Store for an update. I believe it was broken on `5.5.9.0`.

**Comment by Drutol** [comment]
Yeah right, my bad. It's `5.5.10.0` _teehee_

**Comment by KCV316** [comment]
> 
> 
> MALClient Version: 5.5.10.0
> Platform: Windows 10
> 
> Hi, my search is working fine with the recent update `5.5.10.0`, try checking the Microsoft Store for an update. I believe it was broken on `5.5.9.0`.

Nothing happens when i press update in the microsoft store... it says on the app page that there's a new update, but nothing ever loads when i try to install it. any ideas?

**Comment by KCV316** [comment]
> 
> 
> Hmm, that's pretty weird. `5.5.9.0` should fix just that.
> Could you please try running Fiddler https://www.telerik.com/fiddler and send a screenshot of internet traffic going on?

So how do i use this fancy software? i have downloaded now. do i just open and send screenshot of the starting screen, because i don't anything that could relate to traffic on that screen. Or what do i press?

**Comment by Drutol** [comment]
You have to update. Telerik will tell me nothing new since the bug has been already fixed.

**Comment by KCV316** [comment]
Ye i would update it, if i could. But as i replied to the other guy, literally nothing happens when i press update. Any ideas?

Also, pardon the late responses.

**Comment by Drutol** [comment]
Is your windows up to date?

**Comment by KCV316** [comment]
ye, it updates automatically

**Comment by Drutol** [comment]
Odd, well... you can download new version from this issue https://github.com/Drutol/MALClient/issues/275

**Comment by KCV316** [comment]
it was a big mess and some trouble figuring out how to do that, but it seems to have worked. app is now 5.5.10.0, and searching is back to normal. Thanks for the support and help!
