### ISSUE TITLE
MALClient Issue: Crash after swiping to increment/decrement a grid item

### ISSUE THREAD

**Issue by getBoolean** [Drutol/MALClient#275]
### System

* MALClient Version: `5.5.10.0` 
* Platform: `Windows 10|UWP`

### Description

	
Hey,

I am experiencing a crash when I try to swipe left or right on a grid item to increment or decrement the watched episodes. 
This is with the option in settings "Enable swipe to increment/decrement on grid items" enabled. It does not crash with this setting disabled.

Thanks

**Comment by sesshoth** [comment]
I am having this issue too

**Comment by Drutol** [comment]
Ugh, looks like release builds of UWP are acting up again :(
_Works for me locally but I can imagine what's up with it_

**Comment by Natsuki-Yume** [comment]
Me too and it's not only if I want to swipe it, if I accidentally click an anime and sightly turn to left or right it crashes (Like when I open the anime details). It forces me to increment chapters through the sub-menu. I think there should be a way to make it more simple, maybe not to swipe left or right but just two small buttons with "+" and "-" on the corner of each anime or something like that.

**Comment by Drutol** [comment]
I'll clean build it and provide link here so you can check if issue is gone.

**Comment by Drutol** [comment]
https://install.appcenter.ms/users/drutol/apps/malclient-01/distribution_groups/public

Please check this one :)

**Comment by getBoolean** [comment]
It just says "This app is already installed."

**Comment by Drutol** [comment]
You have to uninstall the current one.

**Comment by getBoolean** [comment]
Ok I uninstalled it and tried to install that file but I got this error message:

> MALClient installation failed
Reason:
Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by Drutol** [comment]
Ugh, I figured it would sign it properly since it's store release... I'll send you whole package then once I'm back home.

**Comment by Drutol** [comment]
[MALClient.UWP.Desktop_5.5.10.0_Test - Copy.zip](https://github.com/Drutol/MALClient/files/3591618/MALClient.UWP.Desktop_5.5.10.0_Test.-.Copy.zip)

Put the appxbundle file inside and run the powershell script. Should work.

**Comment by getBoolean** [comment]
> [MALClient.UWP.Desktop_5.5.10.0_Test - Copy.zip](https://github.com/Drutol/MALClient/files/3591618/MALClient.UWP.Desktop_5.5.10.0_Test.-.Copy.zip)
> 
> Put the appxbundle file inside and run the powershell script. Should work.

Okay, it installed. It does not crash anymore when swiping

**Comment by Drutol** [comment]
Heh, it's just a rebuilt version without any changes. Nice one MSFT ^^

**Comment by Drutol** [comment]
Released update to certification with a fix.
