### ISSUE TITLE
plans for F-Droid?

### ISSUE THREAD

**Issue by Soundtoxin** [Drutol/MALClient#276]
Are there plans to add this app to F-Droid? I see that it's GPLv3. I don't use google apps or the play store on most of my devices, but I tried this app out and it works well. It would be nice to get it from F-Droid instead.

**Comment by Drutol** [comment]
Unfortunately they are too restictive about building the app. They don't want VS to build it and using anything besides it is just counter productive. So the answer is no...

**Comment by Soundtoxin** [comment]
Do you mean VS Code or the older Visual Studio? If VS Code, you could probably use VS Codium (same software but built without some nasty bits). Also, where can I see that restriction you mention?

**Comment by Drutol** [comment]
"Older" Visual Studio. Neither is "older", both serve very different purposes and building this solution in VsCode is not feasible.
I did check that rules years ago so they may have changed since then.
