### ISSUE TITLE
Missing icon in App Info / App List (inside android settings)

### ISSUE THREAD

**Issue by Zaczero** [Drutol/MALClient#284]
### System

* MALClient Version: `1.5.4.6` 
* Platform: `Android`

### Description

The app icon inside application info is missing *(same for application list)*. **It shows fine in the launcher**. This bug is only visible inside the settings app.

![photo_2020-04-16_01-25-53](https://user-images.githubusercontent.com/10835147/79398546-3aaac400-7f81-11ea-903a-ed565776cf27.jpg)

**Comment by Drutol** [comment]
Ouch, will check what's up.

**Comment by Drutol** [comment]
Fixed
