### ISSUE TITLE
got signed out somehow, can't log in anymore

### ISSUE THREAD

**Issue by Soundtoxin** [Drutol/MALClient#299]
### System

* MALClient Version: `1.5.4.20.128` 
* Platform: `Android`

### Description

I'm not sure what happened, but I went to open the app and I was at the login screen. When I try to log back in, it says "Authorization failed. Unabled to authorize with provided credentials. If problem persists please try to sign-in on website."
I am still able to sign in elsewhere (a web browser on my computerwhere I wasn't logged in yet), my credentials are correct.

**Comment by strike-the-blood** [comment]
me too... plz help
but i use windows 10

**Comment by Renzo904** [comment]
Are you guys did try to use the new pre-release? Now it redirects to the login page of my anime list instead of login in the app

**Comment by Soundtoxin** [comment]
I first had the issue on an older version, then updated in hopes of fixing it. I don't think I'm using a pre-release.
edit: oh, there's another update now. I just updated and I can log in again!

Closing issue.

**Comment by strike-the-blood** [comment]
the version is 5.5.16.0
app: MALClient [windows 10]
and couldn't login
