### ISSUE TITLE
UWP windows 5.5.16.0 login issue

### ISSUE THREAD

**Issue by harukenji** [Drutol/MALClient#300]
### System

* MALClient Version: `5.5.16.0` 
* Platform: |UWP

### Description
for some reason having the latest version doesn't resolved the login issue. :(

**Comment by GitExploraa** [comment]
contrary to the Android version ,the Windows one hasnt been updated yet ,so the problem is still there ,need to be updated asap please

**Comment by harukenji** [comment]
5.5.17 fixed the login issue.
