### ISSUE TITLE
Mal is not available at Playstore anymore

### ISSUE THREAD

**Issue by Blackklegend** [Drutol/MALClient#323]
I kinda wanted to know what happened because I can't find it in Playstore anymore and the version available here at GitHub is way too old. Sorry if this isn't the right repository but I just wanted to know what happened. Thanks in advance!

**Comment by ThePharaohArt** [comment]
i can see it's still available on the playstore, the playstore version is 1.5.11.0

**Comment by Blackklegend** [comment]
yeah, it came back later, but thanks
