### ISSUE TITLE
MAL Https fix is in certification....

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#48]
## MAL Has gone https... stuff IS broken, will be unbroken in next update...

**Comment by ZeroOmar** [comment]
*radio static* Over.

**Comment by Mordonus** [comment]
Apparently they are going to do this later...

**Comment by Amrykid** [comment]
How have they acquired the ability to postpone an earthquake?!?!?

![img](http://cdn.smosh.com/sites/default/files/ftpuploads/bloguploads/movie-quote-meme-sparta.jpeg)

**Comment by Drutol** [comment]
Fortunately they didn't change too much with https, everything is working on my end now, I'll submit update in an hour or so.

**Comment by Drutol** [comment]
Update is in certification all is in Microsoft's hands
