### ISSUE TITLE
[4.4.27.0] issues/gripes

### ISSUE THREAD

**Issue by Kimod** [Drutol/MALClient#49]
**4.4.23.0 stuff**
* White theme log in page - http://puu.sh/qHf10.jpg
 * :heavy_check_mark: Fixed
* We should be able to copy names of characters and voice actreses
 * :heavy_check_mark:  True
* Favorite button inconsistency - http://puu.sh/qHgIq.jpg (more visible on white theme)
 * :heavy_check_mark: I think I've dealt with all theme inconsistencies. And on the staff page there were 2 favourite buttons... somehow...
* In profile, when you had anime opened and you click on character, wrong back arrow appears - http://puu.sh/qHmQ8.gif
 * :heavy_check_mark: Should work properly now
* When you click on voice actor through character, then on anime and then on back arrow, it skips the voice actor - http://puu.sh/qHmRJ.gif
 * :white_flower: Because of how everything is implemented this will take some time so I'll skip it for now. (It'll happen if you navigate from character to anime too)
* If I click on manga, it doesn't create back arrow to the character that appears in it - http://puu.sh/qHmUk.gif
 * :heavy_check_mark: Fixed
* If you click and drag, it doesn't select that character - http://puu.sh/qHmWp.gif
 * :white_flower: Are you some kind of QA Tester irl or something? I made it behave this way because different issue cropped up and I think I can live with this drag click bug :D
* When you click on different character in profile, it doesn't create that back arrow - http://puu.sh/qHmY1.gif
 * :heavy_check_mark: Fixed
* "Website" is useless on every voice actor I found, it's shortened (with ... at the end), just like on mal website, so there is probably almost nothing you can do about this?
 * :white_flower: I can always hide it :D
* When you made it so +/- doesn't take up space when they are not needed caused index number to jump all over place - http://puu.sh/qHnns.png
 * :heavy_check_mark: Moved this section to the left altogether
* Since we have open in browser in Anime details, could you add this to characters/voice actors? ^^
 * :heavy_check_mark: Added
* Show the type of anime/manga on grid item in character details - http://puu.sh/qHmbx.png (TV, Manga, Novel)
 * :white_flower: No data, or no easily accessible data I should say.
* I want to know how many ppl have the same waifu as I have, so I would like to have Member Favorites on characters too ^^
 * :heavy_check_mark: Added, It's 0 anyway :D
* Would it be possible to add search for characters/voice actors? Or is it something beyond your power?
 * :construction: : Can do
 * I'm going to add character search only though, I don't feel like ppl are searching for staff that much.
 * :heavy_check_mark:  Done

**Two things that are still present**
* If you have subcategory in settings opened and then click on anime/manga, it does have that back arrow too - http://puu.sh/qz4iV.gif
 * :heavy_check_mark: Fixed, literally typo
 * :negative_squared_cross_mark: Still not fixed, another typo? :/
 * :checkered_flag: Not a typo, idk what happend here.
* Favorites won't load if you spend some time (I reloaded, clicked on history, went back and then again reloaded profile) in a profile without favorites - http://puu.sh/qCsyd.gif (I pointed this out because you said "Profile page will no longer show empty favourites." in your changelog :D)
 * :heavy_check_mark: Fixed
 * :negative_squared_cross_mark: Not for me, did the same things in gif in .23, you can also go to that profile through Goto, no need to go though Articles
 * :checkered_flag: Okay... now instead of using trickery with items arrangement I'm using effective yet simple bruteforce...

**And don't forget mobile ^^** (from #42)
* I can't load somebody else's history, it shows empty every time
 * :white_flower:  Cannot reproduce, maybe I have fixed this by accident.
* If you click in your "Profile" page on "Anime list" and then click back, it goes back to "Anime list", so nothing happens
 * :heavy_check_mark: It worked differently for me but it was bugged nevertheless
* Clicking back in forums main page closes the app
 * :white_flower: Cannot reproduce
* In anime search, if you clicked on a show, went back and then tried to click on it again, it doesn't go to the show details
 * :heavy_check_mark: Fixed earlier because I was fixing something eles.
* If you click on Anime stock photo in anime details the photo is in the middle verticaly, so if you are for example in reviews, it isn't visible right when you click on it, you have to scroll down and the save button is even lower
* In settings in Account if you click on back arrow, it closes the app
 * :heavy_check_mark: Fixed
* Grids in history have different widths - http://puu.sh/qBvGE.png
 * :white_flower: Work fine for me... we'll see after next build

**Comment by Drutol** [comment]
I've also discovered that some shows (newer mostly) have higher quality images if you properly modify the url, there'll be setting for high and low quality options :D

**Comment by Kimod** [comment]
Woo you are on a roll, here is a few more things ^^
* Ranked has "2" after every number http://puu.sh/qHR4B.jpg
* If season hadn't anything aired, it will show current season - http://puu.sh/qHR7F.png
* App crashes if you click on character/staff member who doesn't have picture in "Characters & Staff" in anime details - http://puu.sh/qHRYT.gif
* In manga details, "Serialization" is cut of - http://puu.sh/qHSsJ.png
* If you click on "Feedback", it still directs to "Mordonus" instead to "Drutol", I know browser will redirect you to "Drutol", but change it just in case...

**Comment by Drutol** [comment]
Here you go:

![image](https://cloud.githubusercontent.com/assets/6102530/17831699/70b381fc-66f0-11e6-8511-11c698a4c886.png)

+best grill of sakurasou because you seem to be mistaken :D

**Comment by Kimod** [comment]
no one beats autism-chan, you have to learn that blonde girls always win :3 but seriously, all sakurasou girls were god-tier ^^

**Comment by Drutol** [comment]
Ehh, I've seen this "chart" somewhere... ^^

**Comment by Drutol** [comment]
I smell crashes...

**Comment by Kimod** [comment]
* Here is your crash :p - If you click on Anime search, then on Character search, then on Anime search and so on and then eventualy click on for example Anime list, it crashes, try it with freshly open app
http://puu.sh/qIaCU.gif
* Anime search has different background than character search, it also doesn't have that fancy icon in the middle  http://puu.sh/qIabA.png (Top anime = anime search…, and don't forget manga search)
* If I click on "Character search, then on Anime List and then on Character search, it searches in the meantime - http://puu.sh/qIapR.gif
* Score and type aren't in the middle on the left and also days look a little weird next to the anime name.... http://puu.sh/qIaHw.png
* If you search for something in Character search, leave it and then come back, it doesn't clear the list - http://puu.sh/qIaT2.gif
* Ranked has "2" after every number http://puu.sh/qHR4B.jpg
 * :heavy_check_mark: Fixed
 * :negative_squared_cross_mark: nope, even if I loaded a show that I'm sure I havent loaded in .23
* In manga details, "Serialization" is cut of - http://puu.sh/qHSsJ.png
 * :heavy_check_mark: Fixed
 * :negative_squared_cross_mark: nope, still the same

**Comment by Drutol** [comment]
Wow, new images look gorgeous on phone :D

**Comment by Kimod** [comment]
Can confirm that new anime covers look gorgeous on mobile ^^
**4.4.27.0**
* If you search for something in Anime search and then go to Anime List, button for selecting type appears - http://puu.sh/qIYEk.gif
* If you click on character, that you had previously selected, you can't select the character name - http://puu.sh/qIYr9.gif
* If you click on Character search, then on Anime search, then on Anime list and then on Anime search, it searches for something - http://puu.sh/qIYuB.gif
* If you click on Character search multible times, "Search away!" watermark dissapears - http://puu.sh/qIYMn.gif
* If you search for something in Anime search and then click on Character search, it doesn't search for anything, but if you search for something in Character search and then click on something in Anime search, it searches for something - http://puu.sh/qIYYP.gif
* Is it intentional that Score in details dissapeared? http://puu.sh/qJ0ch.png

Other than those small problems, I think that those builds are pretty good release candidates ^^
On mobile, viewing somebody's history works now, but grids still have different widths (which is definitely game breaking... :D)
