### ISSUE TITLE
Logos galore!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#54]
So I had my friend do some stuff with logo in actual graphics software called photoshop which is fundamentally different than me randomly pasting .pngs into GIMP hoping that it'll look any good.

There are some of his attempts:
![pasted image at 2016_08_27 06_07 pm](https://cloud.githubusercontent.com/assets/6102530/18215744/fb88fe26-7152-11e6-8b25-737f49044cce.png)
![pasted image at 2016_08_27 06_01 pm](https://cloud.githubusercontent.com/assets/6102530/18215747/fea82546-7152-11e6-8826-88cecf943249.png)
![pasted image at 2016_08_27 06_00 pm](https://cloud.githubusercontent.com/assets/6102530/18215752/020fa6a0-7153-11e6-8279-fb68fd5604ab.png)
![malicons](https://cloud.githubusercontent.com/assets/6102530/18215753/04bd9d1c-7153-11e6-8cfe-f4b016669b13.png)
![mal](https://cloud.githubusercontent.com/assets/6102530/18216021/86be7952-7154-11e6-98ee-ed8ac2478ade.png)

Generally we've come to the conclusion to have store logo **not** in Windows accent colour in order to distinguish this app from others.

Splashscreens:
![myanimelist_blue](https://cloud.githubusercontent.com/assets/6102530/18215857/bebfaeda-7153-11e6-9d7e-cc255def2ee3.png)
![malclient_blue](https://cloud.githubusercontent.com/assets/6102530/18215854/bafeb868-7153-11e6-9230-502e0142cfed.png)
![malclientclose_blue](https://cloud.githubusercontent.com/assets/6102530/18215867/ccac674a-7153-11e6-864f-8c0e0a067df8.png)

What do you think? These are already far better than my... let's pretend I din't do a thing here :D

**Comment by keikode** [comment]
Really nice logos. They are much better than the current one.
