### ISSUE TITLE
MALClient v5!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#55]
As you probably know I've been converting solution to multiplatform one meaning I can run the same code on Windows/Android/iOS. That's why we are going upper with major version!

Essentially everything (code-wise) is in different place or is more or less altered that's why bugs can appear anywhere, I wanted to test this more but this week turned out to be pretty busy for me and that's why I upload these first v5 builds today.

There are bugfixes from #53 and that's all what's new. No new logos yet as I'm finalizing them.

x64:
https://1drv.ms/u/s!Am1xQK-HVf_IkqReMbxevbGs2XSejw
ARM: (potentially buggier)
https://1drv.ms/u/s!Am1xQK-HVf_IkqRf3_jzL2Ie46tsMA

**EDIT: iOS version is now possible**

**Comment by thepaulomalley** [comment]
The current version of v5 (5.0.1) crashes every time when attempting to open it on RS2 (14915) on a Lumia 950XL. I've installed all the dependencies and the cert and still nothing...

**Comment by Drutol** [comment]
Yeah, I did try it myself. I should be able to do some stuff today :)

**Comment by Drutol** [comment]
Even newer versions!

What's new? *New logos should be up in next version.*
Fixes from #53 
Sorting by season
Option to display show's season next to its type.
Option to automatically choose ascending/descending for sort criterium.
Added button to pull detailed info about every anime item in current set dictated by filters and such. ( "..." button in anime list)

x64 v5.0.4.0
https://1drv.ms/u/s!Am1xQK-HVf_IkqoQNAoYjq_EzGg-OA
ARM v5.0.5.0
https://1drv.ms/u/s!Am1xQK-HVf_IkqoPGdBogciVmK0I9A

**Comment by Drutol** [comment]
:tada: We have 500th commit :tada:

**Comment by Amrykid** [comment]
How's the Xamarin rewrite been treating you? I've been thinking about adding it to one of my projects.

**Comment by Drutol** [comment]
Xamarin... to be honest I didn't do much of Xamarin itself. All what I've been doing is removing windows specific stuff from shared code and this part is already behind me :) 
It was pretty boring (2k errors after moving all the files around) with lots of interfaces, IoC and changing every Visibility property into boolean one.

If I can complain about something is the actual Android API, it wasn't created with mvvm in mind and bindings are very slow and prone to be swept by GC.

Xamarin is not ideal but having ready c# codebase conquering other platforms will be much easier than writing everything from scratch in java/swift. The actual development for other platforms is scheduled to begin early October.

**Comment by Drutol** [comment]
Newestestest versions!

Whats new?

Proper image caching
#57 fixes
New splash-screen but it may change as I'm still experimenting.

x64
https://1drv.ms/u/s!Am1xQK-HVf_IkrROXswfXKDmDcVl9A
ARM
https://1drv.ms/u/s!Am1xQK-HVf_IkrRPPYsJCXGBQNmcig

I'm sorry that it takes sooo long with this update but I'm quite busy irl :(
I'll do my best to push this update to the store this week.

**Comment by Drutol** [comment]
Changelog draft:
```
17.09.2016 v5.0.11 & v5.0.10.0

Colossal code change therefore v5!
Added image proper image caching.
Added sorting by season.
Added new logos.
Added option to automatically choose sort order (asc/desc).
Added option to display show's season.
Added pulling detailed data about every anime in current list.
Fixed multitude of issues with synopsis.
Fixed calendar start tab issues.
Resolved various issues with mix between chapters/volumes.
Fixed images in manga recommendations.
Fixed unclickable buttons iintroduced after AU upgrade.
Fixed sorting button visibility in seasonal anime.
Sorting by score will now do sub-sort by title.
Fixed forum pin post bug (more on forums in next updates).
Fixed offline crashes.
Tweaked show score display.
Update anime requests are now bound to be executed in proper order.
Unified  show cover downloading.
Mobile hamburger's anime/manga list buttons now have quick access to filters.
```
