### ISSUE TITLE
[Bugs] Another list with new bugs

### ISSUE THREAD

**Issue by Kimod** [Drutol/MALClient#57]
**Synopsis**
* When in synopsis is [Written by MAL Rewrite], there is an extra line at the end and "[Written by MAL Rewrite]" is nowhere to be found, is it intentional that you are deleting "["and things in them"]" - http://puu.sh/r6MXQ.jpg and while I'm at it, do you plan to delete (source in normal brackets) too, or is deleting source in this brackets [] unintentional?
 * :white_flower: This data is from API response and not from HTML. I'm displaying what I get from this xml (which is often unparsable). I'm using Regex to remove BBcodes from this string(yes... BBcodes) and source is treated as bbcode.
* When there aren't synopsis, there is nothing - http://puu.sh/r6Npi.jpg
 * :heavy_check_mark: Fixed
* "Weiß" is "Weiszlig;" in app - http://puu.sh/r6Q9p.jpg
 * :heavy_check_mark: Fixed
* "ChäoS;Child" is "Chauml;oS;Child" in app - http://puu.sh/r6Oco.jpg
 * :heavy_check_mark: Fixed
* "Glühen" is "Gluuml;hen" in app - http://puu.sh/r6Q6v.jpg
 * :heavy_check_mark: Fixed
* didn't found any ö and ë, but it is probably "ouml;" and "euml;"
 * :heavy_check_mark: auml buml cuml vuml buml numl.... xd

**New stuff**
* Manga still uses old parsing for titles? - http://puu.sh/r6Qk6.jpg (or something like that? I don't know what am I saying)
 * :white_flower:  It's not about being manga or not. MAL sends unparsable data and I have to remove "&" symbol from it. If I have a source of title which is 100% good (like from anime list) I'm using it for title instead of one from details data. If you add this manga, restart the app and navigate there again you will see "&" in title.
* Shows that doesn't have Score - http://puu.sh/r6OpJ.jpg have score in details - http://puu.sh/r6Orq.jpg , could you remove that (scored by blah blah..?
 * :heavy_check_mark: Fixed
* Should I consider this as a feature? - http://puu.sh/r6QyD.gif and while we are at it, couldn't you just say Volumes instead of Chapters? Because you can't pull the number of chapters in Top Manga?
 * :heavy_check_mark: Fixed, and yes, this is a feature.
* When I click on '+' button on a show that I have in PTW multiple times, it will summon dialog asking to move it to Watching multiple times - http://puu.sh/r6QOf.gif (it will also happen in other places than PTW -> Watching, like in On-hold -> Watching or Dropped -> Watching and even Watching -> Completed)
 * :heavy_check_mark: Should no longer happen.
* When I'm in someone's Anime List and click on Calendar, it will show theirs calendar - http://puu.sh/r6Rni.gif (now that I think about this, is this a feature? I was certainly confused when I discovered this...) happens only if you haven't clicked on Calendar before, so test this after fresh restart
 * :white_flower:  ![71637832](https://cloud.githubusercontent.com/assets/6102530/18415570/48c32892-77f7-11e6-923d-3454d6f342fe.jpg) The code lives on its own. I'll leave this be because it would be pretty complicated to fix.
* So you added this auto descending/ascending thing, but when it automaticly descends, it will not check descending in that shorthing flyout - http://puu.sh/r6RGX.gif So you have to click on descending 2 times before the list will ascend
 * :heavy_check_mark:  Because who needs this ancient button anymore? Fixed...
* http://puu.sh/r6S7X.jpg - When you click on '+' too quickly, it will sometimes send data to MAL in different order. This is a problem, because in history you can see I have 6 eps watched, but to MAL it was send 3 > 5 > 6 > 4 and for some reason it left my "Watched episodes" on not 6 or 4, but on 5... And please don't add cooldown/loading on '+' button, I love spamming it ^^
 * :heavy_check_mark: Fixed(hopefully), no cooldown,no loading but semaphore!
* When you click on magnifier in anime list, type into it something and then click on Calendar/Recommendations (or other things that doesn't have search bar), it will have "Calendar/(different) Title" - http://puu.sh/r6Swr.gif
 * :heavy_check_mark: Fixed
* http://puu.sh/r6SKl.png - Don't have that scrollbar in Recent Manga Discussion and just let it higher than other
 * :white_flower:  Forums aren't finished and I'll come back to them later. I'm aware that these things down there are quite ugly.
* I feel like you could fit OVA/ONA in here - http://puu.sh/r6TKJ.png
 * :heavy_check_mark: Who knows?
* If you click on '...' on grid item in Anime list it opens that right thingy, but if you click on it in Profile, it doesn't open it - http://puu.sh/r6Ugr.gif So have it act like in Profile?
 * :heavy_check_mark: Fixed.
* Date on a comment and the actual comment are way too close - http://puu.sh/r6UyJ.png
 * :heavy_check_mark: Fixed
* Character grids without picture have smaller width, which is equal to their name - http://puu.sh/r8LtB.jpg
 * :heavy_check_mark: Fixed
* "Register!"s in Account are swapped, so if you click on Register! In MyAnimeList tab, it will link to humming bird and if you click on Register! In Hummingbird tab, it will link to MyAnimeList
 * :heavy_check_mark: Fixed
* If you will load all details, then on the second load, it won't start from zero, but from the number the first finished - http://puu.sh/r8SIi.gif
 * :heavy_check_mark: Fixed
* So if I have loaded all details, couldn't you then use the scores to be automatically loaded into the list without clicking on the show itself? - http://puu.sh/r8SV0.gif
 * :heavy_check_mark: im dumb
 * shh bby is ok
* When I click on pinned topic on homepage of Forums and then go back with that back button, it goes through an empty list - http://puu.sh/qwuqn.gif
 * :heavy_check_mark: Seems to fixed magically too...
 * :negative_squared_cross_mark: I don't know why I didn't point this out earlier, but this isn't fixed for me
* Why :'( - http://puu.sh/r21br.png please, move the scrollbar in calendar 2 pixels to the right >_<
 * :heavy_check_mark:  Did you really count these pixels or did dig for "2" in code? Yes it was off by 2 pixels.
 * :negative_squared_cross_mark: Still two pixels away... No I didn't go through code, counting pixels is easy when you are putting 2 pics together ^^ (no I can't code so I can't help you... Yes, I have a lot of free time, which is apparent when I have time putting these lists together... :D Why I don't watch more anime? Because Wow legion ^^)
 * Haha, I'm hyping myself for TBC right now :D
 * Playing on free servers? Well, even I started there... Is there some nostalgic thing about TBC, or you couldn't find any other server? 
 * I'm planning to start playing when new TBC server launches (maybe December), tbh I didn't play on retail at all despite having played wow for thousands of hours on multiple servers. I somehow dislike direction of blizzard and I'm stuck with wotlk and TBC + sub is quite expensive.
 * Yup, sub is expensive, but it's ok if you can earn enough gold for Wow token. I understand your stance towards wotlk+, especialy when MoP brought pandas and WoD was total failure, but so far I'm having time of my life in Legion, can't wait for hating it because of lack of content :D  
* And also that thing with reviews remaining extended and airing days remaining displayed after they are finished airing..........
 * .............................
* "Tokyo Ghoul √A" is "Tokyo Ghoul radiac;A" in app - http://puu.sh/r6Rcr.jpg
 * :heavy_check_mark: Fixed
 * :cat2: It's "radic;" not "radiac;", I'm so sorry, my bad...
* **Crash** - sometimes when I click on profile, it will crash, I don't really know what is causing it, I'm assuming failing to load an image? Idk, here is me crashing it 2 times - http://puu.sh/rb8t3.gif http://puu.sh/rb8uz.gif 
 * :stars: See comment
* When you click on magnifier in anime list, type into it something, click on Character Search, then delete that something you just wrote, click on Anime search, Anime List and then on Anime search, it will search for something with empty search bar - http://puu.sh/r6RPH.gif (there is maybe an easier way to replicate this, but this works 100% for me, so just do this..)
 * :heavy_check_mark: I did not even go through this process, I've just put there restriction for search query to be at least 2 characters long. 
* If you are in somebody's list, click on button Go back to my list, and then click on that back button, it will skip their list - http://puu.sh/r8SE5.gif
 * :white_flower: : To be honest it works as intended, navigation mechanism was implemented *much* later in the development and I'm literally unable to add certain pages to navigation chain withou major code changes.
* In Anime search, shows with no score show 0.00 Score - http://puu.sh/raaSt.jpg (should show N/A)
 * :heavy_check_mark: 
* And in Anime List, shows with no score show nothing - http://puu.sh/raaFi.png (should show N/A, but don't add N/A for everything that doesn't have score loaded)
 * :heavy_check_mark: Fixed

**Mobile**
* You can't save anime cover art on mobile anymore
 * :heavy_check_mark: I've ditched this view on mobile and made it work the same way as in desktop, now with only one option which will try to pull higher quality image.
* When I have settings in landscape mode, I can't reach past About, because you can't scroll in Settings main page - http://puu.sh/r8Ryl.jpg
 * :heavy_check_mark: Fixed
* You can short in Seasonal anime... You can't on desktop.. I guess it works, so no problem here... But that auto descending on score doesn't work there tho
 * :heavy_check_mark: Hmm you were always supposed to be able to sort in seasonal but I forgot to set column for season selection and it was hidden behind it... adjusted sorting.
* Could you add flyout for Anime/Manga list, so I can go to different category than watching from hamburger menu?
 * :heavy_check_mark: No problem :)
* There isn't reload profile button, so for example my Recent updates was updated 5 days ago...
 * :heavy_check_mark: Fixed

**Comment by Drutol** [comment]
If you have jumped to next version please make new post, lists are getting too long and I'm getting lost in them xd

**Comment by Drutol** [comment]
As for profile crashes, could you try disabling image cache? I got reports that "url" is wrong and maybe it's causing it.

**Comment by Kimod** [comment]
Fine, I set the Enable image caching to off, cleared image chache, but it's still happening... Sure, I can move all issues that aren't resolved to this comment, the idea was that I moved all unresolved things to the bottom of that comment

**Bugs** (I'm not including stuff from forums)
* "Tokyo Ghoul √A" is "Tokyo Ghoul radiac;A" in app - http://puu.sh/r6Rcr.jpg
 * :heavy_check_mark: Fixed
 * :cat2: It's "radic;" not "radiac;", I'm so sorry, my bad...
* **Crash** - sometimes when I click on profile, it will crash, I don't really know what is causing it, I'm assuming failing to load an image? Idk, here is me crashing it 2 times - http://puu.sh/rb8t3.gif http://puu.sh/rb8uz.gif
* Scrollbar in calendar still two pixels away from the edge
* And also that thing with reviews remaining extended and airing days remaining displayed after they are finished airing..........
 * .............................

**Mobile**
* You can't save anime cover art on mobile anymore

**Comment by Drutol** [comment]
Wait a sec , we will try again with debug version.

**Comment by Drutol** [comment]
Give it a go : https://1drv.ms/u/s!Am1xQK-HVf_IkrRSiD-VHcRNnAlrTg

**Comment by Kimod** [comment]
crashed it 2 times, I hope it helps ^^

**Comment by Drutol** [comment]
I've clicked this button like 100 time but to no avail.

**Comment by Drutol** [comment]
Now we are talking:

![image](https://cloud.githubusercontent.com/assets/6102530/18524170/a125fb5a-7ab7-11e6-88e8-9b8ae41d830f.png)

**Comment by Drutol** [comment]
Update will go to store tomorrow (probably).

**Comment by Kimod** [comment]
I didn't find any new bugs, huray! Which means I can close this issue. If I will find something, I will let you know ^^ If you will need something to test, be sure to let me know ;) (or I will just continue on stalking you here :D)

**Comment by Drutol** [comment]
I'll have notifications up for testing soon ^^
