### ISSUE TITLE
loading profile 

### ISSUE THREAD

**Issue by WesleyFS** [Drutol/MALClient#59]
The profile is loading without stopping. The background seems to have loaded normally, but because of the status of loading I can't move in my profile.

MAL user: WesleyFS/Wesley2001@live.com

**Comment by Drutol** [comment]
Hi there!

I'm able to load your profile without any problems on Desktop as well as on Phone...

I'll investigate this :)

**Comment by Drutol** [comment]
It took a while but I have some clues on this odd behaviour. I hope to fix this in next update.

**Comment by Drutol** [comment]
Okay, I think I know what's going on. It is bugged only on non Anniversary Update devices because of me forgetting about tossing converter in there. Fixed.
