### ISSUE TITLE
Higher DPI icons

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#66]
In 4k display and 1080p, the icons in the taskbar and desktop looks a little blurred and of lower quality as compared to other apps' icons. Is the current app logo and icon of high dpi, or is it some other issue?
<img width="475" alt="dpi" src="https://cloud.githubusercontent.com/assets/9476430/19021083/1eefe26c-88d7-11e6-81b3-5651d6384570.PNG">

**Comment by Drutol** [comment]
Nicely spotted, I forgot to upload scaled assets here!

![image](https://cloud.githubusercontent.com/assets/6102530/19021156/bf992d70-88bb-11e6-8d2d-af9db96b34e7.png)
