### ISSUE TITLE
Too much white screen & styling issue

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#67]
While browsing the forums and I click on "search", it occupies the entire screen real estate and it is hard to go back the forum topic which I was reading. 

This becomes very problematic in monitors above 20 inches. Users with big monitors will see a huge white screen while clicking "search" to  look up some anime in the middle of forum chatting.

The reason is when users are constantly chatting in the forum, they will not want to browse away from it. In web browsers, users always have one tab open for forum and another tab for searching anime. 

<img width="952" alt="white screen" src="https://cloud.githubusercontent.com/assets/9476430/19021314/43797bc0-88dc-11e6-848a-b40a62d82f28.PNG">

Or the search area can take a portion of the screen like the "anime" window. Look at the picture below:

<img width="956" alt="search" src="https://cloud.githubusercontent.com/assets/9476430/19021347/0d13a80c-88dd-11e6-9df8-49a0d1a13a78.PNG">

**Comment by sinofanger** [comment]
There seems to be a styling issue in the forums while making use of dark theme. I think you are applying external CSS onto the web view of MAL forums right?
<img width="942" alt="error" src="https://cloud.githubusercontent.com/assets/9476430/19028155/a7e5c594-8956-11e6-8d1b-c408f9cb7b0e.PNG">

**Comment by Drutol** [comment]
Yup, I'm aware of this. I have yet to figure out how to detect creating new post.

**Comment by sinofanger** [comment]
When is the next release for the UWP you are planning? Are there any feature updates planned for this release?

On Oct 3, 2016 12:00 PM, Piotr Szymczak <notifications@github.com> wrote:

Yup, I'm aware of this. I have yet to figure out how to detect creating new post.

-

**Comment by Drutol** [comment]
Probably tomorrow I'll push update to certification. Knowing microsoft it should go live on Thursday/Friday.

**Comment by sinofanger** [comment]
Hi @Drutol 

are you planning any new features in your "to do list" ?

**Comment by Drutol** [comment]
Right now I'm planning to sleep after vectorizing this map:
![image](https://cloud.githubusercontent.com/assets/6102530/19052536/75e78972-89b7-11e6-971b-6c75bd4c0bd9.png)

"Basics  of computer graphics"... yay...

I'll be back tomorrow ^^

**Comment by Kimod** [comment]
Woah, thats cool, heh, because it's Antarctica, heh... I want to know about your life too, why do you share it with some stranger and not me? >..< or it's too late? has he replaced me? what should I do to make me special for you?... aren't bug reports enough? should I try to talk to you more? I'm not really good at talking as you can see.... I didn't want to disturb you from your busy life, so I kept my comments at minimum, but I see you are happily replying... so what should I say? hmm... That place in Fairy Tail, where you are now, does really suck, the arc from ep 125-150 is really boring, I'm not envious that you have to go through it... ok another question, what exactly is your profile picture? how was it created? I was courious since first seeing it... and would you like tsundere imouto if you could have one? bit nicer than Kirino, she was really pain... Was that enough? is this how people talk? And it's not like I like you or anything... b-baka... >..<

//I'm not crazy, but I feel like I should write it here.... just in case...

**Comment by sinofanger** [comment]
@drutol yea, I too had an option of selecting this subject as one of my.electives last semester. But I decided to go with a subject called design and analysis of composite structures. I didn't think for a mechanical engineering student, computer graphics would be helpful. 
Is the subject good? 

@kimod cool down bro. 😃

**Comment by Drutol** [comment]
@Kimod woah whoah woah. Yeah this place in fairy tail is pretty god damn boring so I took yet another break from it. The ED from these episodes is the best imo, so I have that going for me which is nice :)
Btw, do you listen to OPs/EDs? I've pretty nice collection myself (https://1drv.ms/f/s!Am1xQK-HVf_Ikt5OdOrNPf3KKftytg), do you have any?

As for my avatar... I used snipping tool to crop it out from some wallpaper :D It's just fancy rectangle.

I already have a sister so I guess I will pass on another :D Not tsundere though. And don't even get me started on this oreimo s**tshow (especially 2nd season).

@sinofanger I dont't have an option of choosing my subjects yet, it's going to include OpenGL graphics further down the line though so it has a chance of being somewhat interesting. Right now it's just clickfest in Adobe Illustrator/Photoshop.

**Comment by sinofanger** [comment]
@kimod  and @drutol sitting on a tree............... 😜

**Comment by Kimod** [comment]
@sinofanger nope, I'm still in high school.. The only thing I could talk about is that I have programming as an optimal subject, where I learn pascal, which is mainly used for learning programming. However I plan to go to some kind of IT school in the future ^^ And to your second comment, at least I don't feel as awkward as when I had the only weird comment here myself :3
@Drutol I love listening to OPs, I skip them very rarely, only if I don't find them cachy enough. However I skip almost all EDs, especialy if I'm binge watching something. I guess I don't skip EDs on airing shows, because after every ep I go to /r/anime to look at discussion about that ep and have the ED playing on the background. I don't have a colection of OPs/EDs, because I'm lazy to download them separatly :p , but I use websites like https://themes.moe or http://openings.moe/list/ , if I want to listen to something ^^

**Comment by Drutol** [comment]
Anyway, visual studio is turned on now... I'm starting to put magical characters in correct places :)

**Comment by Drutol** [comment]
Aaand it's closed, update in certification.

**Comment by Drutol** [comment]
@sinofanger  About adding things to TODO list, I want to add promotional videos and probably address this issue with searching in the smaller window, maybe social things depending on how complicated is it.

**Comment by sinofanger** [comment]
@Drutol  You can also try to add a section  called "wallpapers" for each anime series.  You can use the anime name as a tag and pull wallpapers from image hosting services. There are a lot of image hosting services for anime which provides their API. Also there is absolutely no copyrights violations associated with this, as you are just using information from other image hosting sites.

Most anime fans love anime themed wallpapers, right? :)

There is a windows desktop app, which pulls anime wallpapers (anime and non-anime) from such sites. It is called wallpapers bot: http://wallpapersbot.net/

**Comment by Drutol** [comment]
Maybe in next update? I'd say that this is low priority, but I cannot deny the appeal ^^

**Comment by sinofanger** [comment]
Well, am so angry with Microsoft now. They stopped band 2. I mean it is one of the best fitness trackers out there. I think by next year they will stop Xbox, Azure and everything. 😠
I mean they make their customers look like idiots.

**Comment by Drutol** [comment]
@sinofanger 

![gif](https://cloud.githubusercontent.com/assets/6102530/19202615/81428bfe-8cd3-11e6-9519-276752eb2555.gif)

Moving pictures! Here you go! There's still quite a few things to do with this but it works ^^.

**Comment by sinofanger** [comment]
Wow. It seems to work perfect.can I get a beta version of this. Lol, I don't want to wait till it reaches the Microsoft Store 😥

**Comment by Drutol** [comment]
No problem, but there are still a few things I have to do before giving it to anyone ^^

**Comment by sinofanger** [comment]
Is it possible to work on the opening splash screen. Right now it's black with green font color of Myanimelist client. Shall we brainstorm on redesigning it? Not too complicated, but some simple attractive design.

And is it possible to include "airing today" tab on the hamburger menu. We can pull the information from anilist. Based on the end user's time zone we can pull info from Ani list

**Comment by Drutol** [comment]
I'm artistically impaired so if you have better idea go on :)

Without MAL id or possibility of conversion we cannot do much with "airing today".

**Comment by sinofanger** [comment]
take a look at this: https://anilist.co/register
They provide anime air dates based o time zones and is already being used by some android clients like "Live chart" and "Atarashi".

Also before thinking about redesigning the splash screen, are you planning on changing the name of the app? MAL client seems good, but you also have hummingbird inside it. So, what do you think?

**Comment by sinofanger** [comment]
Ohh, ok.

For the splash screen, how about a blue background (same blue color of MAL) with just the logo of the client (in white). Simple but more attractive.. What do you think?

**Comment by Drutol** [comment]
Nah, it looks cheap in my opinion (I did try it). As the app has no leading colour we have to go with either black or white or accent colour bomb. The current splash looks pretty sleek with this deep black, I cannot switch these colours based on app theme so I went with dark because I'm using dark mode ^^. Maybe this transition from black to white annoys you?

**Comment by sinofanger** [comment]
Na, the color is fine. But the writing on the splash screen look too big. Splash screen appears for maximum 1 second and its hard to get a hold of the entire writing on the screen in that short time. So I was thinking a smaller logo would suit better. Like when you use "Windows Mail", "Windows Maps", "Groove music" etc.

**Comment by Drutol** [comment]
You may have the point as I'm usually running debug version with debugger attached so splashscreen is visibile for a few seconds...

**Comment by sinofanger** [comment]
Yup, for regular end-users the splash screen appears for 1 second in very slow systems. In powerful ultrabooks and all, splash screen comes and goes in the blink of an eye. So people will time to read anything.  That is why it is better to just use the white logo on the splash screen with black background.

**Comment by sinofanger** [comment]
Also, in your to-do-list, try to include "badge notifications". It was introduced as part of Microsoft anniversary update. I would not say this is high priority, but it looks good.
 
But the feature that would be most useful to end users is the anime wallpapers ;) Anime fans browse through lots of websites to find a wallpaper for their pc. So if they can find the wallpapers within the app itself, for an anime they are watching. Then that would be "super cool"

**Comment by Drutol** [comment]
Okay, find me wallpaper API to search by anime title. I'll squeeze search into this smaller window in the meantime.

**Comment by sinofanger** [comment]
http://konachan.com/ -> api  at https://konachan.com/help/api
http://wallpapers.cc/ -> could not find an api for this
htto://minitokyo.net
Bing Images :P

Go through all of these and see whether it is possible. And one more suggestion that came into my mind: "CORTANA INTEGRATION" lol

**Comment by Drutol** [comment]
I'm going to use this: https://danbooru.donmai.us/wiki_pages/43568
The first one you used is like 90% nsfw... xd

For me cortana doesn't exist, I don't see point of these "assistants" and I'm not going to implement this...

**Comment by sinofanger** [comment]
Lol, I did not include Danbooru because it was full of NSFW. -_- Konachan has NSFW filter, does not it?

"Cortana does not exist" :O You just broke the heart of the entire Windows 10 team in MSFT. :P

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/19213110/c8d67234-8d62-11e6-965a-911c0a15161f.png)

When you navigate from profile or forums search will be squeezed there. I'm going to add setting for this too.

**Comment by Drutol** [comment]
I got these "wallpapers" working but with this data source I cannot really do much as 70% of the time it's just random oppai. 

I'm thinking about going through subreddits with wallpapers and match tags somehow but it may be pretty limited.

**Comment by Drutol** [comment]
Yup, I'm going to search for stuff on /r/animewallpaper and /r/awwnime . There will be less images but much higher quality.

**Comment by Drutol** [comment]
@sinofanger This is the link you asked for:
https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c/app_versions/74

This build has been compiled just because so you may experience some interesting(rather not) things xd

**Comment by sinofanger** [comment]
I installed and tested it. The new search feature seems perfect. Promotional videos also seem nice. Wallpapers, if we can't find any proper source we should remove it, as 80% of the time it turns out empty. 

Or we can use Bing Images with search queries of "Large" and we can rename wallpapers as "Images from the web". If a person likes a pic, let them right click it and "Set as wallpaper".

Or another suggestion is that instead of having "Wallpapers" for each anime, we can have just have a simple option in the hamburger menu for "Wallpapers". This way we can show the users, just the most beautiful wallpapers updated in sub reddits or other sources. Still the main issue will be which wallpaper source to use? 

What do you think?

**Comment by sinofanger** [comment]
Also if possible replace the name in the splash screen with the app logo. It will look good. :D

**Comment by Drutol** [comment]
I'm finalizing this update so wallpapers are hidden now. It's going to be hard to beat this thing though:

![wp_ss_20161009_0001](https://cloud.githubusercontent.com/assets/6102530/19219840/41027288-8e1e-11e6-9bfb-b830af7d9344.png)

**Comment by sinofanger** [comment]
Question 1: Which app is that? Readit? But is not Readit a reddit client?
Question 2: Which windows phone is that?

**Comment by Drutol** [comment]
Yup, it's glorious Readit. 

Lumia 640

**Comment by sinofanger** [comment]
Cool. If you are sending new update for certification today. Then that means I can download from the store on Wednesday, right?

By the way there is a review in the Windows store by someone asking you to enable anime streaming in the app 😝😝😝😝

**Comment by Drutol** [comment]
You never know when MSFT certifies things. Sometimes it's a day sometimes it's a week.

I'm well aware of this review (and post on feedback hub) but I'll pass on that. Even if it'll be after Android and iOS release.

**Comment by sinofanger** [comment]
Ya, my suggestion is also the same. Pass on that. It is illegal and it can cause a lot of issues in the long run. 

And the reason why MSFT is so inconsistent in certification is because the person who certifies apps in Microsoft is this:

![horton_hears_who_ssd1_758_426_81_s_c1](https://cloud.githubusercontent.com/assets/9476430/19221092/d3809816-8e59-11e6-9589-7f06e9c55167.jpg)

**Comment by Drutol** [comment]
I'd say that they are hentai fans, after a few months test account was full of various 18+ shows xd

**Comment by Drutol** [comment]
```
12.09.2016 v5.0.29.0 & v5.0.28.0

Added promotional videos.
Squeezed search into off section when navigating from forum/profile. (desktop)
Fixed mobile forum posting bug.
Added "ads on demand", you can enable ads for certain period of time.
A few visual upgrades and fixes.
```

Hey I've actually done something from the actual issue first comment.

**Comment by sinofanger** [comment]
@Drutol  Yes, it is working correctly now. Good work. :)
What visual upgrades did you do?

**Comment by Drutol** [comment]
Who knows, this is the point where I toss small changes not worth mentioning in separate point.

**Comment by sinofanger** [comment]
Well. I never asked you, what are your favorite anime shows? Are u watching any ongoing series?

**Comment by Drutol** [comment]
Monogatari, Toaru Majustsu no Index/Kagaku no Railgun, Oregairu, Haruhi... there are lots of interesting shows. 

As for current season I'm giving a chance to various shows and I'll filter them later. The biggest surprise for me is giarlish number... ^^

**Comment by sinofanger** [comment]
Ohh, right now I am watching Sengoku Basara, Mob Psycho etc. As for ongoing anime I am watching DB Super, Iron blooded Orphans etc. 

Do you use any social messengers? Like WeChat or FB or anything? Thinking about adding you as a friend ^_^

**Comment by Drutol** [comment]
I did think about it... how about telegram?

**Comment by sinofanger** [comment]
I use Facebook, Kik, Snapchat, Wechat, Whatsapp. O_O Installing telegram would be too much for me

**Comment by Drutol** [comment]
Maybe Slack then? :D

**Comment by sinofanger** [comment]
@Drutol  
Can you include these "notifications" button also along with "My recent topics" near the profile picture. 

The problem is I received the notification in the notification center, saying someone quoted me in MAL forums. I accidentally dismissed it. When I wanted to access that notification again there was no way to find it and I had to visit the website.

 So can you include a notifications button, like in MAL site and  Facebook? That would be really helpful in cases where we dismiss a notification and want to see it later. You can include it in the marked area as shown in the screen shot below.

<img width="230" alt="not" src="https://cloud.githubusercontent.com/assets/9476430/19280321/efc95aa8-9002-11e6-9750-d946c5acbf57.PNG">

**Comment by Drutol** [comment]
I feel like we are running out of space in this poor hamburger.

**Comment by Kimod** [comment]
Since this thread is something like suggest what you want and it might get implemented, I'm going to throw my 2 cents in. :3 From the beggining, I disliked the bar at the bottom. I know, it's basic UWP thing that all apps on mobile use. 


![malclient](https://cloud.githubusercontent.com/assets/6088494/19282971/993078dc-8ff0-11e6-985b-9568d7a4d505.png)


This is how it could look ^^ It's based on how weather app looks on desktop. From the first sight, you might say, that it can't be as thin as it used to be before, but you know, your app wasn't really intended for small window view.

And also that search bar in weather app is colapsed if the width is too low. Just look at weather app, I think that app did the bar perfectly :D And I can understand that this isn't top priority, but just something for you to consider.... ^^

**Comment by Drutol** [comment]
Hmm, this top bar section is pure mess... that's the reason why search bar isn't on it for squeezed search page. I'll have to redo it, one day...one day... plz no

#codeFromJanuaryWhenIKnewNothing

**Comment by sinofanger** [comment]
By the way did u find a good wallpaper source other than subreddits?  Did u try pixiv?

**Comment by Drutol** [comment]
I have pixiv subreddit ^^ There's a bot there that posts top submissions everyday. I'm currently planning how to this on technical level though.

**Comment by sinofanger** [comment]
Well does reddits have rss feed? If so u can scrap the picture from it.

**Comment by Drutol** [comment]
It has json API ^^

**Comment by Drutol** [comment]
Pulling data is no problem, the way I'm going to display this/paginate/incrementally load may be challenging. Arranging these items with these strategies in mind. It's not that simple ^^

**Comment by sinofanger** [comment]
Well it's better to paginate. Don't incrementally load wallpapers. If a person wants to see wallpapers they will definitely click on the next page..

And from kimods picture, did she modify the core files and introduce that green color to the app? Because it looks really good. @drutol did u like it?

@drutol the top bar looks fine. The main problem is the side hamburger menu. I feel it should be rearranged in a way that users are not confused and at the same all necessary options are available.
You know well that majority of the end-users never even look at the settings of an app. So it's better to be better optimized right out of the box.

**Comment by Drutol** [comment]
That's why I said that I need to think it over :)

Emm...Emm... this comes from your Windows10 accent settings... The whole app changes its "tint".

Tell me how, I'm of the "yolo" design school. If you have better idea how to organise it feel free to tell me, it's good enough imo. As for settings... I believe that user should have the option to deeply customize everything(okay, most of the stuff) therefore settings are quite big ^^. The defaults are set the way I think it's optimal.

Going back to top bar. Weather app has no 2nd draggable pane, if I were to squeeze everyhting in there it'll result in cluttered mess.

**Comment by sinofanger** [comment]
Well, I will propose a new arrangement of the hamburger menu. Give me some days. Have homework for today. In mean time you get that wallpaper thing going. Pixiv wallpapers are really good.

But one issue is resolution of the images. I suggest it is better to call them "Images" rather than wallpapers, because the resolution of images from various sources will be different. Or else you will have to sort wallpapers based on image resolutions (meta info), which will be difficult to code, I guess??

**Comment by Drutol** [comment]
There's new button on hamburger already with "Images" label.

**Comment by sinofanger** [comment]
How about combining anime search, manga search and character search in to "Search". A master search area for searching anything?

**Comment by Drutol** [comment]
I did have such idea but I had no clue how to switch to the correct search later. This would get rid of 2 buttons already.

**Comment by Kimod** [comment]
@sinofanger I'm dude :p

About the top bar, as I said, the main problem would be that it takes up a lot of space up there. Keep in mind that the search bar can be colapsed in weather app, which reduces the space it takes up. And you could also move some things into ... menu, like setting watching/completed. But I understand it would introduce some new clutter issues, but I feel like it would be worth it.

About search, you could have dropdown list next to searching magnifier selecting anime, manga or characters, I don't think you should overthink it

Also I think the hamburger is fine as it is, the only think I would consider changing is the buttons next to profile, maybe just move them to a new row, I don't really know...

**Comment by sinofanger** [comment]
@Drutol  How about using the same idea as that of MAL website, on the right hand side of the expanded search bar, there will be a drop down "anime, manga, characters". This will avoid using the multiple icons inside the hamburger. Here is a quick sketch of what I am trying to convey
<img width="960" alt="sketch" src="https://cloud.githubusercontent.com/assets/9476430/19300856/2ce5fe7e-907a-11e6-94cd-b1ccaa1c622b.png">


Another suggestion to minimize hamburger clutter is to put feedback and support in the same row. Just put a love icon and a feedback icon. Everyone will understand what that is. Also when they hover over these icons, they will see "Donate" and "Feedback" anyway

And include images icon as shown below:

<img width="219" alt="capture" src="https://cloud.githubusercontent.com/assets/9476430/19301014/f523f580-907a-11e6-8e8c-db074b0540c0.PNG">

@Kimod  :O OMG I was 99% sure that you were a girl. **broken dreams** :P

**Comment by Drutol** [comment]
@Kimod  has just lost VIP status...

Due to techincal difficuilties I'd rather not change this search bar. Anywhere else is fine but not upper bar. Upper bar is taboo.

**Comment by sinofanger** [comment]
No no, I am talking about the existing search bar, not the new one.
<img width="947" alt="capture" src="https://cloud.githubusercontent.com/assets/9476430/19301437/2b593d66-907d-11e6-90b5-a9f31cc2ad4b.PNG">

**Comment by Drutol** [comment]
And yes I'm talking about this one, this is forbidden zone.

**Comment by sinofanger** [comment]
Ohh, ok. Then I think you should go ahead with @Kimod 's idea:

>  "About search, you could have dropdown list next to searching magnifier selecting anime, manga or characters, I don't think you should overthink it"

**Comment by Kimod** [comment]
Mmm, that's one tasty code :3
As I look at the last picture, couldn't you add that bar where watching, completed and on hold is and there would be Anime, manga and characters instead? That could work, right?

**Comment by sinofanger** [comment]
Or you can just have one search button in the hamburger menu. Users will search for everything there. 

Or else you can remove all search options from hamburger menu and keep it in the top menu itself and rename the placeholder text from _"Search....."_ to _"Search for anime, manga and characters"_
@Drutol

**Comment by Drutol** [comment]
![gif](https://cloud.githubusercontent.com/assets/6102530/19408559/794d37bc-92c0-11e6-9838-010290d60cd0.gif)

Anything else?

**Comment by sinofanger** [comment]
Looks pretty awesome. So you are only using sub-reddits as the source?
And please include the logo of the app in the splash screen instead of writing the name.

**Comment by Drutol** [comment]
Yup, it's easy for me to get and filter this content. If you browse through other subs I'll add them as these are all I know about.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/19410677/7c1f5e16-92f2-11e6-96d0-91d327b16bd8.png)

**Comment by sinofanger** [comment]
<img width="960" alt="issue" src="https://cloud.githubusercontent.com/assets/9476430/19410751/523dacdc-9311-11e6-92bd-26bd6a2f8b28.PNG">
when the hamburger menu is collapsed there are some minor issues like:
1) news icon is not visible
2) irregular spacing between feedback, github and profile icons. They should have the same spacing as the other icons does.
3) 2 search icons (becomes 3 if manga section is enabled)
4) we have to scroll to find the settings icon if the manga section is enabled.

These are some minor issues. If you think they need fixing, work on it. ^_^ Just my suggestion, thats all.

**Comment by Drutol** [comment]
As far as multiple search icons are concerned, I make ss-es to highlight one thing. When I made this gif there was no unified search yet ^^.
The rest is pretty valid though. (and easy to fix)

**Comment by sinofanger** [comment]
Cool. By the way, I just noticed one thing. The app does not have "Large" Live tile available. The maximum size is "wide". Is it possible to have "Large" as well?
I was thinking this "Large" live tile can show latest anime news from MAL, like the Microsoft News app. As per the latest Microsoft updates, these live tiles are interactive right?

**Comment by sinofanger** [comment]
NEW SUGGESTION: Contextual Search!!!
It would be good to right click on an anime name and search for it. This way we can search for anime recommendations and suggestions being given in the MAL Forums.
<img width="960" alt="s1" src="https://cloud.githubusercontent.com/assets/9476430/21580570/8cd44c64-d026-11e6-883e-463c756123b6.png">

**Comment by Drutol** [comment]
I don't have such power there... 99% sure. I'll check. I could probably trigger it when copying stuff though.

**Comment by sinofanger** [comment]
Ohh that is good enough. Will it be possible to replace the term "copy" with "search"? Or is that a windows system function outside the app?

This is because, when we browse the forum and going through suggestions and all, the first thing any anime or manga fan does is search for a suggestion. So a contextual search will reduce the need for typing and all. That is why I feel implementation of such a feature in any form might be helpful.

**Comment by sinofanger** [comment]
@Drutol  That was pretty quick.  It is very good..

Do one thing, if the word "copy" cannot be changed, then introduce an option in the settings panel called **"contextual search".** This is because, even though this is a very handy trick,  some users might not like it...

What do you think? I

**Comment by Drutol** [comment]
I cannot do anything with this white pop up menu. I did add option in settings though

**Comment by sinofanger** [comment]
Cool. By the way, how is your New Year coming along? 

And what happened to the person in charge of the iOS application of this client? Is there any progress?

**Comment by Drutol** [comment]
Tons of exams ahead :(

iOS... he said he'll do it before summer but I don't see that coming. I won't touch apple stuff because I could get serious disease from it... it's dead right now ^^

**Comment by sinofanger** [comment]
Ohh.... which semester are you in? Is it end semester exams?

Well, iOS is not that much important anyway. Moreover iOS has a very popular MAL client called Aozora. Android is where a decent anime client is lacking as of now.  

Coming back to the UWP app, do you have any new features in the pipeline?

**Comment by sinofanger** [comment]
Well, I say you should focus on recommendations system first. I once tried doing that a long time back, may be we can add some custom algorithm like Netflix (on a smaller scale) to make recommendations more interesting?

And once the Android APK reaches a beta phase, we can post it in MAL and ask for user feedbacks... Wat do you think?

**Comment by sinofanger** [comment]
SOME BUGS I FOUND:
(1) "My recent posts" section should be ordered according to date. Instead it is ordered according to the latest posts. The problem is, while searching for my recently made posts I see posts which I made 4 months back.

(2) Now I understand the importance of notification centre. Just now, I received 5 important notifications. I accidentally cleared them and now there is no way for me to see them at all :'(

**Comment by Drutol** [comment]
I was talking about mal's auto recommendations which were added recently, without proper database I wouldn't dare to do it on my own.

More public beta is granted, sometime in February, once I'm done with exams.

**Comment by sinofanger** [comment]
NEW SUGGESTION: Is it resource intensive to make these forum articles auto-update every 15 minutes or so? 
While watching a forum post, I have to refresh it, just like I refresh the MAL website. If you think it is intuitive nd technically possible to implement it, please do.
