### ISSUE TITLE
Posting error and refresh issue

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#68]
Hi, I encountered an error while making new posts in the forums. When I click "submit" button it takes me to MAL website post page. I was trying to make a post in the "Anime Recommendations" section. Please look into it.

<img width="915" alt="posting error" src="https://cloud.githubusercontent.com/assets/9476430/19064570/c64d0e5e-8a2b-11e6-895d-1a5eeba79fff.PNG">

**Comment by sinofanger** [comment]
About refresh - when am posting a new post and trying to keep updated with a particular forum say "anime recommendations" or "series discussion". To refresh, I have to go back to the main forum to refresh. **Can you please place a refresh button in the sub-forums as well.**
<img width="1133" alt="refresh button" src="https://cloud.githubusercontent.com/assets/9476430/19064756/dc99ac48-8a2c-11e6-90eb-f3ee8f8d1e96.PNG">

**Comment by Drutol** [comment]
This button has been already added :D

As for webpage navigation, I'm not posting on forums so I don't know to what url this thing is navigating so my system interprets it as external navigation. If you are able to give me the url I'll fix this :)

**Comment by sinofanger** [comment]
The url is the same url of the MAL post page corresponding to the sub-forum in which we are posting.

Example, if I am trying to post in the "anime recommendation" forum. When I click submit it opens the url to make the post on the same sub-forum in the browser.

Try making a post, and u will see. I can give you the url, but the url changes depending upon the sub-forum in which we are trying to post.

**Comment by Drutol** [comment]
So after creating new post it navigates to this post or the board? I've created only 2 topics back in April and Febrauary so I didn't check the urls back then ^^

**Comment by sinofanger** [comment]
It navigates to the board. The post does not get created at all. That's the biggest issue.
Means it's not possible to create a new post in a sub-forum.

I think it's better u try to make a post to recreate this bug. It will be easier to fix.

I tried making post in the anime recommendation section.

**Comment by Drutol** [comment]
I wish they had "Test" section... I'll look into it. I'm not sure whether I'll be able to fix this today.

**Comment by sinofanger** [comment]
Well. Integrating MAL forum is some thing not much people have done before. I don't think anyone has done it before. So it does pose a lot of challenges. 

You can try asking for anime recommendations and test it. But u won't have to worry. Things u post from the app does not get posted in the forum. The process gets cut off in the middle and a new website opens. I tried it around 3 times.

**Comment by Drutol** [comment]
Probably because new request is redirected to website and website doesn't have cookies. So Request is denied.

**Comment by sinofanger** [comment]
Are u using a Web view inside the app, or pulling each info from the API. It's the former right?

**Comment by Drutol** [comment]
Index and boards are natively "scrapped". Post and new topic are web view. There's no API.

**Comment by Drutol** [comment]
Would you like to help me check whether my solution works before I put this thing on the store?

**Comment by sinofanger** [comment]
Sure, How can I help?

**Comment by Drutol** [comment]
I'll send you link with version for testing :) Gimme a few minutes :)

**Comment by sinofanger** [comment]
sure, should I uninstall the one I have or will they run side by side?

**Comment by Drutol** [comment]
The new one will replace the old one

**Comment by sinofanger** [comment]
ok, no issue. Send me the link.

**Comment by Drutol** [comment]
It's uploading now

**Comment by Drutol** [comment]
https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c/app_versions/68

**Comment by Drutol** [comment]
Your quest is to create new topic ^^

**Comment by sinofanger** [comment]
It says "App not found" when I click on the link.

**Comment by Drutol** [comment]
https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c and this?

**Comment by sinofanger** [comment]
<img width="888" alt="error" src="https://cloud.githubusercontent.com/assets/9476430/19082075/40e59f7a-8a7a-11e6-85dd-273ccbd3dbf7.PNG">

**Comment by sinofanger** [comment]
Upload in onedrive or so and share. Its an executable file right?

**Comment by Drutol** [comment]
I want to try this method of publishing ^^

I did use onedrive previously

**Comment by sinofanger** [comment]
-_- Make sure the app you published has proper permissions set. I think its now in private mode.

**Comment by Drutol** [comment]
Okey, should be working now

**Comment by Drutol** [comment]
I was searching for the button :D

**Comment by sinofanger** [comment]
Yes, its working. I am downloading now.

**Comment by sinofanger** [comment]
Done. Extracted the zip file. Now what?

**Comment by Drutol** [comment]
run the PS script

**Comment by sinofanger** [comment]
Ya running. I had to enable developer mode and all. Making a forum post now

**Comment by sinofanger** [comment]
Nope, error is still there. I tried to make an article in Anim recommendation and this time, the moment i clicked on "create new topic" it got redirected to https://myanimelist.net/forum/?action=post&boardid=16

**Comment by sinofanger** [comment]
Even clicking the "preview" button takes me to the link mentioned above.

**Comment by Drutol** [comment]
Okay if there was ```?action=post``` it didn't have the right to work.

**Comment by sinofanger** [comment]
Ya, preview is not useful anways.

**Comment by Drutol** [comment]
Hah, if I'm posting somewhere I'm clicking preview like 5 times xd

**Comment by Drutol** [comment]
Any other issues before I upload next test version?

**Comment by sinofanger** [comment]
Lol, I never do that. I just read it at the end and post. 😝

**Comment by sinofanger** [comment]
Well, this is the main one and the other one is the color issue. When we make a new comment, it comes in white background which causes a mismatch with the theme of the app. I posted that pic earlier and you replied you are aware of that.

**Comment by Drutol** [comment]
Yes but I'm not able to do this now. This requires some pretty hardcore hacks which take time. I'm talking other small issues with the app ^^

**Comment by sinofanger** [comment]
Umm, let's see. Scaled icons, "when clicking search, the search screen occupies the full area of the screen  hiding whatever we were doing in forums". That's all I can find for now.

**Comment by Drutol** [comment]
Still the issue with icons?

**Comment by sinofanger** [comment]
Hmm it's fixed. I restarted the laptop. Now it's fine. What about the search box? Is it possible to be included?

**Comment by Drutol** [comment]
Nope, too much stuff not enough time.

**Comment by Drutol** [comment]
https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c/app_versions/69

**Comment by sinofanger** [comment]
Umm, I closed the lap and making bed to sleep now. I thought u were publishing on the store. So.I switched off the lap.and everything.
😭😭

**Comment by Drutol** [comment]
I wouldn't upload something broken, right... right?

**Comment by sinofanger** [comment]
Haha true. I assumed you made a post yourself in MAL. 😢

**Comment by Drutol** [comment]
w/e went to certification xd

**Comment by sinofanger** [comment]
😃😃. Cool. Did you post about this app in MAL forum?

**Comment by Drutol** [comment]
Not, yet I'll use this opportunity  to test something.

**Comment by Drutol** [comment]
Post is up ^^ And I somehow read your comment wrongly, I thought that you were talking about this update. You can find the thread in creative corner.

**Comment by sinofanger** [comment]
Cool, I think most people in MAL still make use of Windows 7. Win
