### ISSUE TITLE
Social stuff.

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#69]
I recently got an email requesting a feature allowing to share things on social media (fb/twitter).
- On start watching
- On completed

What scenarios would you like to include?

**Comment by sinofanger** [comment]
Facebook, Twitter and shareable link of MAL profile. Whatsapp and snapchat are there, but it will only come in handy for mobile users.

**Comment by Drutol** [comment]
Sorry, I have no time for this now :(
