### ISSUE TITLE
A bit about development.

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#71]
I'm afraid that the development rate will decrease quite a bit moving forward. Generally speaking I will have time to write some code only during weekends :( I'll try to release _something_ every week but no promises here.

On the bright side... I'll have usable images section!

**Comment by sinofanger** [comment]
Well, you already have a solid app. Just make sure you update it with bug fixes monthly. I think it has all features that an anime app needs.

**Comment by Drutol** [comment]
Oh well, I feel like there's tons of stuff to do and I'm not even close to finishing ^^

**Comment by sinofanger** [comment]
Tons of stuff, like....? I have this feeling that you have some big ideas inside that head of yours :O. Care to give a glimpse of your agenda for the app

**Comment by Drutol** [comment]
There's projects tab and evergrowing TODO list.
