### ISSUE TITLE
A miracle

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#72]
![image](https://cloud.githubusercontent.com/assets/6102530/19416741/f2f56eee-9398-11e6-8590-afbfad3390ce.png)

Pro snipping tool writing skillz.

**Comment by Kimod** [comment]
woaaaa cool \o/ \o/ (insert 8/8 copypasta) 👌👌👌👌 420

**Comment by sinofanger** [comment]
Well, don't worry. Windows 10 users are very low still. It will take time before app gets a lot of popularity. When you get free time, think about releasing an exe version of this app (if possible) for all the millions of windows 7 and windows vista users out there (there are still 100s of millions of them from all over the globe)

**Comment by Drutol** [comment]
Why would I have to worry? I'm celebrating that even though there was spike in sessions the app didn't crash a all that day! And this app only works on W10 and **won't** work anywhere else.
