### ISSUE TITLE
Too much load time

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#74]
Wallpapers section is taking too much time to load even in a 5mbps connection. I think the culprit is the fact that the app is downloading the wallpapers in its full resolution even for preview. It is better to download a smaller version of the image, that is what most wallpapers app in android and iOS does. Then when a user clicks on "save as", download the full resolution of the wallpaper

Is there any any way to implement this?

**Comment by Drutol** [comment]
Nope, this is not wallpaper app with dedicated wallpaper servers. Reddit thumbnails are far to small and how am I supposed to download "a bit" of an image xd? 5mbps... we are talking 512KB/s? All I can do is to add setting to download more or less wallpapers on each page.

**Comment by sinofanger** [comment]
Well, there are ways to download a bit of image, reroute it through open source image compression APIs, but that will be pain in the ass.
And 5 Mbps = around 650 KB/s download speed, that is pretty decent speed even for HD Netflix streaming.
Another option you can try is, **download images one by one (the latest image gets downloaded first).** Right now, I noticed that the app is trying to download all images at once which translates to "progress bars" in all images. If you prioritize to download the latest images first, the users will start seeing images at the top, while the others continue to load. Sequential downloading of images is not a good idea in an app.

**Comment by Drutol** [comment]
It's doable but it's gonna be painful... I can add setting to how many items are loading simultaneously which is going to be less painful.

650KB/s is pretty god damn slow, even in rural Poland I have +/- 30mbps on vdsl

**Comment by sinofanger** [comment]
Lol, Europe is every different from Australia and India. I am paying 50$ per month for 5mbps unlimited and 80$ for 8 mbps unlimited. The only place where I get high speed is in my college and work place which has around 150 mbps symmetric uplink and downlink.

**Comment by sinofanger** [comment]
Also, if I may, please include "Live tabs" like large tab, tab which shows popular wallpapers, news etc. to your "to-do-list". It would be really good.

I beg you :P 
![please](https://cloud.githubusercontent.com/assets/9476430/19548758/031a0776-96be-11e6-90ef-ad56e043309f.jpg)

**Comment by Drutol** [comment]
Just wow... $80?

I'm paying like $12 for unlimited though assymetric 80mbs but cable is not good enough for 80 so I get 30-40.

**Comment by Drutol** [comment]
Wohoho, live feeds? No thanks I'm not doing html scrapped feeds.

**Comment by sinofanger** [comment]
@Drutol  not live feed, I am not sure if it is called live feeds. I am talking about what the MSN news app shows in its live tile. Is that possible with MAL client?

**Comment by Drutol** [comment]
Live tiles?

**Comment by sinofanger** [comment]
Yes, it's not essential from functionality point of view, but that will look good in the start menu. That's all.

**Comment by Drutol** [comment]
It's not easy to make these... and development time is limited and I'm semi-hyped for it... maybe one day?

...you can always do it yourself! xd

**Comment by sinofanger** [comment]
Cool, well I would have tried myself, but right now have tons of other work which are heaping on my head. Ya, just make sure to provide an option for wallpaper loading in the next patch release. That would do ^_^

**Comment by Drutol** [comment]
I'll send you the thing with smarter wallpapers later today. I'm not sure if and how much smarter it is because images are downloading so fast xd

**Comment by Drutol** [comment]
@sinofanger 
Hey look, what's this?

![image](https://cloud.githubusercontent.com/assets/6102530/19618739/e4f29f1e-9853-11e6-9421-4693cd3dc3f2.png)

**Comment by Drutol** [comment]
Binary things are now in the binary bin.

**Comment by sinofanger** [comment]
Lol, "tiles are updated once a day", that's kinda funny. But, anyway, good work. When is the new release coming?

**Comment by Drutol** [comment]
News are not that frequent anyway and next background task would add next layer of complexity. I'm waiting for bug reports till the evening and I'm pushing update. "Weekly update" ^^

**Comment by sinofanger** [comment]
Sorry for the late reply. Well I could not find any bugs so far, other than CSS issues when making a new post. I pointed this out earlier that the new post comes in a white background and conflicts with th dark background of the app.

And why did not you include "Pin wallpapers/images" in the live tile section. I was imagining that it would be like the windows 10 reddit app in your mobile phone. Beautiful images coming to start screen. If it is difficult to code that, then no need.

**Comment by Drutol** [comment]
Yeah... I'll find something somewhen for this styling issue. Promise!

Not that it's hard but getting BG task to run somewhat decently is annoying and time consuming, so I'll skip this for now. (It's android time)

**Comment by sinofanger** [comment]
By the way, UWP enables us to port android and iOS apps to windows platform. Is there any method to port windows apps to android? Or will you be coding an android app from scratch?

**Comment by Drutol** [comment]
Wut, there's an Islandwood porting from iOS but it works **awfully**, look at FB messanger for instance.

There's no porting from UWP to <insert platform here>, **but** I've prepared this project so that majority of pure logic code can be shared accross all 3 platforms... in result I've to *just* write View layer.

**Comment by sinofanger** [comment]
Wow 😨😨😨😨 u implemented live tiles? 😨😨😨😨

**Comment by Drutol** [comment]
Yeees?

**Comment by sinofanger** [comment]
In the app, where else? By the way is there a large live tile now? 😰

**Comment by Drutol** [comment]
Yes there's large tile. I was thinking that you thought about android xd

**Comment by sinofanger** [comment]
No not android. By the way how's android development coming along?

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/19715514/02dc9d72-9b56-11e6-9078-1732f2e5d001.png)

I'll start this weekend. Maybe in 2 months I'll have something worthy of calling an app. I'll try to share as much progress as I can but it's gona be rough ride.

**Comment by sinofanger** [comment]
hey, by the way, I just updated to the latest version. When you right click an image in the "images" section the context box opens somewhere else. Try right clicking an image in wallpapers section and you will see. In the below screenshot, I right clicked on the Saber picture and the context box opened on the left hand side.
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/9476430/19717908/7e46d0ca-9b80-11e6-9d9e-8ecf4df2eddf.png">

**Comment by Kimod** [comment]
That's because you're on low resolution screen, if the context box can, it will expand downwards, if it can't, it will expand to the side. I don't really view this as an issue ^^

**Comment by Drutol** [comment]
@Kimod you are a godsend. I can do like **nothing** *(almost)* about it ^^

**Comment by sinofanger** [comment]
It's a 1080p IPS screen. 😒

**Comment by Drutol** [comment]
Positioning these flyouts is pretty god damn hard because all they take is an element like text/button etc, and placement (left/right). You cannot tell it to appear where pointer was pressed.

**Comment by sinofanger** [comment]
@drutol Did you hear about the Creators Update of Windows 10 scheduled to be released this Spring?

**Comment by Drutol** [comment]
Nope

**Comment by Drutol** [comment]
I've started playing with android... oh it's gonna look bad until I learn how stuff works there ;d

**Comment by sinofanger** [comment]
Yea, good. Surface studio is just awesome. 
By the way, I noticed a new bug, when I Uninstall and reinstall the MAL app, all the past notifications which have been read shows up again as unread. 
😵😵

**Comment by Drutol** [comment]
If you are professional creator that's probably gonna be revolutionary, for me it's like "ok, nice".

As for notifications, storing them in clod from background task seemed unreliable so I had to rely on local storage, changing their status on MAL can prove troublesome too so I decided to do this like this.
