### ISSUE TITLE
Manga pinned to start doesn't open properly

### ISSUE THREAD

**Issue by AzureBlaze** [Drutol/MALClient#75]
When using the feature to pin a series to the start menu and open in app this always happens 
[this](https://i.imgur.com/dq0Ns5w.png) always happens with manga series. It works fine with [anime](https://i.imgur.com/061Ik5T.png) but not manga.

After  digging around a bit, I think the problem is that for manga series it still passes them as `myanimelist.net/anime/{manga_id}` when it should be `myanimelist.net/manga/{manga_id}`

**Comment by Drutol** [comment]
Hello!

Actually the reason is quite different and I'll have to rewrite bigger portion of the system as this is pretty god damn old code. I should be able to address this in next update.

**Comment by Drutol** [comment]
Fixed, you will have to pin this tile again in order to get it to work once update goes live :)
