### ISSUE TITLE
Android design!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#76]
I didn't use android at all yet I'm going to make an android app! Hooray! 🎉 

I'll probably need some help with this:
- design references
- ideas
- what's irritating in current MAL apps
- Are there any flyouts on android?

If you know how to make xmls all the better :D

**Comment by sinofanger** [comment]
There is an app called "Livechart me" in Google Play Store. It is not a MAL app, but it is a very neatly designed anime app, which can give you some ideas.

**Comment by Drutol** [comment]
It sure looks very "androidly"/"google-ishly", this is something different from my *yolo* design practices ^^
