### ISSUE TITLE
Is there a way to search by Genre?

### ISSUE THREAD

**Issue by servicemx** [Drutol/MALClient#77]
I love the app! Thank you! Is there a way to search by Genre on the Windows app?

**Comment by Drutol** [comment]
Right now it's not here yet, but it's great material for next update!

**Comment by servicemx** [comment]
Thank you Piotr!!!!

**Comment by Drutol** [comment]
I think that's all I can do. Performing actual search is not something I'd like to dwell into. 

![image](https://cloud.githubusercontent.com/assets/6102530/19835157/200e5838-9e7e-11e6-9006-8d97b6ae3546.png)

**Comment by Drutol** [comment]
Added in v5.1.10(09).0
