### ISSUE TITLE
Pictures not loading on Windows Desktop

### ISSUE THREAD

**Issue by randomuser13** [Drutol/MALClient#78]
I am using MALClient on both Windows Mobile and Windows Desktop and I have no problems on mobile whatsoever (I really like the app) but since quite a while, the pictures won't load on the desktop version ([Screenshot](http://i.imgur.com/CmYuXmc.png))

It shouldn't be a problem with my internet connection, as switching to another network doesn't solve it and it works fine if I visit myanimelist.net directly.

Some informations:
MALClient: 5.1.6.0
Windows 10: Redstone build 14393.321

**Comment by Drutol** [comment]
Hello, could you please try disabling image cache in settings? Maybe re-install will help?

This is quite odd indeed...

**Comment by randomuser13** [comment]
Indeed, the pictures load with caching disabled. However if I reenable it, they don't load anymore.
In that case I'll just leave it off.

Thanks for your help!

**Comment by Drutol** [comment]
Hmm that's strange... did you set some restrictions on windows store apps, or maybe you are running out of space?

**Comment by randomuser13** [comment]
Not that I knew. And I have around 80GB free on my OS partition so that shouldn't be a problem

**Comment by Drutol** [comment]
Heh, I'll look around for a source of this problem :)

**Comment by Drutol** [comment]
I think I've found the root issue. We will see about that in next update

**Comment by Drutol** [comment]
Issue resolved in v5.1.10(09).0
