### ISSUE TITLE
Android Progress?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#79]
I'll be putting here images in order to be transparent with progress and what's happening, you are free to laugh and I'm free to make your eyes bleed. Enjoy ^^

*(I'll be cleaning this from time to time because of big images)*
**(Oh, and I wouldn't expect anything noteworthy for now :D)**
***(I'm trying to get this to work right now, design is not my priority right now)***

**Comment by Drutol** [comment]
First Image after 1st day with this... this little green....

![image](https://cloud.githubusercontent.com/assets/6102530/19831609/ac9570fe-9e0e-11e6-9a6a-a3ca47877cda.png)

**Comment by Drutol** [comment]
It may look pretty similar but I've managed to create "binding wrapping engine" so that my approach from UWP will work with android too (it's pretty important).

![image](https://cloud.githubusercontent.com/assets/6102530/19857736/18cb4b74-9f7f-11e6-8d72-349a3d6b7fe7.png)

**Comment by Drutol** [comment]
As you can see, this UWP on android. Yay... I've managed to use native Java library though! I've also imported colors from mobile version. I didn't choose accent colour yet but I'm aiming for dark color scheme for now.

![image](https://cloud.githubusercontent.com/assets/6102530/20030519/39fd8cee-a367-11e6-83c6-a9ed8d7ff8d4.png)

**Comment by sinofanger** [comment]
If, I update an anime in Android app, will it sync in the windows app? Cross platform sync?

**Comment by Drutol** [comment]
Ehh, I don't feel like this is necessary at all, all the data is synced with mal website from time to time anyway.

**Comment by Drutol** [comment]
Hey look! It moves!

![image](https://cloud.githubusercontent.com/assets/6102530/20039428/0f6cd31c-a444-11e6-9142-22ce9b9f8788.png)

**Comment by sinofanger** [comment]
Awesome. Seems the work is progressing well.

**Comment by Drutol** [comment]
**Seems** is the keyword here :D

**Comment by Drutol** [comment]
I'm experimenting with grid items interactions!

![image](https://cloud.githubusercontent.com/assets/6102530/20150187/cf8516d8-a6b4-11e6-8bd3-41fef1a4f4f5.png)

**Comment by sinofanger** [comment]
What's the time there now? I could have Google that, but just felt like asking the old fashioned way 😄

**Comment by Drutol** [comment]
I'm trying to find the substitute for flyouts ;d

**Comment by Drutol** [comment]
Emm, did I read you wrong?

**Comment by Drutol** [comment]
I've thrown away previous flyouts and used semi-stock ones. I started playing with details!

![image](https://cloud.githubusercontent.com/assets/6102530/20227202/a5056cbc-a84b-11e6-8ae4-a66ddcceeeee.png)

(not yet editable though)

**Comment by sinofanger** [comment]
Android is still a thing, because end-users have tons of apps to play with. From developer perspective iOS SWIFT and UWP are way better, I guess.

**Comment by Drutol** [comment]
I cannot say much about iOS but it has two huge cons comparing to Android and Uwp. You *cannot* (you can if you are suicidal) write UI in text editor and you have to use designer which is probably better than for other platforms but it'd be nice to write actual xml.(I'm a fan of not using designers ^^)
Second is Apple. Expensive, requires mac, getting all the certificates is annoying and can take forever and so on.

These two are not even close to XAML.

**Comment by Drutol** [comment]
Two tabs almost finished!

![image](https://cloud.githubusercontent.com/assets/6102530/20238436/d8b02066-a8eb-11e6-9175-5f7d5344dff6.png)

**Comment by Drutol** [comment]
Android progresses so much that we will have to break the chain of weekly UWP updates. I feel like it is stable enough to focus on the other platform ^^.

**Comment by Drutol** [comment]
I've figured out the basic basics so we are speeding up! Reviews tab!

![image](https://cloud.githubusercontent.com/assets/6102530/20247081/cb6c2c40-a9c4-11e6-9850-f47767a75f77.png)

**Comment by sinofanger** [comment]
Put a hyphen "-" between story, animation, sound etc... and their corresponding numbers.

**Comment by Drutol** [comment]
Okay.

**Comment by Drutol** [comment]
Next tab:
![image](https://cloud.githubusercontent.com/assets/6102530/20314800/ba0376d2-ab5b-11e6-94c4-6340e2ff3583.png)

**Comment by Drutol** [comment]
Soo... details page is now almost functional, I've played around with hamburger a bit but it still has a ways to go. I did try implementing UWP Mobile hamburger with pivot but in the end it looked bat and was probably against all android so I gave up on this idea ^^.
![image](https://cloud.githubusercontent.com/assets/6102530/20461845/241b3e1c-af0b-11e6-9c1c-f48bfbb3a100.png)

**Comment by sinofanger** [comment]
You seem to be progressing pretty fast.

**Comment by Drutol** [comment]
You may be right in terms of functionality but it'll take sooo much longer for this to look on par with other apps. I hope to have testable apk's in a one month's time ^^

**Comment by Drutol** [comment]
It's been a while... search page is now fully functional! Yup, I'm fairly busy recently and that's why it took me so long :(

![image](https://cloud.githubusercontent.com/assets/6102530/20861056/ce2103c6-b986-11e6-9940-a8cd2d05082f.png)

**Comment by Drutol** [comment]
Calendar almost done! I have to figure out countdown though.
![image](https://cloud.githubusercontent.com/assets/6102530/20867369/149e781c-ba43-11e6-96b1-7d71c77a4e95.png)

**Comment by Drutol** [comment]
Regardless of android app state, I'll release first apk in 2016.

> Me motivating myself.

**Comment by sinofanger** [comment]
nice work so far.. seems going good enough.

**Comment by Drutol** [comment]
No screenshots from this weekend as I was participating in hackathon! I did manage to do some less screenshot-worthy stuff though :D

**Comment by sinofanger** [comment]
How was hackathon? 

I logged into the app after a long time. App seems very slower, compared to the past, after the latest update. What happened?

**Comment by Drutol** [comment]
Slower? First time I heard about it, works as always for me.

Hackathon was fine but I'm not going to participate again... I'm just not fit to give up on my sleep.

**Comment by sinofanger** [comment]
Well, yes I tried in 3 systems, it is comparatively slower. Did anything change in the latest update?

**Comment by Drutol** [comment]
#82, not really. Maybe try reinstalling?

**Comment by sinofanger** [comment]
-_- lazy to do. So how is Android app coming along? When will I get the apk to try out? :P

**Comment by Drutol** [comment]
New year's eve 23:59 sounds nice right?

**Comment by sinofanger** [comment]
![bel](https://cloud.githubusercontent.com/assets/9476430/21185592/48397176-c237-11e6-9df4-f9aa60fb8599.png)

**Comment by Drutol** [comment]
Let's move to this github chat thingy ^^

**Comment by Katsuga50** [comment]
Hey.. Hows the android app going

**Comment by Drutol** [comment]
Well... aside from rough interface and instability I've made:
* Hamburger
* Anime list with grid/detailed items (and all list varations for that matter)
* Swipe on grid items
* Almost completed anime info updating
* Anime details page is almost completed too
* Calendar without countdown
* Search

Things like characters, videos etc. are left for later :)

**Comment by Katsuga50** [comment]
Well. I am looking forward to trying out your app on android too. Its one of the well made UA. Hey why dont you add an extension so that it can use the feature in the screenshot.
![image](https://cloud.githubusercontent.com/assets/19756597/21425454/3716be60-c86f-11e6-8f3e-413b4ca61d98.png)
 
I am asking for extension as you can not officially use associate Apps with website as you dont own the website. But people said it works if the extension is sideloaded

**Comment by Drutol** [comment]
I was looking into it but yeah it doesn't work unless I can do things on website. Can you link this info about extensions? I didn't research them to be honest.

**Comment by Katsuga50** [comment]
Do you know what... Microsoft does a shitty job is cataloging its API. I literally combed through the API list in dev center but could not find it. Then I realize that " Transcoder " app developer had info about extention in his app. He is the first and only dev to use that feature. Download his app and you will get an idea how it works. Still i am putting some link that might help you ( took me an hour to find these two )
https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service (for extension)
https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking ( associate website to app )

**Comment by Drutol** [comment]
Thanks! I'll investigate this further soon. ^^

I've been recently working on push notifications for windows... ALL info is outdated by like 3 years with missing pictures or no longer existing websites, real pain. I'm accustomed to such documentation :D

**Comment by Drutol** [comment]
I did read some articles about it but I don't see how extension can help with overcoming serverside changes. The premise sounds nice, for example I could expose update endpoints or other stuff for manga reader app.

**Comment by Katsuga50** [comment]
It was in reddit that one guy ( probably mytube dev ) made youtube links open into his app but he required it to be sideloaded rather than installed via store. Same goes for the WindowsCentral app. So what I am suggesting is that if you can make it work then keep the feature in a plug in or extension so that people can normally download your app from store but if they want the particular feature of opening links into app then they gotta sideload the extension.

**Comment by Drutol** [comment]
I've just stubled upon thid reddit post :D

**Comment by Katsuga50** [comment]
send the link

**Comment by Drutol** [comment]
https://www.reddit.com/r/WPDev/comments/5h33io/is_it_possible_to_associate_a_uwp_app_with_an_url/

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/21437868/8f8365b4-c886-11e6-8e4f-2da96a7f2bf2.png)

Well t launches when I launch it from Win+R window, but browser fails to do so :(

**Comment by Drutol** [comment]
![gif](https://cloud.githubusercontent.com/assets/6102530/21438292/7dd30e1c-c888-11e6-83e9-16230badfc31.gif)

**Comment by Drutol** [comment]
This is android progress thread btw xd

**Comment by Drutol** [comment]
Okay, I'll leave this for toady. If you are able to find out whether just launching link in browser should work I'll be able to finish this tommorow. ^^

**Comment by Katsuga50** [comment]
![image](https://cloud.githubusercontent.com/assets/19756597/21447061/bacbb3e8-c8f4-11e6-905f-0ade6fd8a465.png)
yes this is what I was talking about. I should ask him about how he did it. we made the android forum into windows . :P

**Comment by Drutol** [comment]
We can either move to the chatroom or make next issue, I'll be cleaning up these posts once we are done xd

**Comment by Katsuga50** [comment]
yeah we should better move.

This is supposed to work this way -

Your friend sends you a MAL link ( Anime recommendation ) in messenger 
you click on it
instead of opening into browser , it opens into your app

**Comment by Drutol** [comment]
It works then, I'll upload extension and app to github in new issue once I'm home. :)

**Comment by Katsuga50** [comment]
will be waiting for that. :)

**Comment by Drutol** [comment]
Recommendations page in light mode!
Next will be log-in page (sounds useful) and basic settings.

![image](https://cloud.githubusercontent.com/assets/6102530/21470485/a3c7d0b2-ca8b-11e6-8d0c-b8772969edda.png)

**Comment by Biodam** [comment]
Hello. 

Just passing by to say that this looks really good. Nice work man.

**Comment by Drutol** [comment]
Thanks! First apk ever will be available in max 3 days ^^

**Comment by sinofanger** [comment]
And you know right? I need the beta apk first for testing :P I been in queue for over two months now. :P

**Comment by Drutol** [comment]
Fortunately stock is unlimited :D

**Comment by sinofanger** [comment]
Cool, happy new year in advance to you :) Also, those wallpapers in the windows app are really good. Everyday I get to see some mind blowing pictures. Also, I saw you have removed HummingBird. Well, Hummingbird is dead anyway. So it does not matter.

**Comment by Biodam** [comment]
Happy new year to guys. :D What!? You can change wallpaper? Didn't get that. When did I missed it? That must be awesome. Need to get home to test it.

**Comment by sinofanger** [comment]
@Drutol  :3 couple of more hours left. Where is the apk :3

**Comment by Drutol** [comment]
Umm, doing datepickers now.

**Comment by Drutol** [comment]
Android is hibernating because UWP requires my attention right now ;d

**Comment by Drutol** [comment]
Better image loading

![gif](https://cloud.githubusercontent.com/assets/6102530/22853498/2c3ffca2-f058-11e6-840d-30e7edc8ee43.gif)

**Comment by sinofanger** [comment]
You seem to be in full swing Android development.

**Comment by Drutol** [comment]
We've even new android helper (@Latawiec), he is just starting though ^^

**Comment by sinofanger** [comment]
That's good news. Hey, I was thinking, may be it is farfetched. Down the lane, after Android app ad everything gets released, may be we should put up a small website for this, u know to make these apps more popular and bring it to the front of more users.

**Comment by Drutol** [comment]
Update dump this time!

![untitled](https://cloud.githubusercontent.com/assets/6102530/23091458/f87ec81c-f5b6-11e6-99ed-420b0eb8dbae.png)

**Comment by Drutol** [comment]
My aim is now to remove bottom bar of anime list (filters sortings and things...) and replace it with something more android-like (e.g. Floating Action Button) any ideas?

**Comment by Drutol** [comment]
![gif](https://cloud.githubusercontent.com/assets/6102530/23101093/1183f73e-f68d-11e6-8f21-f8f134a13aea.gif)

This is obviously bad... where's my UX yolo enlightment ;d

**Comment by sinofanger** [comment]
I think the button is good, ease of access rather than the previous method. Some suggestions:
1) in the floating action button panel only include the important options. Too much options will not be good. Like forums, profile, my list. That is enough.
2) Well, i was planning to type more, but i will tell more suggestions after i test drive one of the apks.. I need to feel the app to tell some suggestions. I will wait for the next build.

**Comment by Drutol** [comment]
Nah, this button is meant only for anime list stuff. Sorting, filters etc. The hamburgers with rest stays and I don't think I can get rid of it now because there's too much content.

I'm thinking about adding pane that will slide out from the left with filters and/or sorting.

**Comment by sinofanger** [comment]
Hmm, ya try to reduce the content. Because cramming up everything into a mobile app might be too much for some. Like provide a settings called "feature" where users can enable each content one by one like: forums,  clubs, friends lists, news, images, articles etc.

By default just have the options "My lists", "forums" "News" "Top anime" etc. And definitely include a small walk-through for first-time users. It is required before public launch.

**Comment by Drutol** [comment]
Customization of hamburger menu is quite good idea to be honest as I cannot have pivot in there as I have on windows mobile ^^

**Comment by Drutol** [comment]
![gif](https://cloud.githubusercontent.com/assets/6102530/23102493/88050534-f6aa-11e6-8018-e4a5c89ac6f9.gif)

One more click than on windows though :(

**Comment by FoxInFlame** [comment]
So... What happened to the APK that was going to be released in 2016?

**Comment by Drutol** [comment]
It was released... see #88 . Or you are better off not seeing it ^^

I'll do some things this weekend.

**Comment by Drutol** [comment]
@FoxInFlame forums are coming.

![image](https://cloud.githubusercontent.com/assets/6102530/23585652/feed1446-0183-11e7-862f-8384842956b5.png)
![image](https://cloud.githubusercontent.com/assets/6102530/23585655/092a8664-0184-11e7-913c-56bc4f9b0606.png)

**Comment by FoxInFlame** [comment]
Looks great, but is the "MyAnimeList" orange text necessary?

**Comment by Drutol** [comment]
It's the header of board section, like so:
![wp_ss_20170305_0002](https://cloud.githubusercontent.com/assets/6102530/23586221/18f40054-0191-11e7-8f47-9a815e97838d.png)

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/23589036/cd785cfc-01c6-11e7-95e4-006249028c25.png)

Bam! Board page was much easier than previous page. Topic one is going to be a real challenge though.

**Comment by Drutol** [comment]
I got these things to stretch properly!

![image](https://cloud.githubusercontent.com/assets/6102530/23721482/358b0038-0442-11e7-9b0a-9a7d6f74e27e.png)

**Comment by Drutol** [comment]
I'm thinking about building some binaries with dev version, anyone up for a bit of disappointment?

**Comment by Kimod** [comment]
Me! Me! Me! o/

**Comment by Drutol** [comment]
Okay then, I'll click through it in search for blocking stuff and I should be able to put something up today ^^

**Comment by Drutol** [comment]
Today I'm starting with github android project:
https://github.com/Drutol/MALClient/projects/3

Essentially: If there's no stuff in TODO, that means the we have reached beta.

**Comment by Drutol** [comment]
Messaging main page, tomorrow I'll do the second one.

![image](https://cloud.githubusercontent.com/assets/6102530/24074948/ccbdb89c-0c12-11e7-9a66-865c91308790.png)

**Comment by Drutol** [comment]
Messaging is now usable:

![image](https://cloud.githubusercontent.com/assets/6102530/24079223/31eb6c80-0c83-11e7-8ec5-9a524079567d.png)

**Comment by Drutol** [comment]
Ding! Notification!
![image](https://cloud.githubusercontent.com/assets/6102530/24239974/3e5e80c6-0fb0-11e7-98bb-5ffe6102588a.png)

**Comment by FoxInFlame** [comment]
I updated my phone to Android 7! If that helps.

I love how my name appears in a lot of the screenshots as examples. When will the highly anticipated next alpha APK come?

**Comment by Drutol** [comment]
Once there's nothing left in todo list: https://github.com/Drutol/MALClient/projects/3
Basically when all (or most) features that Windows has will work (barely) we will start beta.

What can I do when this is the only notification I have right now :D

**Comment by Drutol** [comment]
I've paid for dev account! I guess that next builds are going to be published by on google play ^^

![image](https://cloud.githubusercontent.com/assets/6102530/24325233/9d58fe72-1194-11e7-9201-d8df6778123e.png)

**Comment by Drutol** [comment]
Character details! + characters&staff in details page + details page now supports landscape mode
![image](https://cloud.githubusercontent.com/assets/6102530/24329713/e7df02b4-120e-11e7-8de8-d3381119604c.png)

**Comment by Drutol** [comment]
###Only 2 more pages to go!

![image](https://cloud.githubusercontent.com/assets/6102530/24333270/3d0f4294-1255-11e7-82fe-89a771ef0e97.png)

**Comment by Drutol** [comment]
Page history is finished!

![image](https://cloud.githubusercontent.com/assets/6102530/24492614/64ad7fd0-152c-11e7-8d37-6f172a200fc1.png)

From main pages all what's left now is Wallpapers page. (forums are subpages) ^^

**Comment by FoxInFlame** [comment]
If the history page is made like that, wouldn't it be better to make use of [this](https://myanimelist.net/ajaxtb.php?detailedaid=21) as well?

**Comment by Drutol** [comment]
What do you mean by "this"?

![image](https://cloud.githubusercontent.com/assets/6102530/24497054/75da8614-153a-11e7-9957-df7fce0ed391.png)

**Comment by FoxInFlame** [comment]
Yeah. Your layout combines each anime into its own row. If we're looking at it like that and not like the original MAL layout of /history page, I think including the whole history for each of the shows would be helpful. It would take time to request though.

**Comment by Drutol** [comment]
I'd rather think of it as another button on show's details page, easier and more intuitive in my opinion. History page would have to change alltogether too becasue it's groupped like on MAL's history.

**Comment by Drutol** [comment]
I just got android device for this weekend and I've been clicking through existing clients... well feature wise I'm pretty god damn solid.

Some notes:
* Images are loading more smoothly.
  * But in grid mode I've images 2-3 times bigger.
* They are polished quite nicely
  * But we are in beta
* There's better search
  * I'll do it once I'm back to standard development with new features... clubs anyone?
* Pocket MAL has pretty decent reviews section
  * Source of inspiration?

**Comment by FoxInFlame** [comment]
Tapping through, you mean. :)

The Android apps I like to use together are PocketMAL, Atarashii! and anYme.
Here's a quick overview I thought of them:

PocketMAL has an incredibly smooth interface regarding user profiles, in my honest opinion. I am personally not in favour of this one-anime-per-row layout, but it's smooth as hell, so I'm not going to argue much.
Atarashii is pretty solid overall, slightly similar to MALclient in regards to content. I personally don't like how the image takes up the entire page on Anime Info or User Info, when they could've made it so you tap to enlarge.
anYme is more of a stream app. It's good in the sense that it can sort by last watched (handy when you want to update quickly). It has a Random Anime feature and MAL Profile Cleanup feature, but it loads other parts by directly displaying the website in a frame. The fact that you can't edit anything other than progress and score reduces its quality a bit as well.

I still have all three + MALclient installed, and I use them quite often. anYme would be the one I use the most, because of the handy streaming links, but I also use PocketMAL.

**One annoying thing about PocketMAL and Atarashii is that they put Studios, Licensors and Producers all together. It's kind of confusing, because I write studios in my tags and I don't know which of them is the studio and which is the licensor.**

**Comment by Drutol** [comment]
I'll try to reduce your mal app count to 2 then :D

I'm planning to finish forums this weekend which are by far most complicated and after that move on to tweaking and adding smaller parts. I'll do wallpapers further down the line as I don't have an idea for UI yet. Maaaybe I'll put closed beta build on google play next weekend...

**Comment by FoxInFlame** [comment]
Yes! Finally, another beta!

**Comment by Drutol** [comment]
Change of plans, I took my time and applied very efficient refactoring strategy called **ctrl+a del** on whole android logic regarding all 3 anime lists (grid,list,compact).

It's more stable and smooth af if I may (at least on nexus 5) ;d

**Comment by Drutol** [comment]
I can now add colours on a whim!

![image](https://cloud.githubusercontent.com/assets/6102530/24721426/a4a97986-1a40-11e7-8f4c-3d20ebae5331.png)

If you'd like to add yours see #116 :)

**Comment by Drutol** [comment]
This "making-of" issue comes to an end :)
