### ISSUE TITLE
Doesn't show full name of long titles

### ISSUE THREAD

**Issue by Accelyte** [Drutol/MALClient#80]
'Yahari Ore no Seishun Love Comedy wa Machigatteiru.' stopped at 'Yahari Ore no Seishun Love Comed...'
Screenshot: http://imgur.com/a/raBUh

**Comment by Drutol** [comment]
Hello, to be honest I probably can fit one more line there :)

**Comment by Accelyte** [comment]
Maybe you can add a variable textbox so when the title is too long, a button appears that allows you to extend the title downwards?

**Comment by Drutol** [comment]
I feel like it'd be more "complicated" then it's worth too be honest.

**Comment by Accelyte** [comment]
well MAL on Android has it...

**Comment by Accelyte** [comment]
Either that or a textbox that automatically adds lines to itself to show the full title. I dunno man, it's just confusing to try figure out Yahari Ore from Yahari Ore Zoku because the Zoku's at the end...

**Comment by Drutol** [comment]
Sure thing, two lines of text are not going to look that bad + it's one line anyway in most cases :)

I should push update to certification with this in next few hours :)
Nice timing!

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/19900642/8b81fb28-a064-11e6-8631-4ac236a22f2d.png)

Adding more buttons there would make this bar even more cluttered + it fits perfectly.

**Comment by Accelyte** [comment]
Woooo thanks :)
