### ISSUE TITLE
News not Updating

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#81]
The live tiles with news is not updating. We have to manually refresh the news section using the "reload" button. 

For the past 3 days the live tile with news was showing the same news. I started rebooting and all. Finally I had to manually refresh the news.

Look it into if possible.

**Comment by Drutol** [comment]
Well, the code follows the path it should. I'll try to see it for myself.

**Comment by sinofanger** [comment]
"the code follows the path it should" 
Why are u talking like master Yoda? 😒

**Comment by Drutol** [comment]
Having taken the right path they went stray into the deep black void.

**Comment by Drutol** [comment]
Pushed fix to the store.
