### ISSUE TITLE
I've created Gitter chat...

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#84]
It may be a good solution for random talks that happen in issues :D

https://gitter.im/MALClient/Lobby

Let's see how that works.

**Comment by sinofanger** [comment]
-_- You created a seperate chatroom? Anyway, how is the Android client coming along? And how is your holiday season :)

**Comment by sinofanger** [comment]
Also, quick question. Suggest some beautifully designed UWP apps that I can install. I know that Reddit app, any other apps that are your favourites?

**Comment by Drutol** [comment]
That's the exact reason for this chat xd

Android, weeeell... it works but is far from finished.

**Comment by sinofanger** [comment]
Hmm, why not a Skype conversation then? Most have skype, its a pain to use a new website for chat. :(

**Comment by Drutol** [comment]
Chat for git repos sounds pretty accurate and is widely accessible. (+ I don't have skype)
