### ISSUE TITLE
Apps for websites!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#86]
Versions v5.1.25.0+ will now support launching mal links!
```
"Protocol"
malclient://<myanimelist.net url>
```
In order to launch MALClient when opening mal link you will need to download and install special app that will forward these requests to the app itself. This is because of requirement of being website owner...

You can download this smaller app here:
https://github.com/Drutol/MALClient/releases
Desktop app with this support:
https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c

If somebody wants mobile let me know :)

**Comment by sinofanger** [comment]
Why does it say that the publisher is Dogie? O_O

**Comment by Drutol** [comment]
MS has trimmed my email which resulted in windows account named "dogie" which in turn was put there even though I changed it... w/e I'll change it once it's done.

**Comment by sinofanger** [comment]
Even though I am in developer mode, I get the following error:

> Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by Drutol** [comment]
I'll send you this certificate once I get to my computer.

**Comment by Drutol** [comment]
https://files.fm/u/zw29qhe2 Try, this.

**Comment by sinofanger** [comment]
Not working. Is not it possible to pack this app along with the main app and introduce  new option in the setting to open external MAL links in the browser?

**Comment by Drutol** [comment]
Nope, I'd have to be the owner of mal to do so. They may change it though but for now this is the workaround.

**Comment by Katsuga50** [comment]
![image](https://cloud.githubusercontent.com/assets/19756597/21819274/02095454-d791-11e6-9f3e-5b8d554579fc.png)
So you managed to do it finally. <3

**Comment by Katsuga50** [comment]
but then this. :'(
![image](https://cloud.githubusercontent.com/assets/19756597/21819555/21ca1412-d792-11e6-839b-afe5986ab80a.png)

**Comment by Drutol** [comment]
There's powershell script to install this ^^

**Comment by Drutol** [comment]
And you should download v1.1 of this interceptor app

**Comment by Katsuga50** [comment]
From 1 mb to 15 mb app :P

**Comment by Katsuga50** [comment]
![image](https://cloud.githubusercontent.com/assets/19756597/21835771/9a351a84-d7e5-11e6-912c-e08434377f8f.png)
got in

**Comment by Katsuga50** [comment]
if you notice then other apps have 3 types of URL which you should look injto. And when clicking on myanimelist.net then your app opens for 0.2 second and crashes and then the link opens in browser.

**Comment by Katsuga50** [comment]
but workign when the link is like this myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi

**Comment by Katsuga50** [comment]
![ezgif com-9e94b49b81](https://cloud.githubusercontent.com/assets/19756597/21836402/004c4158-d7eb-11e6-811c-51b5df773038.gif)

**Comment by Drutol** [comment]
Okay, I thought that www wasn't necessary. Oh and the app doesn't crash, it's the launcher that launches main app and I couldn't make it without creating new window :(

**Comment by Katsuga50** [comment]
I know that. but when i am clicking on " myanimelist.net " only then your app does not open. but good work with the rest of the part

**Comment by Drutol** [comment]
I'll fix things this weekend. :)
