### ISSUE TITLE
Yay or Nay?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#89]
I'll be playing with UI over this weekend cause I got some new designer toys ( I know, I know... android... but toys!!) ^^

I'm not sure about this one... and I feel like I should make this less cluttered. 
![image](https://cloud.githubusercontent.com/assets/6102530/21697620/7bfb0bc4-d393-11e6-8ef3-47fe75e0c93a.png)

I've already refreshed profile page :)
If you would like me to focus on some pages this is the time as the hype is still present xd

**Comment by sinofanger** [comment]
Hmm, my suggestion would be to keep the anime interface less cluttered. Most android screens are 5.5 inch or lesser. So, it would be better to keep a clean minimal look, with essential features.

**Comment by Drutol** [comment]
Well, it's not android...

**Comment by Drutol** [comment]
Or something like this?
With the two new buttons being friends feeds and pinned profiles.

![image](https://cloud.githubusercontent.com/assets/6102530/21715425/a82d5a6e-d404-11e6-99e7-9e8caeca894f.png)

**Comment by sinofanger** [comment]
Ya, that seems that seems neater. Sorry, I first thought it was Android. WellOn a side note, I almost threw my laptop away trying to download wallpapers from MAL windows app. When I browse to a second page and comes back to the first, all images reload. -_-

On a side note: If the laptop goes into sleep or hibernation while the MAL app is running in background. I will not get any more notification when I resume the laptop from sleep. Then I have to reboot the lap for the app to work.

**Comment by Drutol** [comment]
Umm they shouldn't reload, they are cached and jump from from 0% to 100% instantly. At least that's how it works for me.

You won't get notifications because it's based on timed background tasks (which are not very reliable) and not on push notification which require server infrastructure.

I don't know whether I can do something to prevent "app pause" while minimized, it's managed by the system.

**Comment by sinofanger** [comment]
Ohh, well that is sad. From what you are saying, is Windows 10 ecosystem limited when it comes to development flexibility?

Also, is it possible to enable in-app shortcut commands like "ctrl+f" to find anime, "ctrl+r" to see its reviews... etc etc?

**Comment by Drutol** [comment]
What do you mean by development flexibility?

I haven't looked into shortcuts yet.

**Comment by sinofanger** [comment]
Like, I meant, as a developer you cannot prevent app pause. That made me thinking. 

Ya, look into shortcuts.  That seems a good idea. But there should be flexibility for people to select their own shortcuts, or else it might be blunt.

**Comment by Drutol** [comment]
Bam!
![image](https://cloud.githubusercontent.com/assets/6102530/21719968/c44afd20-d420-11e6-8e70-d139e43c5ab5.png)
Looks nice imo ^^

**Comment by sinofanger** [comment]
Ya, that does look good. Nice job. Looks like ibooks. 
Also, what about "ask cortana" feature? I asked because, the MAL search feature is pretty bad. If I type a name a little wrong, it returns "sorry no results found". So I was thinking if there was any easy way to trigger google search or "ask cortana" from within the app, it will be helpful.

Right now, what I do is open the web browser, google the name of the anime and then copy paste the anime name back into the app. :(

**Comment by Drutol** [comment]
Hmm, I didn't had an issue with search of this caliber... what are your examples?

**Comment by sinofanger** [comment]
Eg: Vision of Escaflowne, serei no moribito

The second example, I missed an "i" and it did not return any results. The first one, is the English name of the anime, but MAL only had its Japanese name.

**Comment by sinofanger** [comment]
Two other issues I found:
1) When there are too many **embedded Youtube videos** in a forum post, the app takes pretty long time to show the post. The app even temporarily freezes sometimes.
2) I cannot find **genre information** on some anime:
<img width="436" alt="12" src="https://cloud.githubusercontent.com/assets/9476430/21720380/bfd2973a-d448-11e6-8dd5-538a0e0441e7.PNG">

**Comment by Drutol** [comment]
Nothing I can do with MAL's flawed search methods for api. (aside from scrapping but I would like to avoid it for search)

What do you mean by "some anime"? There is no genre info on "general" page.

**Comment by sinofanger** [comment]
O_O then?

By the way which language are u using to write this app? Can you tell me a little bit technical info about that? Like whether u are using visual studio or something, or c+ etc? Also, in which all languages can UWP app be written in?

I am trying to learn some "behind the scenes"

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/21724689/bd53580e-d435-11e6-989d-3df76abddc0a.png)

100% C#, you can also write in C++ but it's for suiciders only in most cases. The android app is empowered by Xamarin which enables C# on iOS and Android devices. Visual studio is all you need.

**Comment by Drutol** [comment]
New version is up in #73

**Comment by sinofanger** [comment]
@Drutol  What changes did you make? Did not notice anything in the WIndows Store changelog.

**Comment by Drutol** [comment]
Well, it's a test version and changelog is inside. Store version went to certification yesterday and changelog is in te issue with changelog.

**Comment by sinofanger** [comment]
By the way, there is a very neatly designed wallpaper app in the UWP store; Myersplash. It is a very simplistic design. They use all wallpapers from unsplash.com

Also, I am looking forward to your version of the app with "copy to search" feature for anime titles.

**Comment by Drutol** [comment]
"Copy to search", in forums right?

**Comment by sinofanger** [comment]
@Drutol  yes. Remember, we were talking about how easy it would have been to search for an anime name in forum posts by simply selecting it.

**Comment by Drutol** [comment]
It's already done in v5.2.0.0+

**Comment by Drutol** [comment]
It should be on the store within next 24 hours

**Comment by sinofanger** [comment]
Ohh, nice. Tell me, which other features are in pipeline other than clubs, friends and personal messaging? I am just curious.

**Comment by Drutol** [comment]
Messaging has been there for ages.
I'll have to do something with friends one day but right now it's this grid in account page only.
Clubs are waiting for "hype trigger".

Notification page & list comparing is on the TODO list too.

**Comment by sinofanger** [comment]
I meant messaging a person from the forums. If I find someone in the forum posts that I wish to personally message, it would be an option to have a messaging icon near his/her profile name.

**Comment by Drutol** [comment]
Hohoho, this is far away. I'd have to hack in javascript quite a bit. It's not the most pleasant thing to do. But idea added to project.
