### ISSUE TITLE
This still happens!!!

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#91]
<img width="586" alt="error" src="https://cloud.githubusercontent.com/assets/9476430/21886025/111a8756-d8e0-11e6-8baf-be847547ca6b.PNG">
*sighh*

**Comment by Drutol** [comment]
It still happens because I don't know how to bend timespace... yet...

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/21956200/dce606c0-da7b-11e6-9014-872827259cc6.png)

Take this and be quiet. :D

**Comment by sinofanger** [comment]
I just installed the new version of the app. Really amazing work, mate. Hub seems flawless :)
Thanks *goes quiet* :P

**Comment by sinofanger** [comment]
By the way where is the "anime suggestions" as mentioned in the new change log. I could not find it. Is it the anime recommendations section?

**Comment by Drutol** [comment]
Yup, there's bar at the bottom or in this button top left. These are items from MAL's main page nothing more.

**Comment by sinofanger** [comment]
Ok, seems good. I have one more suggestion. In the "recent topics" section, can you please provide a sorting functionality. Like "sort by thread creation date", "sort by last post date", "posts i created" etc etc. it would be really helpful, when searching for some posts that we created or commented on in the past.

Is it possible?

**Comment by Drutol** [comment]
"Everything is possible, given enough time."™

While sorting is not going to be much of a problem, forums are heavy topic nevertheless and I see that they need more love. Maybe I'll drop html rendering of whole forum page and only render the contents of the topic, but that requires some heavy scrapping and research about forum *API* + it's full of javascript which is not something I specialiaze in... the thing is that it's not my priority nor I'm hyped about it.

*Akhem*... Android...*cough cough*...

**Comment by Drutol** [comment]
And I'll surely do clubs before forums major overhaul.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/22163042/85a7cf76-df51-11e6-8266-fbdd55d21718.png)

**Comment by sinofanger** [comment]
Ohh, new posting interface. Seems good. Anyway to introduce a button to install smileys?  :O

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/22172825/9e2dd63e-dfb1-11e6-8b84-d936ededb665.png)?

**Comment by sinofanger** [comment]
-_- That is the onscreen keyboard -_-

**Comment by Drutol** [comment]
Sure it is

**Comment by Drutol** [comment]
4 hours later...
![image](https://cloud.githubusercontent.com/assets/6102530/22173815/ebfd6ef8-dfcd-11e6-84d3-a7bfd4b12a48.png)

**Comment by sinofanger** [comment]
And here I am scraping MAL using Python -_-    :(

**Comment by Drutol** [comment]
What are you working on?

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/22175253/b93125a4-dff1-11e6-89d0-53eb243495bc.png)

Taking shape!

**Comment by sinofanger** [comment]
It looks good. Ohh, well I am just playing with python; reading APIs, and casual Web scraping.

**Comment by Drutol** [comment]
Have fun ^^

**Comment by sinofanger** [comment]
Yea. Is it possible to write UWP apps in python? No, I guess?

**Comment by Drutol** [comment]
Nope, c#... and c++ if you are brave enough... There are also some APIs for Javascript.

**Comment by sinofanger** [comment]
Ohh, I have not used C since 8th grade. It has mainly been: Java, php and python.

**Comment by Drutol** [comment]
Well C# is just *better* Java

**Comment by Drutol** [comment]
With editing!
![image](https://cloud.githubusercontent.com/assets/6102530/22176516/d510aa72-e00c-11e6-89b4-5220189469dd.png)

**Comment by sinofanger** [comment]
Looking very clean. The irony is, even the original MAL website is not this cleanly designed.

**Comment by Drutol** [comment]
I can somehow agree with you, I was reluctant at the beginning but it's gonna be usable.

**Comment by Drutol** [comment]
Okay, I actually have now usable topic page with scrolling and all.
What do you need on forums when you are not lurking? (your messaging buttons are already in-place)
I'll try to upload working version for testing later today :)

**Comment by sinofanger** [comment]
A quicker way to jump from one forum to another. Example, say if I want to go to "casual discussion" forum from the "recommendation" forum, how can I do that other than clicking 3 times to get there. So any sort of jump-lists near the forum header would be well good.

Also, when it comes to caching images in forums and other sections. Cache them for longer periods. And give an user to "clear all cache". So the app will get faster and faster, as it gets used more. Allow cache up to a month.

**Comment by Drutol** [comment]
You can already pin these boards, right? 
![image](https://cloud.githubusercontent.com/assets/6102530/22181865/e3e81326-e095-11e6-81b7-c03bef691f6f.png)

Unfortunately the posts itself are rendered in small WebViews and I don't know how they are caching images. User avatars are cached properly.

**Comment by sinofanger** [comment]
OK, I didn't know things could be pinned. Well if they are Web views they can't be cached I guess.

By the way, can u do anything to cache the wallpapers in the images section. Like cache atleast the latest 20 wallpapers, so that they don't have to re-download everytime I open the app in the same day. That would be helpful. And ofcourse an option to clear this cache or to increase size of cache.

**Comment by sinofanger** [comment]
Also, an option to send crash report, if the app crashes. That would come in very handy down the lane.

**Comment by Drutol** [comment]
Crash reports are sent whether you like it or not in the background, with atached various things that sometimes describe crash accurately. If somebody wants to talk to me there's plenty of ways :) (email,github,feedback hub,forums...)

**Comment by sinofanger** [comment]
Ehh? So u are saying even if no one reports crashes to u, u are getting crash reports from them?

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/22183741/f39e765a-e0c4-11e6-817d-1481b3d3c9c1.png)

**Comment by Drutol** [comment]
Crashanalytics are provided by the system itself.

**Comment by sinofanger** [comment]
OK that's good. By the way, is this mentioned in terms and conditions or anywhere ? Because some users don't like such unauthorized information exchange, right? Many apps nowadays specifically show a pop-up after crash, saying

"do u want to report this crash?"

**Comment by Drutol** [comment]
Terms and conditions? Well, I've created half page pdf with some stuff because after 9 months on store I got an email that I should put up something like that... Analytics are collected and sent directly from system and I cannot disable it even if I wanted to. If somebody does not agree with it they can uninstall the app :)

**Comment by Drutol** [comment]
https://github.com/Drutol/MALClient/issues/73

Feel free to click through it, I have not tested creating new topics aside from doing it on test club's forum so be aware. Should be usable.

**Comment by sinofanger** [comment]
Don't worry. Two third of the people do not even know there is a terms and conditions. Only some "afraid of Skype" users care about all these.

**Comment by Drutol** [comment]
Most people are not aware of volume of data sent by apps without their knowledge ^^

**Comment by Drutol** [comment]
Hmm, have you checked it out?

**Comment by sinofanger** [comment]
Actually, I got sick in the mean time. 😫😫😫

**Comment by Drutol** [comment]
Ouch, get well soon :D

**Comment by Drutol** [comment]
It happens no more!!!

**Comment by sinofanger** [comment]
How you did it? :O

**Comment by Drutol** [comment]
Umm there's completly new non html page?

**Comment by sinofanger** [comment]
Interesting. I think, after the Reddit and Netflix app, MALclient is the one which has good user interface.

**Comment by Drutol** [comment]
Thanks ^^
Anyway, did you thing that previous screenshots were from html page?
