### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#93]
App is crashing whenever I try to write for long in the "recommendations forum". I tried using bbcode, not sure whether that is the reason. Crashed for 2 times in the past 2 attempts. So for the time being I am using the MAL website :'(

**Comment by Drutol** [comment]
It crashes on submiting post?

**Comment by Drutol** [comment]
I'm heavily thinking about postponing android even more and do clubs because clubs have forums and I could spam there all I want for test purposes.

**Comment by sinofanger** [comment]
:( well yeah app is crashing on submitting posts to the "recommendation section". Other section seems fine. *depressed*

**Comment by Drutol** [comment]
I'm actually amused that it works this much... considering I was making this with lurkers in mind ^^

**Comment by sinofanger** [comment]
-_- Fix it. 
![mugsy](https://cloud.githubusercontent.com/assets/9476430/22058966/f0aea262-dd90-11e6-89cd-4d3f731f0ee9.jpg)

**Comment by Drutol** [comment]
I feel like I'm threatened ;d

**Comment by sinofanger** [comment]
A little bit :P because I was typing a long post and the app crashed two times in the middle and had to retype all those for the third time. 

Your app is the only hope. That MAL website looks silly in high dpi displays. It is very painful to use.

**Comment by Drutol** [comment]
It crashed *WHILE* you were typing?

**Comment by sinofanger** [comment]
Yes, that is the biggest concern. I could not even copy-paste the content. Crashed immediately after typing around 400 words.

**Comment by Drutol** [comment]
Just Wow... I did not expect that.

**Comment by sinofanger** [comment]
ya, try to fix it when u get some time...
![mugsy2](https://cloud.githubusercontent.com/assets/9476430/22059598/a095ca5a-dd93-11e6-991c-8253411ec52b.jpg)

**Comment by Drutol** [comment]
I may throw out html out of there. It'll make things much more nicer code wise, but will take some time.

**Comment by sinofanger** [comment]
Well, I myself am playing with API reading and manipulation etc with Python.

**Comment by Drutol** [comment]
If you want to make research for me feel free to do so ^^
Endpoints,parameters and such

**Comment by Drutol** [comment]
nvm, found:
https://bitbucket.org/ratan12/atarashii-api/src/247962babe59fb77f2ec260e3504dce7b11eadf0/src/Atarashii/APIBundle/Service/Communicator.php?at=master&fileviewer=file-view-default#Communicator.php-175

**Comment by sinofanger** [comment]
is not atarashii, another MAL app for android?

**Comment by Drutol** [comment]
yes it is but they have figured out some things already "api"-wise

**Comment by sinofanger** [comment]
Also another sad news. Notification center failed to load 6 new notifications I received in a thread I made. I just saw them in MAL website. 6 notifications. -_-

**Comment by Drutol** [comment]
Refresh button did not help?

**Comment by sinofanger** [comment]
Hey, I tried reinstalling, refreshing and all. The app just randomly closes while doing things like adding anime to my list etc. Today I clicked on "troubleshoot network connections" button in windows and the app immediately hung and then closed while I was in the middle of composing a thread.

Try to fix these instabilities before introducing club features and all. If you can enable some debug log file or so, in future I can just send it to you.

Thanks mate.
@Drutol

**Comment by Drutol** [comment]
There's one suspect... but I won't be able to do anything today :(
Still very odd

**Comment by Drutol** [comment]
I've given up on sleep today so I can push hotfix in the meantime.

**Comment by Drutol** [comment]
Update is live, reopen if things still crash.
