### ISSUE TITLE
"Top Anime" view broken

### ISSUE THREAD

**Issue by Guerra24** [Drutol/MALClient#94]
[Video of the issue](https://puu.sh/tvoJl/aa2d9cf9a0.mp4)

To reproduce the issue go to the bottom of the "top anime" and click the 3 dots multiple times, when they disappear go to other menu, open "top anime" again, click the 3 dots multiple times and then the issue will appear.

**Comment by Drutol** [comment]
Hello, thanks for report!

These dots have been problematic since forever ^^

**Comment by Drutol** [comment]
Fixed, update *should* be up next week if I manage to finish forums.
