### ISSUE TITLE
Native forums! Aftermatch!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#96]
They are almost done and quite usable in my opinion :D
I'd like to release them next week and I'd like to test them before it'll crash world-wide.
### What new?

* New forum topic page which is ***NOT*** website wrapper.
* New new topic page with live bbcode preview.
* New "starred messages page" just to bookmark interesting posts.
* Private messaging will now display images contained in these messages.
* #64 Fixed + I hope finished "load more/3 dots at the bottom" functionality.
* You can now browse recent topics of any user.

### What's missing? 

* Pools
* Signatures - I've them scrapped and are ready for display... but due to certain something they'll come later.

### Download
This build is built in **debug** configuration which means it'll work slower but I'll get very detailed crash reports.
See #73

**Comment by Drutol** [comment]
Aaand I see first crash ^^

**Comment by Kimod** [comment]
Notes from forum lurker:
* Now that you have the whole page native, couldn't you add "Pin" and "Pin to lastpost" somewhere?
* You should probably do something with long titles - http://puu.sh/tE6Wt.jpg or maybe better, I think it takes up unnecessary place there, could you move it next to "Forums" ? - http://puu.sh/tE7Jw.png
* While a forum page is loading and you click on globe, it will crash the app - http://puu.sh/tE76t.gif
* A lot of crashes (ok, maybe 1 or 2) while afk, literally doing something else in different window, dunno if your crash reporter caught something, also I have in app notifications turned off
* In some comments you can scroll, I can imagine this is a difficult issue to solve - http://puu.sh/tE7Q7.gif
* You should probably prevent from going to a page of comments that doesn't exist - http://puu.sh/tE84F.gif
* A lot of random crashes when messing with Starred comments, all crashes were caused when I clicked on back arrow, the app wasn't reliably crashing, can't really say more...

And probably a lot more~ Will maybe come back later ^^

**Comment by Drutol** [comment]
As for these crashes, they happened in the background because of copy to search... it seems to work even if you are outside of app. Starred messges crashed because key that went into the things was *null* for some reason.

**Comment by Drutol** [comment]
There's new version available with stuff.

**Comment by Kimod** [comment]
More stuff!
* No word wrap in Reply: - http://puu.sh/tEik4.jpg
* When I clicked on the quote, it asked me to search the store for an app. Do I need that other app you've made for redirecting links to your app or is this a bug? - http://puu.sh/tEiQE.png
* For some reason (too many comments I guess?), next page of this forum page won't load https://myanimelist.net/forum/?topicid=334 - http://puu.sh/tEjpx.gif
* Maybe related to the issue above but I will list it anyway - On high amount of comments, "go to page - last", won't go to the last page, but to the page before that - http://puu.sh/tEkt0.gif

Also no crashes in this version related to forums! yaay \o/

**Comment by Kimod** [comment]
I think these are the last issues from me, forums working somehow reliably for me, yaay o/
* Unnecessary scrollbar on the left and no word wrap when creating new topic - http://puu.sh/tFrxr.gif
* Another case of double spaces! - http://puu.sh/tFrnl.png "Forum -  " and if there is "Locked:  " there are 2 spaces after locked: too (casual discussions is really creepy place… I love it)
* Still some crashes when I'm navigating to starred comments… - http://puu.sh/tFsq2.gif

January almost behind us and you spend all of it on UWP... You should be ashamed that you left your android baby in the corner! Looks like MALclient will be your lifelong project :D

**Comment by Drutol** [comment]
The thing is that UWP is a breeze to develop in and the only reason why I spent whole January doing UWP (aside of @sinofanger moaning ;d) is new Visual Studio 2017. They brought so much new stuff that I just cannot stop doing things. But hey, I've my last exam on Wednesday (hopefully) so it's the whole February semi-free after I'm home from work :D

**Comment by sinofanger** [comment]
![angry-panda-amazing-drawing](https://cloud.githubusercontent.com/assets/9476430/22405793/2cdc0a5a-e66e-11e6-89cb-92c74a63c857.jpg)

>.< Because of my moaning (one of the reason), the app is soooooooo awesome right now.

**Comment by Drutol** [comment]
I was wondering whether you are still alive ^^ Are you over with your illness?

**Comment by Drutol** [comment]
Next version is up!

**Comment by Kimod** [comment]
The quickest report yet!
* Preview being weird - http://puu.sh/tFzqV.png
* That double space... - http://puu.sh/tFzDv.png - add the space where you deleted it and delete that space that I selected xd

**Comment by sinofanger** [comment]
@Drutol  Ya, I am back, kicking.

**Comment by Drutol** [comment]
🎉🎉🎉

**Comment by sinofanger** [comment]
<img width="428" alt="error" src="https://cloud.githubusercontent.com/assets/9476430/22426202/7d48ab2c-e724-11e6-8fb6-58bb393bc8fc.png">
This notification issue still happens. The app randomly shows some old notifications on start-up or resume or restart. From the image you can see that it is showing one month old notifications to me, today.
@Drutol

**Comment by Drutol** [comment]
This appears because it wasn't marked as read and after app reinstall data about displayed notifications is lost.

**Comment by sinofanger** [comment]
@Drutol  I did not reinstall or update the app. This shows whenever I restart or wake up my laptop.

**Comment by Drutol** [comment]
Count me surprised, these only re-appeared to me after I redeploy/reinstall app.

I'll mark them as read if user interacts with them.

**Comment by Drutol** [comment]
I'll be uploading package to the store tomorrow afternoon.

**Comment by Drutol** [comment]
IT'S BUILDING
I'm a bit scared actually ;d

**Comment by Kimod** [comment]
Don't worry, I tested it more than any other build ^^ well maybe the lurking I was doing wasn't enough, @sinofanger should have at least downloaded it and do some of his basic forum posting :3 Let's hope for the best

**Comment by Drutol** [comment]
Hehe, I found 3 more rather annoying bugs just before clicking the button :D
+ I have problems to actually package it, because something...

**Comment by Drutol** [comment]
Well, I'm unable to build a package because Visual Studio refuses to do so. I wrote to support and now I'm waiting for response...

**Comment by Drutol** [comment]
The thing is in certification now! Let's see the world burn!

**Comment by sinofanger** [comment]
@Drutol  Yo, I was busy with uni works. Well I can see the build live. Shall I install? Each time I update I get all my past notifications :( *nags*

**Comment by Drutol** [comment]
Now if you click on them they will show no more.

**Comment by sinofanger** [comment]
Ok ok, by the way, now that native forum is done. What is next in your agenda?

**Comment by Drutol** [comment]
Android ;d

**Comment by Drutol** [comment]
February is the month of android, I will make issue with february plans later today.

**Comment by sinofanger** [comment]
Going to use material design?

**Comment by Drutol** [comment]
I'm going to use the design which will work with current UWP mobile design. I'm really not fan of this design so yeah.. as much as I can.

**Comment by sinofanger** [comment]
In the new native forms wht is a "pool question"? I think you meant "Poll Question" right? That might be a typo. 

Also, is there any method to drag and drop images into the forum post and buttons to embed youtube links? I know MAL does not allow that, so guess you will have to rely on imgur api or something like. I donno, try it if it seems worthwhile. @Drutol

**Comment by Drutol** [comment]
Wohoo, now that's something big and complicated, while adding editor buttons for bbcode is something I have in mind, uploading photos is something I'm not going to do. One can only do so much offtop xd

Pool questions, you can only ask questions about pools obviously. Try asking something different and my neural network will BSOD your computer... xd

**Comment by sinofanger** [comment]
-_- admit the typo lol. 

Also I made my first post using your native forums, worked well. The text typing area could be improved. Try typing a long text and some text goes beyond screen area. The preview area works well.


Well or you can just create buttons to that insert or wrap bbcode around content. Buttons for "bold", "italics", "underline", spoiler", "youtube" etc. That should be better right?

In the MAL news section, could you implement comment section. Is MAL using disqus? 
And in the news section, can you show news from anime news network? I asked because most MAL news are copied from ANN. ANN is the official source for English anime news. So ANN news is way better than MAL news.

*thinks*

**Comment by Drutol** [comment]
They typo is a lie!

How could I forget to add wrapping there, I think I added it at some point...

These buttons will come, I'm quite hyped for them.

I do not plan doing anything with news right now, too much hustle right now + there are exact copies of them on the forums, right?

**Comment by sinofanger** [comment]
ERROR!!!!!

@Drutol  The native forums are not showing replies I am getting on my forum posts -_-. No notifications as well. Now am using website of MAL. I think the post thread is cached or something, it is not being updated with new replies

**Comment by Drutol** [comment]
Hmm, notifications are handled by mal anyway. It seems like I forgot that you would want to refresh forum page... lurkers were unable to notice that :D

**Comment by sinofanger** [comment]
Not the forum page. The new topics that I create, I want to refresh them, or else how will I see the replies and new comments. Put a "refresh button" just like the button in main forum area. Also, if possible enable background refresh every 15 minutes or so. 

I am telling this because, without refreshing and notifications, now I am relying on MAL website notifications which I get on my email inbox -_- That is counter productive when I have an MAL app dedicated for this.

**Comment by sinofanger** [comment]
@Kimod  -_- What exactly did you test? You did not spot these two minor errors? >.<

**Comment by sinofanger** [comment]
@Drutol  Error -2 

In a forum thread each reply box is scrollable. Why is that needed? It makes it so hard to scroll through a page, because instead of the page the reply box gets tried to be scrolled. Try scrolling a forum posts with large number of replies; use your laptop track pad to scroll.

**Comment by sinofanger** [comment]
@Drutol  Error 3

In a new forum topic, when we reply to someone's comment, our reply is nowhere to be found. Just reload the entire thread after each reply or comment is made.

An easy way for you to understand these is, just make any forum thread in the recommendation thread like: "Suggest me some anime like Yuri on Ice". Then you will star getting comments from people and try replying to them, and you will see all the bugs that I have pointed out.

**Comment by Kimod** [comment]
@sinofanger I can actually answer a lot of those!
* I have notifications turned off, because email is more reliable and also I don't want double notifications and also I don't have any forum topics created
* Scrolling in each reply box is one of the main reasons, why native forums were a really big thing to implement, there isn't an easy way to handle that
* I reported that there is no text wrapping in replies and new topics
* A lot of your problems would be solved with refresh button
* And I don't have a problem with questions about pools ^^

**Comment by sinofanger** [comment]
@Kimod  pool is a typing error. Also, it is not about you or me. When we are beta testing anything, it is always about the general end-users and making sure everything is working for them.

**Comment by Kimod** [comment]
@sinofanger I know, that's why you're better suited for testing forums, I'm not really using forums in my free time, you are using them 24/7 and using every feature, they can offer, so your feedback is more valuable than mine ^^

**Comment by sinofanger** [comment]
Aah it is fine. I was just telling. No actually, I use forums only for getting anime recommendations. MAL users are very knowledgeable when it comes to recommendations and suggestions. Anyway hope @Drutol  sama starts troubleshooting all of these.

**Comment by Drutol** [comment]
To sum up:

* Refresh button
   * *Auto refresh*
* Scrolling I can assure you that they are not scrolling for me... I've been fighting with it for 1/3 time of developing whole forums. What's your screens dpi?
* Well, I'll later check how it behaves on new thread, but it works on existing ones.
![gif](https://cloud.githubusercontent.com/assets/6102530/22596291/3c389458-ea2b-11e6-9457-8115b080c395.gif)
* I'm now willing to add there emoji of pool 🏊 there, it's more and more compelling.

**Comment by sinofanger** [comment]
Ohh, if those issues are fixed. Please upload the new package to Windows store. My version of the app is not useful right now :'(

By the way, instead of having blank color background, why not allow users to set a custom pick as app background like Windows 10 Mail. 

Or, even more better: you can provide an option to automatically change app background every single day, by making use of images from Reddit. More like Bing's "image of the day". But I think you will need to make sure the picture size that is randomly selected will match with the user's screen resolution. That may be a headache.

**Comment by Drutol** [comment]
Okay, I'll catch up with Re:Zero webnovel and I'm off to fixing stuff.

**Comment by Drutol** [comment]
@sinofanger what's the DPI of your screen?

**Comment by Drutol** [comment]
I'm unable to reproduce missing replies. I've just created new topic with new reply and everything works.

**Comment by Drutol** [comment]
Here you go by the way...
![image](https://cloud.githubusercontent.com/assets/6102530/22601178/0aae8a7e-ea3e-11e6-910b-49a211fa5522.png)

**Comment by sinofanger** [comment]
@Drutol  The DPI is 166. Why does that matter?

I was recently watching Re:Zero anime, then dropped it. Then started watching Drifters.

**Comment by sinofanger** [comment]
Also, if the forum errors are rectified, please upload the new package to the store :)

**Comment by Drutol** [comment]
Uploading new store package isn't something I can do instantly (you cannot certify during weekends anyway), I'll upload test packages today/tomorrow.

166!? Wow... That's the reason why it's broken, I don't know how to calculate it to "magical Microsoft units", can you get a normal monitor like everybody else? /s

**Comment by sinofanger** [comment]
😞 its my laptop. I cant tear off the screen, u dummy.

Well, i will wait for the bug fixed build. Will rely on website till then.

Sent from my iPad

On Feb 4, 2017, at 11:56 AM, Piotr Szymczak <notifications@github.com<mailto:notifications@github.com>> wrote:


Uploading new store package isn't something I can do instantly (you cannot certify during weekends anyway), I'll upload test packages today/tomorrow.

166!? Wow... That's the reason why it's broken, I don't know how to calculate it to "magical Microsoft units", can you get a normal monitor like everybody else? /s

**Comment by Drutol** [comment]
This is my laptop... you can certainly do it :D

![wp_20170204_08_28_09_pro](https://cloud.githubusercontent.com/assets/6102530/22616783/8bce50b4-eab4-11e6-910a-f4bcd18e5b72.jpg)

**Comment by sinofanger** [comment]
So, which laptop are u using now? Or your system config?

**Comment by Drutol** [comment]
I don't use laptop ^^ My monitors have standard 96dpi, and making sure that it both works for me and you is going to be problematic... maybe simple ratio will help if it works on 96 ;d

**Comment by Drutol** [comment]
Found a bug which could result in missing replies.

**Comment by sinofanger** [comment]
Ohh, ok ok. Well I don't use much UWP apps, so I am not sure how scaling works in them. What about you? Other than Readit and MALclient, you use anyother app from the UWP store?

Ohh, :) that is nice, hopefully it gets resolved soon.

**Comment by Drutol** [comment]
MyTube is also great. 

The thing with scaling is that the height come in pixels from javascript and I have to manually convert them to uwp units which isn't something you do really often.

**Comment by Drutol** [comment]
Primitive bbcode "editor"
![image](https://cloud.githubusercontent.com/assets/6102530/22617917/408c7b0a-ead0-11e6-8657-143eebd55627.png)

**Comment by sinofanger** [comment]
Nice, if everything is done, pack it into a build and upload to UWP store ^_^

**Comment by Drutol** [comment]
My lumia has 144 dpi and everthing scales correctly... are you sure that every post had scroll enabled?

**Comment by sinofanger** [comment]
Yup. I usually post in the recommendations section. In it all posts and replies had this scroll enabled. Let me ask, even though it is a native forum, you are scrapping the threads from the MAL forums, right? So why is it not possible to just show the posts like it was done before? I know the answer is not gonna be simple, but if possible explain; I can learn something.

**Comment by Drutol** [comment]
By native forum I call one that's not one big web view with whole page restyled by JavaScript. Each post now has little WebView which needs to be manually resized to avoid scroll and I don't know why it doesn't work for you as dpi is not the case here.

Rendering this in xaml would probably take 5 years and a research team... + this works pretty damn good except for you ;d

Are these containers of different sizes at least?

**Comment by sinofanger** [comment]
![image](https://cloud.githubusercontent.com/assets/9476430/22619598/fa2bc424-eb1d-11e6-985b-3fcbe31c7257.png)

This is what I mean, when these containers become scrollable, the page does not scroll well unless from outside these message containers.

**Comment by Drutol** [comment]
You are not using touch input right?

**Comment by Drutol** [comment]
Make SS of first post of my thread on forums

**Comment by sinofanger** [comment]
Yes it is a touch enabled screen. -_- But am using my touchpad. I just tried scrolling with finger (touch), that works flawlessly. These containers become active only when using touchpad.

**Comment by Drutol** [comment]
It shouldn't work with touch... on phone version I hat to put transparent panels that captured all inputs before WebView which would disappear after tap enabling interaction with WebView. (WebView scrolls **always** with touch regardless of what I try). I don't have any touchpads around to test it.

**Comment by sinofanger** [comment]
Well, I am not sure why, as touch input, there is no scrolling of container. Is not that a good thing?

 The only issue is with touchpad. but its fine, i can scroll from the left hand side (outside the container area). So you focus on remaining troubleshooting, leave this container issue for the time being.

**Comment by Drutol** [comment]
It's not a good thing because it works differently on phone and screens with touch. Touchpad should behave as scroll wheel and it's not.

 I'm at loss now... I'm implementing the same strategy as on phone right now i.e. if touch is present hide WebView behind another element.

**Comment by sinofanger** [comment]
:P Something just occurred to me. I was thinking, how awesome it could be to say "Hey Cortana: Check for new anime episodes today" and lock-screen notifications from the app "New episode of Drifters airs today at 10:00pm EST"

I know you don't like Cortana, but just placing all the potatoes on the table ^_^

**Comment by Drutol** [comment]
You know what? Take an example from @Kimod and make big issue with all your requests on the 
* List
* so
  * it's easier
* to track everything
* :)
Test version should be available in a few hours.

**Comment by sinofanger** [comment]
@Drutol  Ya I understand what you mean by "it's not supposed to do that". I think I told you I wrote a webscrapper in python to scrap images from a webpage and all the concurrent pages  linking from the webpage and store it into my desktop. But for some reason the program terminates after scrapping 3-5 pages. Still have no idea why it does that. -sighhhh-

**Comment by Drutol** [comment]
Well, I'm not sure how can I help you with this much info xd

**Comment by Drutol** [comment]
Click through this one :)

https://github.com/Drutol/MALClient/issues/73

**Comment by Drutol** [comment]
@sinofanger Call to arms :)
I want to send this for certification in a few hours ^^

**Comment by sinofanger** [comment]
😨 I am actually outside right now, just roaming inside a Playstation store.

I think this build will not be having any issue with forum. Just a feeling.

**Comment by Drutol** [comment]
> I think this build will not be having any issue with forum. Just a feeling.

*Wishful thinking*

Sure, take your time. I'd just like somebody to click through it from active forum user perspective ^^

**Comment by sinofanger** [comment]
Lol, I am make up questions in forum just for checking out the app. I simply ask random questions like “which anime should I watch after Drifters?” etc. I am the least MAL forum user. 
 
But yeah, I also think it will have least issues. I just saw the latest Macbook Pro lineup. The Mac OS is really top notch when it comes to design and a feeling of wholeness. I mean Windows 10 still looks like part Windows 7 with two Settings center (settings and control panel). *sighhh*

**Comment by Drutol** [comment]
Yeah you are missing on usb connectors and they are awfully expensive for what they offer hardware-wise. These things should die already. /rant

*Apple hater* - 2017

**Comment by sinofanger** [comment]
Lol, Its not like I plan on switching to Apple (unless they make a Mac which is detachable, touch-enabled or 2-in-1, which will never happen, I guess). 
What I am pointing out is the way in which apple design their software, their mail app, Mac OS; just their software. Like when we compare Apple music with Groove Music; that is what they are implying.

**Comment by Drutol** [comment]
I won't argue here as I've little experience with the apps there. I did have an iPhone a few years ago (3GS) and in my opinion it was unusable without jailbreaking, this was the best feature of that phone ^^.

**Comment by sinofanger** [comment]
Ya, anyway, I seriously hope Windows 10 becomes more "full" when creators update releases this March.

**Comment by Drutol** [comment]
So what's missing?

**Comment by sinofanger** [comment]
proper contextual menus, depreciating control panel. proper icon sets, making Edge more stable, MAPI for mail.. etc etc...

**Comment by sinofanger** [comment]
SUGGESTION: 

You said you cannot do anything about the notifications, right? Why not provide an option to select "Mark all as read" or "Mark as read" for individual notification, instead of "open topic"?

That way people can easily close notifications, so that they never come back again. The app shows me at least 20 old read notifications from the past every single day.

**Comment by Drutol** [comment]
So why won't you mark them as read?

**Comment by sinofanger** [comment]
Because there is no "mark as read" option. The only option is "open topic" and "dismiss". Dismiss does not work, I am not going to open topic of all the 20+ old notifications.

**Comment by Drutol** [comment]
You have button "Mark as read" in notifdixation hub

**Comment by sinofanger** [comment]
Nope. I can only see two buttons for MAL notifications: "Open Topic", "Dismiss".
For apps like mail I can see the option "Mark as Read".

**Comment by Drutol** [comment]
> You have button "Mark as read" in **notifdixation hub**

**Comment by Drutol** [comment]
I'll add these today though

**Comment by Drutol** [comment]
@sinofanger  Time's up. I'm uploading packages to the store.

**Comment by sinofanger** [comment]
Sorry about not being able to test it. Was and is stuck with some assignments. I could see that it reached the store. That was pretty fast. I will update it and let you know how it is... :)
@drutol

**Comment by sinofanger** [comment]
@Drutol  By the way, I wanted to ask you, after Android version of the app is released, what is your plan? I asked because by the time android app also becomes popular, we will have a huge fan base...

**Comment by Drutol** [comment]
By the time Android app is finished whole world will be conquered by Windows 10 Mobile :D /s

I've no clue to be honest, I cannot foresee so far in the future ^^

**Comment by sinofanger** [comment]
Lol, by that time I just wish Windows 10 mobile does not become an exhibit at the museum of natural history. I think, android app will become a lot more popular. How many installs of the Windows 10 app have taken place so far? You will be having some sort of analytics in the windows store, right?

**Comment by Drutol** [comment]
4k downloads after 10 months + 1,2k monthly users as of know

**Comment by sinofanger** [comment]
That is good. Considering the fact that a few people make use of UWP store and the anime fans among them are even fewer, and the anime fans who use MAL are way smaller than that.
