### ISSUE TITLE
@FoxInFlame Remarks

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#97]
I got some more feedback from yet another perspective! (from @FoxInFlame)

http://imgur.com/a/g4nLp

Just putting it here :)

**Comment by FoxInFlame** [comment]
As I also sent on MyAnimeList:

> I also think that the Images page on MALclient should be auto-loading new pages at the bottom.
> 
> You see, since the page has these kinds of pinterest-style flowy feel, it's very weird to just cut it off at the end without even giving a straight line end (some pictures go lower than others)
> 
> These styles do not fit pagination, and it's to be honest, a little ugly. I think that auto-loading the next page and appending it when the user starts reaching the bottom would be a better way to do this. 
> 
> Just stating my honest critical feedback here.

**Comment by Drutol** [comment]
Yup, thanks a lot! I've just sent next update to the store with forums... and I'm half dead now ^^
I'll elaborate more on your input tomorrow.

**Comment by Drutol** [comment]
Let's begin:
* Friends Feeds
  * I 100% agree with you.
* Profile items
  * If you keep it squeezed like this it sure is big but I want to have these items consistent throughout the app. I'll experiment with adaptive design though.
* Messaging button
  * It's in certification right now :)
* Unclickable profile stuff.
  * This is meant to be unclickable, these serve as a labels and this general label is attached to the uppermost section.
* Freezing
  * Well, by freezing you don't mean that flyout captures all clicks once?
* Images incremental loading.
  * This one is certainly tricky due to nature of the panel that arranges items (which I had to write from scratch) of various sizes that are resizing in runtime and it was made as little fun addition to the app. The performance would be worse because I wouldn't dare to write virtualisation for this thing, and to be honest I've more important things to do... *like android...* . Inconvenient, a bit ugly but it works. Added to the TODO list :) 

Oh, and welcome to this magnificent issues board :D
Now I feel obliged to click through your extension ^^
