### ISSUE TITLE
February plans!

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#98]
### What's gonna happen in February?

Semester is over, exams are over, native forums are done... That means that I'm going back to this little green slimy robot... ^^

For UWP except ususal small tweaks and fixes I've planned pools and signatures... I'll do them when I'm irritated enough with android. I'll also may start research with list comparing.

I don't have any ETA's though :(

**Comment by Drutol** [comment]
And my grand plans were reduced to forum fixes for now :D

**Comment by sinofanger** [comment]
*ahem ahem*
