### ISSUE TITLE
new list option

### ISSUE THREAD

**Issue by Kuraze** [Drutol/MALClient#99]
can you add an additional function for custom list the watched animes ?
 for example: an ID to set for every anime myself so i can sort them manually by ID.

is this the right place to ask something like this ?(first use of github)

(sorry for bad english, i'm not a native speaker)

**Comment by Drutol** [comment]
Yeah it's the right place... Welcome :)

So you would like to attach custom "tag" to each entry for further sorting, right?

Definitely doable but right now I'm fighting with forums which were just released and I have to add it to the TODO list.

Thanks for feedback!

**Comment by Kuraze** [comment]
I'm looking forward to seeing this feature and thanks for quick reply.

**Comment by Kuraze** [comment]
how is it going ?

**Comment by Drutol** [comment]
Well, other things are coming up and I'm not really hyped for this so I cannot really say when I'll do it :( Sorry

**Comment by Kuraze** [comment]
ok
